Class {
	#name : #AdventOfCode2020Tests,
	#superclass : #TestCase,
	#instVars : [
		'aoc'
	],
	#category : #'AdventOfCode2020-Tests'
}

{ #category : #data }
AdventOfCode2020Tests >> dataForDay01 [
	^ #(1864
1192
1802
1850
1986
1514
1620
1910
1557
1529
1081
1227
1869
1545
1064
1509
1060
1590
1146
1855
667
1441
1241
1473
1321
1429
1534
1959
1188
1597
1256
1673
1879
1821
1423
1838
1392
1941
1124
1629
1780
1271
1190
1680
1379
1601
1670
1916
1787
1844
2000
1672
1276
1896
1746
1369
1687
1263
1948
1159
1710
1304
1806
1709
1286
1635
1075
1125
1607
1408
1903
1143
1736
1266
1645
1571
1488
1200
211
1148
1585
2005
1724
1071
1690
1189
1101
1315
1452
1622
1074
1486
1209
1253
1422
1235
1354
1399
1675
241
1229
1136
1901
1453
1344
1685
1985
1455
1764
1634
1935
1386
1772
1174
1743
1818
1156
1221
167
1398
1552
1816
1197
1829
1930
1812
1983
1185
1579
1928
1892
1978
1720
1584
1506
1245
1539
1653
1876
1883
1982
1114
1406
2002
1765
1175
1947
1519
1943
1566
1361
1830
1679
999
1366
1575
1556
1555
1065
1606
1508
1548
1162
1664
1525
1925
1975
1384
1076
1790
1656
1578
1671
1424
757
1485
1677
1583
1395
1793
1111
1522
1195
1128
1123
1151
1568
1559
1331
1191
1753
1630
1979
953
1480
1655
1100
1419
1560
1667 )

]

{ #category : #data }
AdventOfCode2020Tests >> dataForDay02 [
	^ '13-15 c: cqbhncccjsncqcc
2-3 v: zvdvfd
9-14 b: rbrbnbbbqdfrht
11-12 k: kkkkkkkkkkxqk
4-5 b: bqbbdm
10-12 w: kwwkwwwrwzzwwwwzwswx
1-11 g: grrmgmqgghw
4-5 m: mbmhmvmwdvxmvpw
1-13 n: ndnnnnnnnnnns
11-18 l: lllllllllllllllllll
4-5 c: cccscc
2-4 k: bkfr
9-13 k: lcmsvkknrxtkkksgvkjg
1-2 b: bhwgb
1-4 j: zjjcjj
7-11 g: nnffggdmggr
3-4 z: zzhzz
4-10 g: mggkgvgggmggkggmqg
4-5 n: dcmnl
11-15 s: gzpdvsmnzsshswzs
10-14 x: xmvpxjtlxxhxtpdhsnx
5-15 v: zzhjdpgxlsvphzv
4-8 k: dsfktqchpkk
6-7 j: jzjgjqld
12-16 r: rrrrrrrrrrrhrrrrhrr
1-2 l: lllllll
2-3 q: jqxwtggmgqmzpljdvkt
8-11 p: xpmcppppwvzp
7-8 c: vwcvkcct
4-10 d: lsmdffzdsrk
2-3 p: sxpg
4-11 p: rzlgxshhpbp
1-4 b: qbbbbbbbbbbb
6-11 m: zwmzmmlbmxgphkks
1-4 n: lnnnn
15-16 h: hhbdmbhchhhkhhrw
10-11 k: kkkqtwkkkkkkkkn
2-13 m: mggmmxmrzmwglbmmm
12-14 g: ggggrggggxgwhggggd
7-11 l: llbqsqlkvll
1-3 f: ffff
4-9 h: qvnhvcmpmfdbqhkdsg
3-8 d: ddsdddddd
14-15 j: qjjjzjjjjjbxmjs
3-5 j: jjjjtctjjjs
12-13 q: qqqqqqqqqqqqgqqq
1-8 p: xpppzdpp
13-15 f: lnlnlkcwgnfqgmfhlwm
12-17 g: gfgtgrvcxggggtggjg
6-8 r: rrrrtwrqrrr
9-12 r: ctldssjlrzhvpmqrtxd
1-6 k: qkkkdkkkkkk
17-18 x: bxrxxbxxzpbxnqxcsmn
2-4 c: ccmr
1-7 m: mmmmfrdmmmhl
9-12 d: ddddddddxddhd
13-14 f: ffffffffjffbbff
4-6 c: ccchcc
6-7 r: rrsrrrrcrrjbrrrr
9-15 w: wzfbtqrwwgtmbxn
6-7 q: qqqqqqrq
1-7 l: lgpqzhlkb
6-8 d: dhddkndp
2-5 m: bjxmmmmm
5-16 t: nbgjntfhpwtbrcftxt
5-7 k: kkkkkhbkkkkk
8-19 t: dsdstttfjhnttttvgttt
3-4 t: ttltttt
1-5 l: flfllllllllbhldll
7-10 x: xxxxxxcxxxx
2-7 t: ttttttctttt
3-12 x: vlxfwpdncxzkmkxt
1-5 b: mbbbbbdbbbtbwbhpbt
3-16 q: fpqkkkqfkqdbrxlq
5-6 p: lpcbtppjpt
6-7 w: wcwwhwv
9-13 v: vvvvvvvvvvvvvvv
1-4 g: vgggtggghgggggggg
2-9 p: mppsrrzwxdt
4-5 f: ffffdfffffdf
2-5 x: xkjss
13-14 z: zzzzzzzzzzzzbhzz
2-10 p: xmtkzpbrrj
17-18 t: ttttttttttttttttttt
2-8 j: cjjqbzpd
4-12 z: zzzkzzhzzpzzdzz
1-2 d: rdcdt
2-3 j: wnltj
7-9 r: rlrfbrdrqrbdr
3-4 s: bcsss
12-14 h: hhhhhhhhhhhbhhh
3-5 h: rfhlc
8-15 f: ffffffflffffffff
3-15 s: ssxsssssssssssss
2-4 h: hlbhshhmhhhg
12-13 r: rrrrrrrrmrvrnrr
3-5 p: ppppjp
1-2 z: zqhdkgqqzfsxkjjzg
6-8 k: kkkkkkzd
1-12 h: qhhhhhhhhxhhhhh
9-14 p: ppppppppqppppfp
2-4 t: tsttt
18-19 t: cttttllttttwxtttttt
10-11 t: rkdbpntntttfw
4-14 m: mdmmgtlmmwmbmmmk
4-6 n: xxhnpmnfnn
15-16 g: ggggggsggggggggng
14-15 k: kpjxmkrksskpbwk
15-18 f: fffffsffffffffnfffff
18-19 p: gwpplnpndvpxgzjvhbpp
8-12 l: ldclrkllbgpwllllcxms
14-19 w: pxsjbtwwhdkptwcxwvr
2-17 m: mtmmmmmmmmmmmmmmmm
12-15 b: nbcsplrmvbjbqlc
1-4 z: bzzszzzzz
1-13 t: tttttttttttttttttt
6-7 j: jjjjjmvjjjjjjjjjjj
10-13 l: llclllllljllllll
11-12 c: mzckxzsbbxcq
2-14 k: kkckkkkbkkkkkrkkkkkk
3-5 s: msssvqszssprssss
7-10 f: fffffffffrf
2-4 l: dlwrl
3-7 v: slqgljmrqrwv
4-6 d: pdddddnddddddd
6-9 f: cnfffpfzfffffff
4-17 v: vvvnvvvvvvvvvvvvvv
7-9 q: qqqqqqqqkqqqqqnqq
15-16 q: qqqqqqqqqqqqqqqqqq
10-11 g: cgtrgggggggggg
10-12 x: xxsxxsjxfxxlx
3-12 j: jjljjjjjjjjjjjj
8-9 c: ccbccczccthcc
4-17 h: hhhfhhshhhhhhhhhhhh
1-2 p: prppr
4-12 q: qqqdqqqqqqqqqqq
7-11 b: bbmbqbrtlwb
4-7 l: lllhlllllz
3-4 r: rrqc
5-14 r: rrrrcrrrrrrqrrrrrrr
10-11 d: pxdcxxjsddd
9-11 s: sssssssspssssssss
1-2 j: jfjljjjjjjjjjjjjjj
3-4 v: vqnvvv
2-3 c: wlcntvmsshxcgzc
9-14 t: rbbljpttwwjtbj
10-11 s: gnrdtfzttks
1-4 x: xpxjxhdxx
9-12 c: chccccccmpfccc
14-16 j: jjjjjjjjjjjjjxjjj
5-6 d: rpdndsbddwdd
9-13 x: thpdhlcwxcxxvxbv
4-6 g: nfsgqnvbntgwvlzlmmxg
3-4 d: dttdcdtq
2-4 n: wnntzbr
2-10 j: jtpszbpjfjcgdjg
6-7 b: bdspbvb
10-14 z: vzznzzzwzlzzqzj
7-8 c: cccccccc
7-11 h: hklhdhssfbz
7-8 h: hhhhhhqzhhhhhs
3-5 b: bcgbwbbbbbdb
5-6 q: qqlxqbgtqpkqt
8-9 q: qqqqqhqkq
2-4 q: qshp
8-13 g: gggggggrgggbgghg
1-5 k: ktcpgpk
2-13 v: mvvwnvfkjrhvvdvvtsvk
12-13 k: kxpkkkckjtkkj
12-18 h: xhqngjkxqqzqhnhhhh
11-12 k: kkkkkkkkkkkjk
2-4 r: rdgrrr
3-4 x: xwjx
2-6 c: lcqzflc
13-14 t: smlkctgbsqpftx
4-5 b: fxtdbzbqbd
4-7 s: wmsssznjzsdkgvdsxhd
2-6 z: wpptkhk
14-16 p: pppppzpppppbprppppp
6-7 c: cccccbw
1-6 h: mhhhhhh
2-3 k: cwkgk
3-4 l: llcl
3-4 m: kmmx
14-20 h: hhhhhhhhhhhrhhhhhhhh
8-12 b: bcmbpbffwghcvjb
10-15 f: fffdfqwmzfdfrfdbpf
1-2 l: hlllljl
1-3 g: vgbgg
2-4 n: zgfn
18-20 w: gmbwtzgzpmdwstsffqzw
9-19 j: jjjjjjjjkjjjjjjjjjjj
16-19 f: fffffffffffffrffffzf
8-20 l: htdlzwsllllccwlflstf
3-4 w: wwww
2-4 b: sbbz
4-6 n: nnrzbbnlcrnsbk
7-8 c: wmzjtbvw
5-7 l: cldlljlzzz
5-6 h: hhzhbhhg
4-5 f: scmrfftkc
11-12 m: flfrbmdpdkpm
6-7 v: xvvvcvkbnvvq
4-11 h: qkjphjpfllhpqnbm
2-5 b: bqbwbbwsb
1-8 c: cqcscccbccrccq
1-13 c: cccccccccccckccc
7-8 h: hhhhhhhs
1-3 l: llxl
6-8 h: hhhhsnkv
6-13 m: mmmmmmmmmmhmpmmm
6-9 n: nrnmmnbnmn
7-14 k: whkpphhkxlnnmkbhtnt
4-10 n: nnnnnnnnnhkn
3-4 c: mcnw
8-13 b: bbbbbbbgbbbbbbbbb
8-9 c: lcccdkjcjrqwck
3-13 w: szmnhsmzwpdbkhtbf
4-5 r: prrrz
9-14 m: mmmmmmmmgmmmmmm
7-8 q: kqpgrqqp
16-17 p: fzxxpcpdhmvmrnvjp
7-9 v: vvvvvvqzxs
3-4 w: qwxw
1-2 x: xqkx
9-10 v: vccmlrlhvdtttfvcxwm
11-14 h: mhvthqhvhhgmfhhhkhch
3-4 n: nqzw
2-5 j: jbjjjjjjjjjjjjjj
11-15 g: bcxggqfmgzgfrdg
3-5 v: gvwvvvrzf
6-7 t: ttzdttr
4-9 j: cgqjqdjvjbfjwdlvdgj
5-6 s: hfflrzksshjqsbvsps
1-4 p: pppn
4-5 g: dprggmpfggbkpg
2-3 k: kbhkkkk
13-15 r: srrrtstrwwxzrrzr
2-4 b: lbbnbzbb
1-4 g: fvgz
5-11 q: hxdhqrqqprpq
2-4 z: zzgm
1-13 w: wwwwhwwwwwwwwwwwww
2-3 k: kkkkk
4-8 g: nlgmhplgcv
1-2 j: zncllmvgjnj
11-13 f: fffffffffffflff
2-8 p: bphqpxkr
2-9 b: bbbbbbfbdbhjpbbbjbbb
9-10 s: zpxnstzwsw
7-16 c: ccccccccccccncsvccc
6-8 r: rrwbrqgr
6-12 v: vvvvvvvqvpvvvvzdd
8-9 z: zzzzbzzmzzz
15-16 t: tfttttntxttqtttc
9-16 b: btbrbfplbbbmbbbbkbb
7-8 q: qrqxrlqg
8-12 q: qqqqqqqpqqqw
5-8 v: jrrlpvvcvkjzjvvvv
11-14 d: dddddddddddddq
5-6 f: rfxmfzf
3-4 t: tttqt
10-14 c: bcccccccccrccfc
3-7 n: snnqplvl
5-6 z: kshzfzhlcsbqwqb
6-11 s: sssssssssmsjsgssss
3-7 v: qgcxvxvg
12-17 v: vkvbsvxkvvnjvvrvvvx
2-4 d: ddrrxbd
8-10 x: tvxxtmgbsxpxbl
7-9 r: rzrbgbrrrrrrmhm
2-4 t: ttttt
5-9 x: xxtwxxnssxlxx
3-4 p: ppdp
3-7 g: ggtgggtg
1-2 k: kbbhjdkfvjqffcss
1-2 l: lrlvlll
10-12 x: xjkbqxkxzxxq
7-9 d: dddhdkpdfdf
5-8 m: mmmmmmmwm
3-9 l: sfrjlzhcll
7-18 m: mmmmmmcmmmmmmmmmmmm
1-3 w: mwplxwwww
7-8 t: tgtctbtrtdtttt
3-6 p: lfpbbgfbpdhnqz
5-6 d: ddddrd
1-3 b: llbbbbb
4-7 r: ktbrncrrnnsrr
8-10 r: rrrrrrrfrrbrr
1-8 l: wlklvlllnljlgtzll
2-4 m: mmhmmxsm
10-12 c: cmwkcnczsxmcrmjtc
2-8 q: qmqqqqqzqq
7-9 v: xvvvvwdnzzv
3-7 j: lsjvmbrjjmpcwqnvvdgc
3-9 l: bgmllldjrzhllsclc
1-6 p: ptppfjpqpp
7-8 r: mctrrstrrxrqtmrr
7-8 d: qddddddxddddddddd
4-11 r: rrrrrrrrrrbr
4-8 s: lsfvtfss
4-9 c: zcccccccj
11-12 v: vvvvvvvvvvvm
4-8 g: rggzlfgtm
3-8 j: jjjjjjfhjsgj
3-4 m: fmhmm
15-16 l: ltllhlljtllllbtlllgl
12-13 c: cccccvcccccqccccc
6-7 q: qqnlqqhqqq
1-8 z: znjqzxpz
10-13 k: kxzmkbxnkbkktmkk
8-15 k: bskzvggzsnlnxzz
9-10 v: vbvvgvcwvs
5-8 h: qhsnhhlhwpvzfb
15-16 g: gdcgggggggtgcgtg
8-9 z: fbgdnrzfb
6-7 d: ddkdddh
4-6 w: xzgfwwlbxft
1-3 h: hkjhh
1-3 p: pwprlp
8-12 j: jdjjjjjdjjcjvjjjjjj
11-14 m: bdsfwddfkgxsmrmm
3-10 m: tmmcmfmmjmm
3-4 b: dwhbzfjxl
2-5 n: nnnnjcnnn
16-17 v: vvvfnvvvltsxhrvvm
1-7 v: qvvvvvwvvvdvv
2-14 k: nxqblwwqmhqzkm
3-4 t: ttts
5-6 c: clnnfk
12-13 s: sssssssssssts
7-14 d: ddqdnwdkdmhddg
3-4 t: tmsttm
9-11 x: xxxtxxxxxxqxwntxj
8-14 l: lllqklwlvlllmbslzlln
9-12 n: sdsnnfncxnwnrn
1-5 f: qfffff
6-9 r: rzmphlrgrr
1-4 m: grdm
4-5 s: ssxsg
1-4 n: xhnznnxnnn
2-6 r: mcwldgbqlqsckgzlrd
1-3 l: llmllll
3-4 p: pjtgdnfjfcjtcnpgxpzq
6-7 m: mmvmmmtn
17-19 h: qgmhhhwwwhqhmhhthhch
3-14 s: lhmnsfdrvnngrsfhxd
1-6 p: pppppwp
4-6 l: lzllltrl
3-4 c: rpxccsc
13-16 h: qsdznfqmsftqqthh
2-4 k: wsvkm
1-18 h: chhhhhhhlhhhhhhhhhhh
17-18 d: xddddddddddddddddddd
2-3 t: jtbrhpzjfpzhcmjql
10-11 n: gjngnnncncnn
7-13 r: rrrrrsrrrrrrlwrrr
10-12 l: llldllslbldllwl
17-19 m: mmmmmmmmmmmmmmmmfmm
10-14 n: nnnnnnnnnbnnnnn
17-18 x: xrxcxxxxxxxxxxxxxxwx
3-4 b: lvxb
5-6 r: rrrrrrr
13-18 l: lllllllllllllllllpl
8-12 m: mmmmmmmqmmmmmmmm
7-8 l: llhqlllh
3-8 p: nmrppdvpxcphxgmkpbsl
9-10 v: hvsbttgsdvvj
5-9 k: kgmvzzzckkgldk
15-20 x: xqxxxjxxxxxxxxxxxxxl
5-6 t: bbwpwtwbhwgqttzjv
6-13 n: klzcfnnjqxrhjwpjfxnk
5-8 d: pcnndzddddnsdqh
5-14 k: kblbtvkwltfklk
4-11 q: zxwdkqqkvqq
10-12 s: tsssssssssssss
3-5 r: rddsrrdksfqfrgr
7-16 h: vdvhlsjxgvrbrxnhns
3-4 z: zxtz
4-8 x: xmnxdwmh
11-12 r: gwsnfrnckrrxrx
3-9 q: qqqqqqqqwqb
9-14 f: bfnfffffvfpfffff
6-9 p: pvpppkppcpp
3-4 m: mmmz
3-5 j: jjjjmjsjjrlkjjjjj
4-6 p: jpbpjs
6-9 r: bswdsrksdrzrgrfmjr
8-10 l: lllllllxll
3-7 v: vvhvvvvv
4-11 n: mnjpbldngrrkbthhmdp
2-4 r: frlrfblsrfzrhtpk
16-17 h: nbghhnzshclxhhmkr
2-5 z: zfzvzzzzzzzq
1-5 l: lllzlfl
9-10 d: dddddddddzd
11-12 p: pspppppppbzp
5-9 t: thzttpxrdhttdwqjsg
7-10 w: tfdfwlwwzdvpnww
4-6 z: fvcljzllwhbzscx
14-15 m: mmmmmmmmmmmmmcd
8-11 d: hgdmwgsdkdbghb
13-15 v: vmvdvvqvvvkvqvvv
13-14 f: fffffffclffffffmf
2-5 s: ssscn
11-13 w: wwwwwwwwwwwwww
7-9 l: xnwrlkskll
8-14 g: vggglvcrgscpgggt
4-5 w: wwwww
5-11 w: wwwwswwwwwwwwwww
6-7 g: gggbvjg
14-18 q: wqfqqqqqqnqsqrqqqq
6-7 z: zzzztzqczzzzz
6-12 n: wnnnnnnxftnkznpvvl
10-16 j: jjjjjdjjjrhjjjjj
1-10 l: lllllllllrll
9-13 g: gdgggggggggkggn
6-8 r: rrrrrrrs
16-17 k: kkkkkxkkkkkkkkkck
11-14 b: bbbjbxbfmqscqbdmgg
3-8 d: sjdkmjppbdddhdxd
6-7 g: xhkhwgqpbg
11-12 x: xxxxnxxwgxxbdl
6-8 c: cccscccwcccccccccc
9-16 h: vhhhhhchwnghmkzhr
5-9 v: vvvdnvvvvv
4-16 n: nmqncgnbfhqnnpnbxwrl
3-5 f: fljrf
13-14 m: mmmmmmmmmmmmgfmmmmmm
5-6 g: ggnggd
2-6 w: wlvhvw
13-18 h: hhhhhhhhhhhhhhhhhvh
7-19 m: mmmmmmmmmmmmmmmmmmwm
4-12 k: mcvtrtsdkvkkfjrmkn
1-8 t: qvmrtttn
6-7 f: fffffsf
10-11 m: mmmmmmmmmjl
15-17 v: mvrhvvvvnvrvzrvvfv
10-14 m: mmtmmmnmmmmmmxm
4-16 b: vcscdqcbcxswjfdbrqbx
8-9 z: zzzzzzznzvz
4-6 g: ggnggdpgggg
2-4 d: hddxxnzzw
9-10 g: gggggggggj
4-7 k: kkkvkkkkkk
1-3 r: rrrrj
14-15 w: wwwwwwwwwwwwwwwww
2-4 n: brfmln
18-19 b: bxbbbbbghbbbbbbbbwb
10-12 q: dqqqrqwcqgqqf
2-5 g: sxfzgtrxkrmstdzfmw
3-4 d: pcddq
11-16 w: sbqwlwzwwwwwtwww
2-12 c: wrccqxtccccchcccjcj
16-17 b: bbbtbbbbbbbbbbbqb
3-13 t: tttttttmgktdthtp
1-3 t: ttcg
13-14 z: zczzzzzzdwkzqz
5-6 n: bnjhnjhnnq
2-9 b: bjbgbzmlbbklbwt
4-5 b: dtlbbwtjbkzzbghbghzk
10-16 p: ppppppqpppwnpppppppp
5-6 b: cbbwtbjkm
15-16 p: ppppppppppppppqd
4-8 m: lgmmhgktslzhbvw
2-4 h: hhdlhhhhhhhhhhh
14-18 k: ktmkkkkkwkklkjrkklfk
5-7 x: sfxxsxx
8-9 v: lkvxdpvjv
7-8 r: rrrrrrsr
4-6 b: btcbbv
7-13 n: zhnhjhnmkzdbt
7-9 j: jvjjjjjjjjjjjjxjj
1-4 v: hdvfv
2-5 f: rznpnxqwncmtkwfxcxqh
16-17 x: zxgbhltrdhxkvvxsxf
1-2 h: hkhhh
3-4 h: zhxc
4-9 z: vsmzhzwgjxfg
11-13 x: xxxxxxxtzxxxc
11-12 d: dddddddgddqj
4-11 f: zkdhqnpgbff
2-3 q: qqlqgqqqv
4-9 b: bvnblwhbbkswmrhtf
7-13 t: cztskdtqdtrkt
4-5 f: fffcsf
4-9 f: ctblqrflf
1-2 l: lmllqhlnll
3-6 v: vvqvvvvr
7-9 b: bbrhbkjbb
1-8 p: xpppppppp
7-10 k: ckkpmktkqksgkkk
1-7 m: lmmmmmmmmmmmmmm
11-15 v: vvfvvmvvvvdvkvv
10-11 b: kbbbbbbzbhbb
11-12 l: jltgggtlcggllt
10-13 q: kqnqqqqqqqqqq
6-7 c: cjcccczc
5-11 t: kdtstshrhfkcx
3-12 v: vlvfzvwvxvvhvvsvvcvm
9-10 t: xttttttttttt
8-10 z: hctlkgjzvzh
3-5 g: gtkwgk
16-17 w: wwswwwwwwwwwwwwwwqww
4-11 j: lbmwjzjxjpjhzjjpbj
4-5 c: klbxc
3-5 w: wlhvb
4-8 x: xgxxxxxxxxxxxxdxnxx
2-5 n: nnnkhn
1-2 d: dxfd
11-12 w: wjcqszwqwkcb
6-11 v: sqpgzhnvndtmvvwl
3-4 m: mmmqmmm
1-3 d: mddb
6-7 w: wwwwwnwwwwwwww
12-14 z: zzzzzxzczzzrzzz
5-10 f: mtcmmhfftft
10-14 x: hhgvmxbwgxdcnz
10-16 z: wzfzzmlmxxfhzqcbsnl
3-4 p: ppvkppp
8-11 h: hhhkhhhjhpbhhhh
6-12 f: ffffdwffrsfffrffnfpk
5-11 z: xqwzzzzbzpwk
7-9 c: crccccccscccccc
4-5 b: qpcnz
2-13 m: lmnrrzfhmbwtmqbsg
12-13 k: kkkkkkdkkkkkmk
10-14 q: sdqfbqszdjhqfq
8-13 h: hhhhhjhhhhhhbhh
2-4 g: gfdb
12-19 n: wtrhndnnnbwnnnnjnnn
5-6 n: zdwnpn
3-5 f: ffsffffff
11-16 r: rrrvrrrrrrwrrrrrlrrr
6-8 n: nnnnnfnnn
10-13 b: brnlbblbkbbbjbbhx
7-8 q: ftrfnqgqc
11-12 c: ncccccccccgcccn
3-4 z: tzzctzwzzvz
3-5 t: tzrqg
7-10 m: mmmmmmrmmqmmm
1-2 c: cdccfcccc
10-11 k: kkkkkkkkkwkk
6-18 x: qndxdgmjvpppddwkbt
8-17 c: pxhszsccndlbzkwgvx
3-4 p: qlrvwdxpqtgwjrtqcc
2-4 q: lkjq
17-19 f: pffgflzxrxfdxffffnz
3-11 x: kzsvmhcxnwj
6-7 x: lxxxxxxcm
1-8 n: nnnnnnnrn
2-5 r: rtrrnr
2-4 n: csvhrvhlp
7-8 b: lbbpdbkb
2-8 t: ztcrbvmst
3-4 r: rwrr
7-15 b: tbtrrbbpwsrvklqb
9-13 d: dcfsgddmdsjgg
2-7 d: mvdzscd
6-8 d: jrjjdndq
1-3 m: mhmvhtmmlbztvmsvmtmb
10-12 c: ctwjbpkchccmbqw
2-3 z: jvzwcrbgqbhvzbf
2-7 g: qbwsdbg
4-7 s: jsxpbmsmkhktfdq
11-13 r: rrrrrrrrrrhrqr
9-14 d: zddcdgddddxddntddm
1-15 x: jgrxxxxfxkgbmsxzx
2-17 p: kcppppkppppppppwm
12-19 k: kkkkkkkkkkkmkkkkkkkk
1-4 x: nzpxg
5-12 p: xcbppqnppqgtrm
11-14 h: dlhzhhhsbllcwhh
13-14 q: qqqqqqqqqqqqqcq
11-16 t: ttgnswrltltttjtj
14-15 t: ttttvtttftttttjtc
3-5 s: xssns
9-11 q: mlqqtqnjqfl
3-4 z: nzzhz
2-5 k: skwbwkwgzj
1-3 p: pppppcppppbpp
5-10 r: rrrrlrrrrrr
2-3 l: jlffrztcckl
3-5 t: ttftttttr
3-6 q: qtqtmnlqck
1-4 v: vxfvmvxwvvjbxp
1-5 z: tzzzzszvzzrmzmz
10-11 l: lllllblllcx
1-4 p: vppppp
6-12 v: zvrwvvvrvhzb
2-4 x: xxnv
1-7 w: hwwwwwgwgwwbwqw
3-7 w: wwwwwlfw
5-6 l: kkpltd
4-5 d: ddnrdk
3-6 c: cncvkt
8-9 j: vblczlfjjkj
7-15 d: ddddxdgdddddddjddd
4-7 z: vvmzdspzwptz
5-7 t: cdrtfqt
6-9 j: jjjjjdjjjjjjjj
2-5 j: ljptkvvfl
6-7 l: vhhnllgx
5-6 g: gpcxwvgpvvgg
5-12 q: plzqqnqzrhqgljj
8-13 k: zkckdknkxkgkvmmkd
4-10 s: jkvstssfcsrckjnzzbsl
9-11 n: nlknnnnggnvnnnnn
8-9 s: ssssrsgstk
16-18 r: rrrrrrrrrrtrrrrbrrrr
4-5 f: qxrzfcgfqfp
2-10 p: pphtppppppplwpsp
2-5 q: qqqqsq
6-15 j: xjkxkjxxkjznjjj
9-13 f: fvfvjlfmltfgf
3-6 j: jnsrcj
1-7 h: vhhhhhhh
4-5 q: qrqqqf
2-3 v: mvxb
4-11 l: lllllllllldl
7-17 k: mkcxhcmbcpjckkqznh
7-9 v: vvpgvvvvs
7-11 j: jjjjjjjjjjjs
2-12 v: mlxjljvffxgv
3-4 t: hhfn
14-16 w: kwfwwqwcfcwwfmww
5-6 j: jjjjjg
11-12 n: nnnnnnrdnnmnn
8-9 b: dsbbbfbbbb
3-4 j: jjcjjj
1-3 r: wrnr
10-11 p: pppppppppqppp
12-13 v: vvvvvvvvvwvvvv
7-9 v: vvvqvvxvdvxv
9-14 r: mmrrrrnrrxrrrwrrrrrr
5-6 k: kkkkbkkr
13-17 v: dbvgrchdpnzvxrdfv
4-9 c: ccjbccqcpcclcc
6-8 m: mbjmmxnb
2-6 h: hhdhnvcc
9-16 t: tttttttttttttttgt
12-16 n: nnnnnnnnnnnnnnnwn
3-14 z: zzdzzzzzzzzzzzz
3-8 k: pmktwckzn
9-13 q: gqqqqqqqrqqqqq
3-6 l: lllllddll
7-8 x: slxxzplxsxkcxlxxx
2-5 v: vwvvd
6-7 n: xxnnnmnnn
2-4 z: zczz
2-12 p: pppppppppppvp
2-4 h: bqwhv
5-7 t: btzttjg
4-9 c: sxcskxxbcv
1-6 c: cccccpc
9-13 l: bcsllbvbjhrflt
5-9 c: zprfctdnt
1-5 z: zzzzz
4-8 h: bpshnhxhrbk
4-7 l: bqclvxf
5-6 m: mmmmmgwcmgjj
13-18 m: mmmnmmmmmmmmpmtmmgm
1-5 w: cwwgwwwwwww
14-16 h: hhhhhhhhhhhhhqhhh
6-7 v: bvvjvvbvvv
5-13 b: pbcbbqmbcsfblc
17-18 j: jjjwjsrjjmkjjqjjjj
4-6 t: ntttpt
6-7 v: mvvnvvc
11-12 v: vclgnzbvtvvjvs
8-13 r: rlrzkjkrrxmdvzgt
5-7 n: nnnnnnsnnnnn
3-6 q: qpkjpq
2-7 v: hvgnjfrkvx
6-10 g: xgmrggggpbggfqgdpm
9-10 s: ssssssswfszsdssszss
5-6 p: pppjppwpp
2-5 d: ddddddd
9-13 p: ppjhpbppxpxxt
10-15 t: cgtcnlltzdkbcjtvxs
8-11 m: dkmmvtdmkbhmk
3-4 z: rzzqzw
4-8 z: zcxzswbzzqzxwkzz
3-4 s: jsts
2-7 b: bsbbbbbbbbbbb
11-15 l: jjkslsltvfbqshl
3-14 c: cqtxcgmcgvgfcccmg
1-8 f: fbfwffhfbxffhlx
4-11 r: drrmrrrzcfrj
5-6 p: pwpvjp
11-14 d: pnrddqwdlpdbddwg
9-10 r: rrrwrrrznrrgqsr
3-12 v: vsvvbvvkvvpdrvvv
2-5 t: mtfqjrjlthk
13-17 r: rrrrrrrrrrrrrrrrtr
7-8 n: nnnnnnhnn
3-4 r: wrpr
1-14 p: ppppppppppppppppp
8-9 m: vzkbzwnmwfqmmmmcmmnd
11-14 p: pppnpvpwppvpppppppp
17-19 h: lzhxlhhchxhbxhwvhsx
10-11 n: nnnnznnnnlp
3-12 f: kwflsfqflxpzbgxzdhzv
8-10 x: xxvxxxxvxsxxlxxxx
1-2 c: dclflczlj
4-9 w: wwwtwwwwwww
2-8 t: pfvtlbtxt
4-9 f: pnfkffkfnh
8-10 v: vjvvvvvvvvvvvv
3-13 s: mfshscgmmrvzw
6-10 g: gzggggpggkggzggggg
13-14 n: fnnnnnnnnnwnrnnn
4-14 k: lbvkwrkjkxjskg
9-11 q: qqqqqqqqsqgq
17-18 q: qqqqqqqqqqqqqqqqqd
6-9 s: spsssgsrrssss
8-14 m: qmmqjmmmmtpmnzgmm
1-7 m: bmsrmmmmmmm
14-17 k: kskdbkkkkdkkkktkqkkk
4-5 c: ccccgfc
2-5 k: kkkkzk
2-11 q: qqwqlnqqqhtdvxqrc
4-6 m: fdxkmmd
7-10 j: mjgftcmjmjj
17-18 m: mmmmmmmmmmmmmmmmnm
2-4 v: svvv
6-8 x: jxxhrxlp
4-10 s: dsvdbsssmscs
18-19 k: zwdgknqvqkgdhdhktkmr
2-7 h: jdflgfh
6-8 z: zmpzzzzzzzzgz
3-6 m: mmrmmm
4-8 w: wwtwktws
4-10 k: dkjkqkkzvk
3-7 b: bbbbbbfbbb
4-12 z: zzzzzzzzzzzzz
5-9 z: nmqdzzkzzzbj
4-11 z: fzzgzzzzzztzz
1-7 w: whwwwzrw
5-6 t: tjtttv
9-11 v: vzvhvxvvnvwvvv
2-4 t: pkjtpp
14-15 n: njpwjnsbnnnnngnnvnnn
5-15 k: qtmvkkdjkslkqvk
2-4 s: skszs
2-3 g: zggjhgxzn
16-17 p: ppppmppppppppppnppp
4-10 z: zzzzzzzzzzz
17-18 s: sssgsssskssssssssbs
5-8 m: mmmmmmmbm
1-5 l: llllmlql
3-13 z: bmdwpgvzfdlgzgl
1-4 p: pjplgjr
1-9 v: vvvzvrvvk
6-18 w: whwpwwflbcwwvwwwwst
19-20 n: nnsnnjnnnnnnnnnnnnkx
9-10 m: rlmxrnqrmkmmwmmmmm
15-17 s: lvssssslssfsssksfb
3-4 q: qqqpq
7-13 h: hhhhhhhhhhhhdhhhhhhh
2-6 h: dvkfhhmk
4-6 s: nczssv
10-12 p: pppppppppppdpprp
16-18 s: sssssssssssssssgsg
7-12 h: hhhhhhvhhhhhh
4-12 f: ffftfffffffwff
4-7 s: csqcpssbgvvmwdb
6-10 p: ppppvppppdppd
6-8 h: hxjhthhgzh
3-10 f: fffffffffsf
4-11 g: trggxlrnqrgh
2-15 w: wjxwtvkwwpgwwww
1-4 v: zjxv
7-10 f: fffffflqff
4-6 g: mgwgpbg
1-10 z: vvzzzzzvzz
6-7 f: ffffffnf
11-15 w: wxzwwqdnnwwxjlwplcl
10-11 s: hsslzjgsssvxsshnsc
4-12 n: tlxdnpznjbknt
7-8 k: mkhcvjxk
10-12 j: jjjjjjjjjjnm
2-7 c: fckckdpcksjckwcc
3-8 s: sssdxssw
12-14 t: ttttttttqttxttttpttt
6-7 g: gggggggg
5-10 f: fqffzffffffffgf
6-7 t: ztqhpbt
5-12 w: swwfwwwwwpwbwj
2-4 w: qmww
5-8 v: vvjnvvpv
7-8 p: bcbtnppbxnnwpr
4-12 z: zzkzdxntzlfbkkzzzw
8-9 s: sssssssss
15-18 h: jhvhhhcxwhhhhmhhhj
6-10 w: bwwwwwwwwwwwww
5-9 l: mtqlhlwlh
5-7 l: ljllnllblpl
15-17 h: hpgdkhsjwfnsjmhqxf
3-4 g: gggxgggg
1-2 q: qdqm
6-10 n: hnnnqknnnnnlnnnnp
13-17 q: djstfsmmqlshqqbqnf
6-7 z: qzlzxzw
7-12 g: qhghvbwdcvkgjl
7-15 z: zzzzzznzzzzzzzzzzzzh
3-6 w: zchpwvw
3-4 c: wmbjp
6-9 k: tckbvkkxkkqk
11-13 p: pcppppppppppppbp
5-7 r: rrrrsrxrr
6-10 c: ccccczcccccccccc
7-8 j: jjpjjplj
5-7 m: mjmmmjrmfmmmmmmmm
1-7 t: ttttttnttvpt
6-12 t: tttfwtttttttttttttt
7-17 x: hxwgrqqlxmrxrcwsx
3-8 g: vjcgqrjhlq
13-18 n: nnnfnnngnnnnjnnnhln
13-15 f: ffffffffffffrbff
13-15 x: xmswzjhtthggslslgx
12-13 g: ggggggggggggggg
3-9 f: cxfskjcbmhmmcpwn
5-7 h: jxzbhbh
2-3 m: mhmlmq
1-3 m: rmmmgmzvcghdtgmsmnm
14-15 s: wzssphxtsskpssr
8-14 p: kppjppgfpprftj
2-7 r: prnmlrrbm
2-5 v: vvvvtvv
1-5 n: nnnnzn
2-5 t: xtlnfwhgvltx
3-4 v: gvtv
2-8 k: kvkstkfz
2-6 j: jdjjjnjjjjzjjjj
3-4 s: sshwsssss
2-10 w: mnhkdtwdzwvsq
6-8 b: bbbbkxbbtbbkbt
14-19 h: hhhhhhhhhhhhhhhhhhhh
6-10 d: ddddddddddddddd
10-13 t: ttttttttthttjttt
4-5 c: ctscw
8-9 b: bbbvbbgmb
10-12 s: sxssshsssswsscsx
3-7 r: rdhrrkrkrrrrcrhrrr
8-10 j: wjsslzjjntjjwjs
1-4 q: gqqw
4-6 t: tjlhvrt
2-10 s: ssssssnssssssssx
7-8 x: xxxxxxfw
6-13 r: sxtcgrffrpdprnklbxbw
1-3 p: ppbppppppp
2-3 b: jbfr
1-7 m: cmmmmqm
4-5 t: tttzt
7-9 s: zwbbbssvl
10-13 w: wwwwwwwwwwwwdw
13-14 n: nnnnnnnnnnnnnmkn
5-11 q: jpbzqwqbwttgzn
4-5 k: kkkwkkk
10-17 w: sgtklkflsrfqxfwhjm
6-12 w: wwjqwwlmphwkwwwwwjw
2-13 p: ppppppppppppzp
2-16 h: tslcwztxxtchgqlxsbx
2-9 p: slptvtljpxdkf
10-12 z: tnzzghzzgzfn
3-18 f: ffxfffffffffffffff
1-2 p: prdpdghkckdgpl
6-8 x: fxxnbwrx
7-9 z: zmzkzdpgjzzz
7-14 p: pppppppppppppppb
7-10 l: xltlzllllljzxlll
18-20 n: nnnnnnnqnnnnnnnnnmnb
15-18 p: pxmqxpmqwfntrpppmf
1-15 v: kgmvwvrvmcvtrvvwv
2-8 g: gxggggggg
4-5 f: clfjfqmpffjfff
3-5 r: rpjkf
2-9 h: hhhhhshhrhh
2-5 z: zxzzz
5-11 k: kkkkkkkkkkkk
8-9 n: nnddcfntnrgnnrnnc
1-11 f: dfffffffffff
2-4 x: dzphvg
4-5 w: mnzlr
2-6 f: jhrkfmg
2-17 z: czzvvzzczznzhwzbzz
2-5 r: xrjrg
2-3 g: gggg
7-9 s: ssssssbsssss
17-19 k: kcwktkxkkbkqnwkkkkdz
1-16 f: zmxdffmfgffxrffffqf
7-8 q: qtmrkbqjq
8-9 q: qqqqqqqqx
10-18 n: nnnnnnnnnznnnnnnnnnn
16-18 x: xwxxxxxxxxxxxxxxxrxx
15-18 t: tttttftptttttttcttt
10-11 h: hfxnlbsqxphtmstbhdn
7-13 z: vdzdzmzxvfzzz
2-5 n: nnpqgnnqnb
12-16 v: pvjvvnbqzjnvvvvpjv
4-5 d: ddddk
4-8 l: lxvhlbclhgd
3-12 v: vvkvvvvvvvvvvvvvvvvv
17-18 j: jjjjjjjjjjjjjjjjdj
6-7 b: ckbdbcsbb
9-11 q: qrhxpcjjqbqt
8-14 h: hhhhhhhhhhhhklhhhhn
2-3 b: bzbjb
2-15 w: nnmdgzhsvhpvswltvt
1-5 l: lbclz
15-17 d: wlddgdxsdcdfdcgdd
18-20 q: dqsldgqqfqwsstqlmqtz
1-6 q: qqqqqdq
2-6 j: jpjjjjjj
13-15 p: ztjlhtnsgphgxccpfsp
6-13 m: ghvvmrglmmmcm
3-6 b: nbbrmrfdlbs
1-3 j: fwhjsr
7-10 p: gcppcppzpppp
4-12 r: rrrrrrrrrrrrrr
16-20 d: djdddvdsddddlmddddpm
14-19 x: xzxjxxxxxxxxxxxxxxj
11-16 w: kwclzxjjwxlwkcnwkwv
3-11 b: zhhxsgqxqbbg
10-11 q: trbhqqzhdqw
9-13 l: vcvlvqlwrlfvll
7-9 x: xxxxxxxxgx
5-6 n: nnnngnn
2-5 p: pqpppppppqpxp
4-17 z: zxrmzwwxwhqxxmqrv
5-9 v: vvvvvvvvrvvvj
6-7 x: qkhbxxkxs
3-4 d: fcmd
5-9 f: nsnlxstff
6-9 x: hrtzmhrxxbmcc
3-7 w: wwwwwwsww
5-8 g: ngkdxggg
8-13 r: rrrrphrrrrrrrrrrdrt
2-6 f: rckzvzfrnp
4-6 k: bfrpttcfbwmvhgn
7-9 w: wwwwwwswww
13-15 n: nnnnnnnnnnnnnnn
4-8 j: jjjjjjjwjjj
9-11 h: hhhhhhrhhhhhh
4-7 h: thmhwrhss
1-3 d: ddddddddddddd
10-11 c: ckrcxwcdpqc
2-4 g: kgghg
3-12 s: ssssvwssssgqs
2-7 s: sssssszs
2-10 v: wvpbjqxvzsdpgmq
12-15 n: nnnnnnbnqvrkfnn
3-5 w: wlvdw
11-14 t: pfrbxgcrwndttj
6-7 w: qnnwwpfwwhw
7-10 n: nnnvnnhnnx
3-12 c: mmfcwvxqwpcclwlxfx
2-3 p: lgpxpppp
17-19 k: rfxvmnmfzrnktfpckpr
2-9 k: kkkknkkkkkkk
15-16 t: ttjmtttmttttttwt
9-10 r: rrrrrrrrmrrrr
3-4 p: jppppxf
7-8 k: nkqbvkkt
6-8 d: dddddrdddd
6-7 q: czbqdgnc
3-5 p: rxpppsx
4-6 t: thvtwv
2-13 d: dmdddddddddddd
16-18 n: nnnnnnnnnnnnnnnnnnn
11-12 s: ssfsdsmssswssh
3-5 v: kxnvvvmvrvdvvssvvv
5-8 x: nxxxxbxxxzx
3-5 t: ctttftt
5-7 s: hssvsgj
5-8 r: rrrrrrrcrx
1-13 v: vvvvvvvvvvvvpvvvvvv
5-9 h: gxlrhsgswhchfxbwjd
2-4 w: wgwb
6-12 v: pmxnjtfsvvxvv
1-4 n: vnntn
2-3 w: wwww
3-7 f: xmfbmnvnfkkmsd
10-12 x: xxxxxxjgxxxxx
2-3 l: cllvpbtmgzmrfmq
2-4 l: llrlllnlxll
5-10 h: hdhhhzhvtchhh
8-10 q: lhqmdwcfhqngq
1-5 t: twtfvcmktthtjltqvpwc
6-8 s: sxsghtbs
3-4 m: mmmmmmmmmmmmmmmm
16-17 l: rjdpxhtblvllgvwhl
5-13 s: brhsssnfcndsh
7-13 v: swkfswvmkvjbnsgvwp
1-3 k: wlfpzk
2-4 t: tpttt
2-9 t: cntttttcgtttt
5-6 r: rrrrbh
10-12 j: jjjjjjjjjzjjdj
'
]

{ #category : #data }
AdventOfCode2020Tests >> dataForDay03 [
	^ '.........#..##.##..............
#...#.#..#.....................
.#...#..#...................#..
........##..#...#..............
.#.#.....#..#..##......#.......
....#..#...#..##........#..##..
...#....##........#.......#.#..
....#................#...###..#
...#...#.#..#....#.......####.#
.....#...#..........#...#..#.#.
....#..#............#.#.#.#..#.
..#....#.###..#............#...
.....#.............#.#.........
.#.##............##.........#..
...##...#..#....#.##..#.....#..
..............#.#.........#.##.
...........#.....##....##......
.......#............#...#......
............#.#....#....#..#..#
....#................####......
...#.........................##
..........#........#.#.........
....#.#....#...........#......#
..#.#..##......##..##..#..#.#..
...#.....##......#.#.#.........
.........#.#....#...#.#.#......
.......#.......###.#.......#...
..#............##..#.......#...
...#....#......#...#...#...#...
......#..#.#.....##......#.....
...........##...##...#....#.##.
#.##..#.....##..#.#............
.#.#.....##......#.##........#.
..#...#...#...#..........#...##
...##.........................#
.....#......#.....##....#.....#
..#........#...................
#......#..#.#..#..#.#..#...#...
...............#..........#....
.....#...........#......#....#.
........#..#...............#...
.........#...#.......#.#..#...#
..#..#......#.##..........#....
.#...#....#.....#.............#
.##.....#.........#......#..#..
........#..##.......#......#...
.......#.....###......#..#.....
.......#.#.......#.............
...#................##.#.......
..##..#...#.#...#.#..#.#.#.##..
.......#.#............#...#....
#...#.....#......#..........##.
.#.......#......#.......#.#.#..
.#.##.#.#...........#..........
.......#.....#....#.#.##......#
.###..#...#.............##.....
......#......#.................
##...#.#...##...#.#.....#....#.
#.............#....##...#....#.
#.#...#....#........#.###..##..
......#.........#......#.#.#.#.
..#.#.#.....#........#..#...#..
#.##....#.#......#...........#.
.#.#.####.........#..#.##....##
......##...............#......#
.......#.........#........#.#..
....#....#..#.##.........#..#..
.#..........#.##....#.#..#.....
#..#.#............#..#....#.#.#
..................#..#.........
##..##.#....#.................#
..................#........#..#
.....#.........#.......##......
.....................#.#..#...#
.....#.........#..........#.#..
...#.#..#..#.#.#.......#.......
.....#.....#.#.........#.....##
.............##....#....##.#...
.#......#........##..#...###...
........#.......##.##.#......#.
..#....................#.##..#.
......#.......#..#....##.#.....
...#....#.......##...#.......#.
.#.#..#.#..........##..........
....#.......##...........#.....
###....#.......#..#...#.....##.
...#......#.........#..#.#..#.#
#.........#..##.#..............
.#.....#..##.#..#..###.....##.#
..........#..#....##.......#...
.#..#.#...#...##.#..#.##.#.....
#....#...#........#......##....
..#.####....#.#........#....#..
#......#............#.#........
...#..#.......##...........#...
.........#..#.#..#.###.#...#..#
..#....##.......#.............#
............#..#......#........
........#......#..............#
..#.#.#...........#............
...........#......##.#.#.......
.#..........#...........#..#...
.....#...#..#.........##...#...
.......#....##....#.#.........#
..#.#......#.......#...##.#....
.....#..........#........#.....
#.......#.......#............#.
..##.#.....#.##.#.#.#..#.......
..#...#.......#.###............
.#...#..#....#...#...#..#....##
.....#.....#...................
.......................#......#
......#...##.........#...#..#..
.....#..#.....#..............#.
.#.##..#..#....................
....#..#...#....#.............#
..###..#...#......#.....#......
..#......###....#.....#.....###
...#.##..#...#.....#........#..
.#.#...........##....#...#.##..
.......#...##......#..#..#.....
#.............#..#...##.#..#..#
..........#......#.......#.....
...............#.#.#....#...#..
#.......#.#..#.....#........#..
.#.#.#.......#..#.........##...
......#.....#.#....#...........
..#.....##.#........##.#......#
...###...#..#.........#........
....#...................#..#...
.##........#...................
....#..#...........#.#.........
.....#.......#...#....#.#......
.........#...#.......#.#...#...
.......#.#..#....#....#.......#
..#.............#..............
.#...#..#.#.#..#............#..
...#.##.##..#..#...........##..
...........#...#..#.#........#.
....#...#.....#...#.#....#...#.
.......#.#...##..#.............
.......................#....#..
..#..#.....#...........#....#..
.#..#...#.##........##....#....
#.....##.#.#.......#.....#...#.
.#....#.......................#
#..##..###...#.........#.......
..##...#...#..........#....#...
......#..##......##.#.........#
................#........#..#..
.....#.#..#.....#.......#..#...
..#..#.....#.......#..#..#...#.
.#....#...#...#......##.....#..
....#........#...#......##....#
..#..........##......#......#..
#.#.....#.....#.......#........
...#...#......#....##.#..#...##
...#....#...#.#...........##...
#....##...#...#....#...........
...#.#..#...#..............##..
#..#..........##.#.#.....#.....
..#...#.........#.#..........#.
....#.....#..........#.........
........................#......
.#.....#.#...###...#....#......
....##....#....#..#.##........#
..#........#.........#.......#.
.....#.#......#...#...#........
........#..#.....#....###....#.
...........#..#.#....#.#....##.
.......#.....##.#............#.
...............#........##.##..
.............#...##......#...#.
#...##.#.......#......###.....#
..........#...#........#..#....
....#....................#...#.
.#......#...#.......#....#.#...
....#.......................#..
#...#...#...#.##....##.........
..........#.#...##.#...#.......
..#...............#....#..#...#
#..#..#...#..#.........#...#...
.....#..#..........#.##.#..##..
........#......##.....#........
.#....#.#.........#...#..#.#...
....#..............##..........
#...............#..............
..###.........#....##.........#
.........#.#....##........#...#
....#.#..#......#...#..........
...#.#.....#....#..#....#.#..#.
............#..#.....#...##....
...........#....#.#.#...#......
#...............#....###.......
.........#.....##.#..#..#......
...#...##...###...............#
.#......#.#.#.................#
.........##..#............#....
..#..#.....#.....#.#...........
.#......##............#.#....#.
.#.##..##.##..#.........#.....#
...##.##......##.##......#.....
##.....#.#...#...#...#..#......
....................#......#...
.....#.................#...###.
...........#..#.........#.#....
...#........#..#........#....#.
#................#......###...#
.............##.#.....#.#......
...#...#.##..#........##.......
#..#.##...#....#.#.............
.#.........#.#..#...........#..
....#...#.....#.#..........#...
.#.#....###.......##.....#.##..
.##....##......#......#.#....#.
..#...#.#........#...#..##.....
..............###..........##..
#....#..##.....#.....#.....#...
...#...#....................#..
.#....#.#.....#.#..#..##.......
#...##..###......#.............
..........#.#....##.#........##
..#..#.....#...#....#.#.#......
#.....#........#..##.#.........
....#.....#..........##......#.
......#..#.....#........#.....#
.....#..#....#...........#.##..
.#....................#....#..#
........#..#...........#.......
#....#.#.......#........#.#..#.
........#.....#...#............
..#........#........#....#...#.
.....##.......#..#..........#..
......#.#......###...#....##..#
.#..#.............#.#..........
#.....##.#.#.#.#.#.....#.....#.
.#..#.....#.......#.#.....#....
###....##...#.#...#..#......###
.#................#.....#.##...
....##....#.#........###.#.#...
#.#....#........#.....#.......#
..........#..........#.##...#..
....#....#..##......#..#.......
.....#..........#.##...........
##......#.#......#.##..........
##..........##.......##........
..#.....#....#.##..#..#..#.....
......###...#...........#...###
#..#.............##............
...#.###.....#..#.........#.#..
......#...............#...#.#..
.....#...##.#...#.....#.#..#...
..#..#.#....#.#................
...............##.....#........
......#.#.....#...#.........#..
........#..#...#.#...#......#..
#...........#.......#...##...#.
........#.#...#..##..#.#...#...
..#....#...#......#..........##
..#..............##...##.#.....
...#....#..#....##.........#.#.
.#.#....#..........#.......#...
...##....#.#....#....#.#...#...
..............#..##........#..#
..........#.#...##......#..#.#.
#...##..#......................
.......#........##.#.#.#.......
.........##..#.#.......####....
..#.............#..#........##.
##..#..#...#....#.....#...#..#.
..#.#...#.#.....#..............
..#....#....#..##...#.#........
##.....#..#...#................
#....#.....................#...
..............###.....#.#.#....
..#......##.#....#.#...##......
#...#.#......#...#.#......#....
....#...................##.#...
.........##......#.....#.####..
##..#........#.....#......##..#
...#..#...#...#.............#..
#..#..#.#......###...#.........
.......#.#..#........#....##..#
............#..##.....#.#.#....
#..#.....#.....#....##........#
......#..........##............
.....#...#...........#.........
...........#....#...#....#.#...
....#.........##.##.......#....
......#....#...........#.##...#
.##.#.#..##...#.....##.#...#...
.......#.#....#...#...#....#...
.#...##.#.#.....#..#....#......
.#....###..#.......#......#...#
..#.#.........#.........#.....#
.......#.#.##..#.#.......##..#.
.##............#.........#....#
.#...##.###..#........##.#..#..
..#........#.#.....##..##.#....
...........#...........#.....#.
.#...######..##...#.....#......
.#.##.#.......#......#......#..
.#.....#.....#........#........
...#..#...#.##...#...........#.
.......#.....#.......#.........
............#...###...........#
...#.......#.......##....#..#..
##.......#....#....####........
.......#.#......#..........#..#
#.....##..#..#.....#....#...#..
#............#........##.......
.#.#...#.............#..##.....
.#....#..#.#......#.##.......##
...................##...##..###
..#.....#...#................#.
..#...#....#...#.#.#...#.....#.
.....#............#....#...#..#
.#.....#....#..#......#.#.....#
............#.#.....####.##....
....#......###....#...#....#...
#.....#..#.....#..#...#.......#
..#.#...#....#....##..#...##...
.##..#..#..##....##...#........
'
]

{ #category : #data }
AdventOfCode2020Tests >> dataForDay04 [
	^ 'byr:2010 pid:#1bb4d8 eyr:2021 hgt:186cm iyr:2020 ecl:grt

pid:937877382 eyr:2029
ecl:amb hgt:187cm iyr:2019
byr:1933 hcl:#888785

ecl:hzl
eyr:2020
hcl:#18171d
iyr:2019 hgt:183cm
byr:1935

hcl:#7d3b0c hgt:183cm cid:135
byr:1992 eyr:2024 iyr:2013 pid:138000309
ecl:oth

ecl:hzl
hgt:176cm pid:346059944 byr:1929 cid:150 eyr:1924 hcl:#fffffd iyr:2016

iyr:2011
cid:99 ecl:amb
eyr:2030 hcl:#18171d
hgt:165cm pid:897123249 byr:1948

hcl:#cfa07d pid:827609097 ecl:gry iyr:2017 byr:1963
eyr:2029 hgt:72in

hcl:#6b5442 eyr:2028 iyr:2016 ecl:hzl
hgt:152cm
pid:432183209 byr:1984

hgt:169cm hcl:#888785 ecl:hzl pid:626107466 byr:1929 iyr:2013 cid:217
eyr:2026

hcl:#bdb95d byr:1935 eyr:2023 ecl:blu iyr:2011 cid:90 hgt:64cm
pid:155167914

iyr:2017
byr:1943 cid:56
hcl:#888785 hgt:193cm pid:621305634
ecl:amb
eyr:2024

ecl:gry
hcl:#a97842 pid:936999610 cid:169 byr:1991 eyr:2029 hgt:175cm iyr:2017

hcl:#866857 ecl:gry
byr:1975 hgt:71in
pid:180628540 eyr:2020
iyr:2017

hcl:#cfa07d hgt:153cm byr:1962 cid:325
iyr:2018 eyr:2020
ecl:amb pid:579364506

hcl:#6b5442 iyr:2010 ecl:amb byr:2001
eyr:2020 pid:406219444
hgt:173cm

pid:#430c70
ecl:gry iyr:2018 hcl:#866857 eyr:2021 cid:97 byr:1997
hgt:75cm

iyr:2023 pid:#518780
eyr:2034
ecl:zzz
hgt:72cm
hcl:z byr:2010

pid:1961614335 hcl:#c0946f hgt:157 ecl:grn eyr:2031 byr:1972 iyr:1992

cid:142
eyr:2022 ecl:amb
hgt:68in
hcl:#6b5442 byr:1927 pid:112372155 iyr:2012

byr:1972
hgt:169cm
hcl:#888785
cid:75 iyr:2015 eyr:2021 ecl:oth
pid:7889059161

ecl:brn
iyr:2020
eyr:2026 hgt:151cm byr:1961 pid:468038868 hcl:#18171d

ecl:blu
hcl:#b6652a
byr:1959
hgt:151cm cid:109 pid:708689901
eyr:2026 iyr:2012

ecl:grt byr:2024 iyr:1995 pid:225263933 hcl:z
eyr:2040 hgt:127 cid:162

pid:683129831 cid:144
hcl:#a97842 hgt:155cm eyr:2030 byr:1962
iyr:2015
ecl:oth

byr:2009 hcl:#866857 cid:329 iyr:1955
eyr:1994 pid:085929595

byr:1940
pid:936748944 hgt:160cm eyr:2024 iyr:2013 cid:205
ecl:grn hcl:#c0946f

hgt:193in cid:161 iyr:1984
pid:#f82e35
byr:2018
hcl:b1a551 eyr:2014 ecl:#4d2d5b

byr:1978
iyr:2011 hgt:172cm hcl:#efcc98 ecl:brn pid:759624394 eyr:2020

eyr:2020 pid:622444743
hcl:#a97842
ecl:gry iyr:2014 hgt:157cm byr:1980

hgt:181cm eyr:2020
iyr:2014
hcl:#602927 ecl:brn byr:1934

hgt:188cm
ecl:blu eyr:2029 pid:757878469 hcl:#b6652a iyr:2017

byr:1995 ecl:blu hcl:#341e13 eyr:2027 iyr:2020 pid:283341241
hgt:174cm

byr:1960 iyr:2012 hcl:dc007d eyr:2011 hgt:166cm
pid:9889788504
ecl:#a9b3a1

ecl:hzl hgt:70in pid:620966688 iyr:1998 hcl:z
eyr:2022

hgt:187cm cid:190 pid:818634983 byr:1925 ecl:gry hcl:#ceb3a1
eyr:2021 iyr:2015

hcl:#c0946f iyr:2017
byr:1953 eyr:2030 hgt:67in pid:085876735 ecl:hzl

pid:205284134
hcl:#cfa07d byr:1987 hgt:167cm
eyr:2022 ecl:oth iyr:2020

iyr:2018
hgt:180cm pid:232535961 eyr:2027 byr:1999
hcl:#18171d ecl:oth

cid:342 hgt:171cm ecl:blu byr:1920 hcl:#18171d eyr:2023 iyr:2012
pid:353601791

byr:1956
ecl:brn pid:141896408 iyr:2012 cid:116 eyr:2028 hgt:164cm
hcl:#866857

hcl:#fffffd ecl:oth eyr:2030 hgt:67in pid:855777018 byr:1975
iyr:2012

ecl:blu pid:45257034 hcl:#c5447e iyr:1928 cid:212 byr:1974

pid:080116868 cid:97 eyr:2021 iyr:2020 ecl:grn byr:1987 hgt:62in hcl:#efcc98

eyr:2027 hcl:#efcc98 iyr:2020 ecl:amb cid:111
pid:143966954
hgt:165cm

iyr:2015 byr:1941 pid:798564127
hgt:183cm ecl:oth eyr:2020

byr:1999
iyr:2017 hcl:#ceb3a1
pid:640883740 hgt:164cm
cid:105 ecl:hzl
eyr:2022

iyr:2014 eyr:2023
ecl:grn hcl:#ceb3a1
hgt:188cm byr:1981 pid:185076942 cid:342

hgt:150cm
iyr:2013 eyr:2035 cid:184 hcl:#341e13 pid:#e2dd63 byr:2014 ecl:brn

eyr:2024 iyr:2015 ecl:brn hgt:76in
hcl:#866857 byr:1958
pid:886486245

ecl:amb cid:113 byr:1931 pid:087380735
iyr:2010
eyr:2028
hgt:161cm

byr:1926 eyr:2024 iyr:2012 pid:036335738 hcl:#c0946f hgt:153cm ecl:brn

hcl:bf952a
hgt:169in
eyr:1925 pid:166cm iyr:2028 ecl:lzr byr:1938

hgt:154cm hcl:#733820 ecl:oth iyr:2016
byr:1925
eyr:2020 pid:590365390

eyr:2029 hgt:166cm pid:670283165
hcl:#ceb3a1 iyr:2018
byr:1955
ecl:gry

hgt:181cm
iyr:2016 hcl:#866857 byr:1933
eyr:2028 ecl:blu

hgt:184cm
cid:138 hcl:#623a2f
pid:081880232
byr:1929 ecl:hzl eyr:2030
iyr:2015

pid:825698872
eyr:2026 hgt:181cm iyr:2015 hcl:#866857 byr:1950 ecl:gry

eyr:2022 byr:2002 iyr:2013 hcl:#fffffd ecl:hzl pid:687380398
hgt:173cm

byr:2016 ecl:zzz pid:0514910377 hcl:ebe8b2 eyr:2025
iyr:2011 hgt:183cm

ecl:amb hgt:67in
pid:602547016 byr:1985
eyr:2021
iyr:2014

iyr:2014 eyr:2020 ecl:grn pid:642261584
byr:1970 hgt:190cm cid:278 hcl:#7d3b0c

eyr:2035 cid:226 hcl:64ac73
byr:2007
pid:176cm ecl:#927fbf iyr:2006

iyr:2019 eyr:2026 ecl:brn hgt:162cm
cid:108
hcl:#ceb3a1 pid:774441166 byr:1951

hgt:166cm eyr:2024 hcl:#b6652a byr:1934 pid:260873380 iyr:2016

hcl:z
iyr:2015 ecl:blu
eyr:2040 byr:1927 pid:431855667
hgt:173cm
cid:209

eyr:2034 cid:139
ecl:#cb7564
byr:2023 hgt:172in iyr:2027 pid:2877047600

ecl:brn
cid:125 hcl:#888785
iyr:2011 pid:739399822 hgt:184cm byr:1989

hcl:#c0946f
pid:891125961
hgt:175cm
iyr:2010 eyr:2027 ecl:gry
byr:1930

hgt:164cm byr:1935 eyr:2023 pid:684366743
ecl:oth
hcl:#18171d iyr:2013

hcl:#341e13 hgt:64in byr:1959 ecl:#c53bbb iyr:2014 eyr:2029 pid:174cm

eyr:1943 ecl:#e52638
hcl:06a964 byr:1959 cid:342 iyr:2029 hgt:178in pid:150cm

byr:1966 hcl:#733820 iyr:2020
ecl:gry eyr:2021 pid:229789071

pid:363947487
ecl:blu
hcl:#623a2f
byr:1972
iyr:2017 hgt:184cm
eyr:2023

ecl:oth pid:460855562
iyr:2010 cid:148 hcl:z hgt:74cm byr:2005

eyr:2027 iyr:2017 hgt:172cm
byr:1975
ecl:amb cid:97 hcl:#c0946f pid:591950054

eyr:2022 ecl:oth hgt:185cm
hcl:#6b5442
byr:1978
iyr:2018 pid:849124937 cid:78

iyr:1927 hgt:121
eyr:2020 ecl:#c73b1a hcl:#cfa07d pid:4505701953 byr:2020
cid:235

hgt:183cm hcl:#341e13 iyr:2019 byr:1932 ecl:#144539
pid:184cm eyr:1954

iyr:2020 cid:332 byr:1930 hcl:#6b5442 hgt:168cm ecl:amb
eyr:2023 pid:332084752

ecl:blu
byr:1922 cid:135 iyr:2019 eyr:2028 pid:481801918
hcl:#efcc98 hgt:76in

ecl:grn pid:188906975 cid:153 hgt:173cm eyr:2029 iyr:2012 hcl:#733820 byr:2001

eyr:2029
byr:1948 iyr:2020
hgt:167cm ecl:brn hcl:#623a2f pid:577624152

hcl:#18171d
pid:262528276 byr:1949
iyr:2020
eyr:2023

hcl:#c0946f iyr:2016 byr:1967 ecl:brn
hgt:162cm
pid:139002508 eyr:2030

eyr:2030
hgt:72in iyr:2013 pid:542944485 cid:112
byr:1950 hcl:#a97842 ecl:amb

pid:772544664 eyr:2023 ecl:gry hgt:159cm iyr:2012
byr:1956 hcl:#602927

hgt:172in ecl:grt pid:668387651 byr:2019
iyr:1995 hcl:bc51ff eyr:1921

pid:322272953 ecl:brn hcl:#a97842 byr:1990
eyr:2021
iyr:2017
hgt:181cm

eyr:2029
iyr:2011
pid:503169142 byr:1980
hcl:#a97842 ecl:oth

pid:514042929
ecl:amb eyr:2030 hgt:154cm
iyr:2010 hcl:#623a2f
byr:1989

byr:1988 pid:156381939 iyr:2016 hgt:161cm eyr:2030 ecl:brn hcl:#7d3b0c

pid:545819361 hgt:191cm iyr:2012 byr:1982 eyr:2025 ecl:zzz
hcl:z

pid:872911892
byr:1924 iyr:1974
hcl:#602927
ecl:brn hgt:154cm
eyr:2028

hcl:#602927 hgt:188cm
byr:2007 pid:503933918 ecl:utc
eyr:2030 iyr:2020 cid:132

ecl:hzl
eyr:2020 hcl:#888785 hgt:181cm
pid:721383537
iyr:2018
byr:1983 cid:50

pid:8590606 hcl:#18171d
eyr:2039 iyr:2024
cid:161 byr:2027

hgt:160in byr:1956
cid:214 pid:187cm iyr:2027
hcl:z
eyr:2033 ecl:grn

byr:2029 pid:90562860 hcl:4fa0d1 iyr:2024
eyr:2040 cid:62 ecl:#07ae33 hgt:186in

pid:557319679 byr:1945 hgt:182cm eyr:2026 iyr:2012 hcl:#866857 ecl:hzl cid:219

eyr:2028 iyr:2022 ecl:zzz cid:273
hgt:133 pid:4084335529 byr:2011 hcl:z

pid:69196974 hcl:z iyr:2014 ecl:amb byr:1928

hgt:183in
eyr:2028 pid:771762218 byr:2003 ecl:dne hcl:70eb58 iyr:2027 cid:330

ecl:hzl pid:195721774 hcl:#602927 byr:1945 hgt:186cm
eyr:2037
iyr:2011

ecl:brn eyr:2028 hgt:171cm
byr:1980 hcl:#fffffd pid:563089389 iyr:2016

eyr:2027 iyr:2011 ecl:gry byr:1932 hcl:#18171d
pid:398526372

pid:97363921 hgt:178cm
ecl:oth eyr:2028
byr:1930 cid:345 iyr:2018 hcl:#1fb2f0

ecl:amb iyr:2012
byr:1961 pid:679312513 eyr:2026 hcl:#cfa07d
hgt:174cm

byr:1980
hcl:#80055d
cid:235
ecl:oth pid:159696517 eyr:2030
hgt:191cm
iyr:2012

iyr:2013 eyr:2027 hcl:#866857
pid:621184472 cid:137 hgt:175cm byr:2000
ecl:hzl

byr:1998 hgt:166cm
ecl:oth eyr:2025
iyr:2018
hcl:#a97842 pid:358495679

byr:1928 ecl:oth cid:122 hcl:#6b5442
hgt:189cm eyr:2020 iyr:2018

hgt:186cm
byr:2020 hcl:79d685 ecl:grt iyr:1944 pid:3659998623 eyr:2000

hgt:63in ecl:oth eyr:2029
iyr:2013 pid:942282912 hcl:#c0946f byr:1989

byr:1997 hcl:#623a2f eyr:2026 cid:149
pid:702981538
ecl:amb hgt:178cm iyr:2017

ecl:brn iyr:2015 byr:1932 pid:191192548 cid:318
hcl:#7d3b0c eyr:2020

hcl:#866857 eyr:2028 pid:341036511 cid:343 iyr:2020 hgt:173cm
byr:1973 ecl:blu

iyr:2016 pid:165707654 hgt:181cm ecl:hzl
cid:119 byr:1973 hcl:#b6652a

iyr:2014 pid:833337583 byr:1936 cid:91 hcl:#602927 ecl:amb hgt:165cm
eyr:2021

byr:1938 ecl:grn hcl:#a55daf eyr:2021 cid:199 pid:701515796
iyr:2015 hgt:71in

hcl:#a97842
ecl:blu
eyr:2030 iyr:2020
hgt:155cm byr:1927
pid:524488639

pid:385084163 eyr:2025
hcl:#866857 ecl:oth iyr:2020 hgt:177cm byr:2002

eyr:2029 hgt:177cm
cid:142 ecl:hzl hcl:#866857
iyr:2015 byr:1946 pid:459543573

pid:826977286 eyr:2030 iyr:2016 byr:1996
hcl:#efcc98
ecl:gry hgt:180cm

eyr:2029
iyr:1976 pid:872821863 ecl:gry byr:2030

hgt:191cm byr:1924 pid:918753019 ecl:blu
iyr:2019 hcl:#5d69e0 eyr:2024

ecl:lzr iyr:2020 pid:991375034 byr:1947
eyr:1923 hcl:8224f6 hgt:157

eyr:2021 byr:1946
hgt:189cm ecl:grn iyr:2010 hcl:#cfa07d pid:246923037

iyr:2016
ecl:oth hgt:155cm byr:1962 pid:924702739 eyr:2028 hcl:#7d3b0c

pid:7358100461 hgt:183cm byr:2011 hcl:#a97842
iyr:2020 eyr:1963 cid:71

ecl:hzl hcl:#c0946f
byr:1934
hgt:183cm
iyr:2018 pid:433993423 eyr:2028

hgt:183cm hcl:#cfa07d iyr:2018
byr:1975 eyr:2024

eyr:2021 ecl:amb byr:1992 hgt:164cm iyr:2020
cid:302

pid:271720491 hgt:161cm
iyr:2012 byr:1947 hcl:#6b5442 ecl:grn eyr:2024

pid:860852799 eyr:2021 byr:1980 hcl:#6b5442 iyr:2010 hgt:174cm
ecl:hzl

hcl:#623a2f eyr:2028 iyr:2016 pid:813453232 hgt:173cm cid:131
byr:1962

byr:1975
hgt:177cm
pid:290098810 cid:241
ecl:oth hcl:#a5fc9f eyr:2021 iyr:2013

byr:1947 pid:762351259 hgt:178cm ecl:amb hcl:#d07b27 iyr:2017 eyr:2028 cid:271

iyr:2012 pid:053790533 eyr:2023 ecl:grn hcl:#623a2f byr:1939 cid:70 hgt:189cm

hcl:#c0946f pid:891312170 byr:1986 iyr:2012
hgt:163cm eyr:2023 cid:150

iyr:2015
byr:1963
pid:695024197 hcl:#efcc98 ecl:brn hgt:166cm eyr:2022
cid:276

eyr:1945 hgt:150in byr:2007
ecl:utc hcl:z cid:272
pid:186cm iyr:1927

pid:956296646 iyr:2015 hgt:168cm
byr:1979 eyr:2029 ecl:gry hcl:#866857

pid:745452488 byr:1998 eyr:2025 hcl:#602927
hgt:158cm iyr:2015

eyr:2027
iyr:2017
pid:6173634679 byr:2001 ecl:hzl
hcl:babc41
hgt:76cm

ecl:grn
iyr:2019
hcl:#3881ca byr:1975 eyr:2023 hgt:162cm

hcl:#ceb3a1 hgt:169in pid:398759957
eyr:2020 byr:2016
iyr:2011 ecl:#be3622

hgt:156cm
hcl:#b6652a pid:166cm iyr:2027 byr:2003
eyr:2036 ecl:#6d4df1
cid:109

eyr:2026 pid:295161300 ecl:gry
hgt:160cm byr:1950 hcl:#746f08
iyr:2017

iyr:2010 cid:335
eyr:2024
hcl:#866857
byr:1948 hgt:166cm pid:178927953
ecl:blu

hgt:161cm cid:210 eyr:2025
byr:1920
ecl:gry iyr:2020
hcl:#7d3b0c pid:443548961

iyr:2019
pid:320015839 eyr:2029
hcl:#fffffd ecl:oth byr:1953 hgt:182cm

eyr:2038 hcl:abb3ad iyr:2015 pid:174cm hgt:167cm
ecl:hzl

byr:1982 pid:798153758
ecl:brn
hgt:161cm hcl:#341e13 eyr:2023
iyr:2014

byr:1938
pid:193cm hgt:190cm ecl:amb iyr:2019
eyr:2028 cid:270
hcl:#18171d

pid:711886098 byr:1962
eyr:2028 ecl:grn
hgt:151cm
hcl:#cfa07d
iyr:2019

eyr:2028 iyr:2011
ecl:gry
pid:550207629 hgt:183cm
hcl:#888785 byr:1920 cid:96

ecl:utc
eyr:2021
byr:1962 hgt:175cm
pid:872298092
hcl:z iyr:2017 cid:197

iyr:2010
hcl:5b88b0 byr:2021 ecl:gmt
eyr:2040 hgt:179cm pid:161cm

pid:56869473 eyr:2036 ecl:lzr
iyr:2027 hcl:z

hcl:#602927
hgt:151cm pid:780342729 ecl:oth iyr:2015

byr:2027 hcl:#fffffd
pid:5609758115 eyr:2037
iyr:2017
ecl:#6f0329 hgt:97

iyr:2025 hcl:z byr:2007 ecl:gmt
pid:#eda9ab
hgt:154in eyr:2028 cid:247

ecl:utc pid:216181141
hgt:161cm eyr:2026
hcl:#d38f20 byr:2028

ecl:grn byr:1955 hcl:#c0946f
iyr:2017 eyr:2027 pid:746303487
hgt:72in

pid:489225602
iyr:2018 ecl:gry hgt:65in byr:1982
cid:248
eyr:2025

hcl:#ceb3a1 pid:663798116 byr:1937 iyr:2010
hgt:167cm ecl:hzl

pid:329032527
hcl:#ceb3a1
iyr:2014 ecl:gry
hgt:169cm
byr:1932

hcl:#545d0c
ecl:brn iyr:2023 hgt:186cm cid:209
pid:886392748
eyr:2030 byr:1984

hgt:80 iyr:1943 hcl:#733820 byr:1937 eyr:2029 pid:625851706 cid:309

pid:73586582 hgt:156
cid:162 ecl:zzz eyr:2025
iyr:1990 byr:1940 hcl:z

iyr:2010
eyr:2023 pid:162901454
hcl:#733820 byr:1958 ecl:gry
hgt:159cm

byr:2007
hcl:#cfa07d
cid:261 pid:148538600 ecl:hzl
hgt:64cm iyr:2021
eyr:2040

iyr:1997 byr:2007 ecl:#24adc8
pid:55794137 cid:219 eyr:2037
hgt:75cm hcl:z

hcl:#efcc98 byr:1940 ecl:amb iyr:2012
pid:594237790 eyr:2029 cid:112
hgt:173cm

byr:1941 cid:70 eyr:2026 hgt:178cm hcl:#733820
ecl:brn iyr:2013 pid:425263722

eyr:2025 byr:1998 iyr:2014 ecl:amb pid:188113611 hcl:#341e13

byr:1950
iyr:2017 hgt:74in cid:238
pid:897969952
ecl:hzl eyr:2022 hcl:#0a18bb

eyr:2022
iyr:2015 ecl:grn
hgt:179cm byr:1956 hcl:#7fd789 pid:201629099

eyr:2024
pid:483257417 ecl:hzl iyr:2010 hgt:159cm
hcl:z
byr:1968

pid:916586207 ecl:amb iyr:2011 eyr:2022 hgt:191cm hcl:#602927 byr:1923

pid:175608183
hgt:190cm hcl:#fffffd iyr:2017 byr:1993
ecl:blu

eyr:2029 hgt:173cm
pid:669662258 byr:1997 iyr:2015 ecl:brn cid:153 hcl:#888785

hcl:d899cf
ecl:#876029 hgt:76cm iyr:1997 pid:40406158
eyr:2032 byr:2010

eyr:2023 ecl:hzl cid:162 hcl:#602927 iyr:2015
pid:82885029
hgt:75cm byr:1946

byr:1962 hgt:167in
ecl:brn
hcl:#c0946f iyr:2014 pid:488520708 eyr:2027 cid:271

hgt:180cm pid:358771245 eyr:2020
ecl:grn iyr:2018 hcl:#efcc98
byr:1979

cid:273 ecl:gry pid:424388351 iyr:2010 hcl:#c0946f byr:1988
hgt:166cm
eyr:2027

ecl:gry hcl:#a97842 hgt:189cm
pid:743213778 iyr:2015 byr:1959

iyr:2021 byr:2021
ecl:#a79d2e cid:89
hcl:#5fb8d7 eyr:2001 pid:#5575b3 hgt:60cm

eyr:2021
iyr:2017
cid:87 hgt:164cm pid:560394910 ecl:hzl hcl:#ceb3a1
byr:1955

iyr:2018
hcl:#27f7e6 hgt:160cm
eyr:2029 pid:033692111
ecl:amb byr:1920

hgt:160cm eyr:2028 iyr:2010 ecl:blu byr:1974 pid:858060501 hcl:#733820

byr:1961 pid:818700605 cid:93 eyr:2024
hgt:188cm hcl:#866857
ecl:gry

eyr:2029
hgt:180cm iyr:2017
ecl:hzl byr:1951 cid:158
hcl:#888785

cid:290
eyr:2027 byr:1986
ecl:blu
pid:076339632 iyr:2010
hcl:#341e13
hgt:167cm

eyr:2023 iyr:1990
hcl:#623a2f byr:2005 hgt:116

hgt:167in iyr:1944 ecl:dne eyr:2031 hcl:465775 pid:2505694463

cid:93 eyr:2024 iyr:2010
hgt:143 pid:154cm
ecl:#c6f352
hcl:#a97842 byr:1925

pid:600685520 byr:1967 hcl:#ceb3a1 iyr:2014 ecl:oth cid:226 hgt:179cm eyr:2026

hcl:#ceb3a1
pid:789956738
byr:1938 hgt:171cm cid:183 eyr:2021 iyr:2011 ecl:amb

hcl:#613f4b hgt:151cm eyr:2025
ecl:amb byr:1985 pid:493339889
iyr:2013

hcl:78cda6 pid:36823553
iyr:2021 cid:235 byr:2028 eyr:2011 hgt:113
ecl:#02ce86

pid:529274811
iyr:2012 hgt:103 ecl:blu hcl:#341e13 eyr:2023
byr:1959

hgt:166cm iyr:2014 ecl:xry cid:276 byr:2014 hcl:#7d3b0c pid:146851133

pid:359823289 hgt:181cm byr:1978 hcl:#c0946f
eyr:2022
iyr:2011 ecl:hzl

pid:029400877
eyr:2026
byr:1983 iyr:2015 hcl:#cfa07d cid:70 ecl:gry

hcl:#ceb3a1 eyr:2021 hgt:190cm
ecl:amb iyr:2017
pid:411804678 byr:1950

byr:1926 iyr:2017 ecl:blu pid:103821113 eyr:2026 hcl:#c0946f cid:71 hgt:152cm

cid:108 byr:1955
iyr:2010 eyr:2022 hgt:169cm hcl:#733820
pid:208715596 ecl:gry

pid:352807405 ecl:blu
hcl:#b1214c iyr:2012 hgt:165cm byr:1929
cid:139
eyr:2020

hcl:#cfa07d hgt:151cm byr:1987
eyr:2024
cid:140 pid:884441477

pid:#dade9c eyr:1979 hgt:191cm
byr:2026 iyr:2018 hcl:z ecl:lzr

cid:259
pid:644561358
ecl:blu hgt:164cm iyr:2013 byr:1997
eyr:2023 hcl:#108f16

ecl:oth
cid:141 hgt:66in pid:877258886 iyr:2019 byr:1949 hcl:#18171d
eyr:2027

byr:1932 cid:103 hgt:175cm pid:464473181 ecl:xry iyr:2013 hcl:51fd65

cid:175 iyr:2014 eyr:1959
ecl:#d83076 hgt:182cm pid:863972537 hcl:#efcc98 byr:1986

hgt:181cm pid:869641194 hcl:#efcc98 cid:141 ecl:gmt iyr:2017 byr:1981 eyr:2027

eyr:1938
iyr:2026 cid:278 ecl:brn byr:1936 hgt:150 pid:6902040050

eyr:2027 iyr:2014 pid:110887179
hcl:#a97842 ecl:brn cid:262 hgt:66in
byr:1954

ecl:grn
pid:498972747
eyr:2024 hcl:#341e13 iyr:2011 byr:1932 hgt:186cm

cid:59
hcl:#6b5442 iyr:2018 eyr:2028 pid:866696485
hgt:178cm ecl:gry

pid:598961001
eyr:2024 iyr:2019
byr:1963 ecl:grn
hcl:#c0946f

eyr:2024 hgt:172cm pid:295056305 ecl:blu byr:1926
iyr:2017 hcl:#341e13

byr:2001 hcl:#6b5442 hgt:164cm
pid:862982189 ecl:grn iyr:2019 eyr:2030

hgt:69cm eyr:2014 ecl:hzl iyr:2025
hcl:2812c9
cid:74 byr:1980

hcl:#888785
pid:409489862
iyr:2011 hgt:186cm ecl:gry byr:1985
eyr:2028

cid:221 pid:6849250876 hgt:169cm hcl:z
iyr:2013
byr:1950 eyr:2022

pid:189083891 byr:1983 hcl:#623a2f ecl:hzl iyr:2013 eyr:2026 hgt:66in

pid:581546673 cid:269 eyr:2030 hgt:191cm byr:1945 hcl:#18171d
iyr:2015
ecl:amb

hgt:158cm ecl:hzl
cid:234 eyr:2023
byr:1996 hcl:#7ac7ad
iyr:2020 pid:666748924

iyr:2013 ecl:grn cid:53 hgt:172cm eyr:2028 pid:406602771 hcl:#fffffd byr:1959

hgt:63cm hcl:eaaf60 byr:2026 iyr:1981
pid:#baf2cf cid:117 ecl:hzl

eyr:2035 byr:2014
iyr:2028 hcl:z ecl:#acd426
cid:261 pid:174cm hgt:182in

ecl:amb pid:#4bb0a8 eyr:2027 hgt:155cm hcl:#623a2f
byr:1956
iyr:2011

eyr:2012 cid:53 byr:2005 ecl:oth
hgt:183in iyr:1974 pid:150cm

iyr:2020 pid:833821322 ecl:blu byr:1944 hgt:169cm hcl:#623a2f eyr:2020

hgt:60in ecl:oth byr:1962 eyr:2022 cid:99
iyr:2019
pid:281039464 hcl:#733820

ecl:hzl hcl:#7d3b0c hgt:191cm pid:771871096
iyr:2012 eyr:2027
byr:2025

hgt:188in hcl:z eyr:2032 iyr:1955
byr:2027 ecl:#517bfe pid:#206bab

hcl:#733820 iyr:2010 pid:784128823
hgt:169cm cid:305
ecl:grn byr:1962

cid:50 eyr:2022
hcl:a916cf pid:407148034 iyr:1926 ecl:#fa1ba7 hgt:69
byr:2028

hgt:193cm pid:507697987 cid:275 byr:1958 eyr:2023 ecl:brn iyr:2013 hcl:#326596

eyr:2025 hgt:192cm cid:95 iyr:2011 ecl:grn byr:2002 pid:399623583 hcl:#b6652a

ecl:brn hcl:#602927 eyr:2023 pid:089068603 hgt:189cm
byr:1953 iyr:2018
cid:160

hcl:f1bf94 byr:2030
ecl:gry hgt:60in iyr:2016
pid:4816152

hgt:154cm iyr:2015 ecl:gry
eyr:2024 pid:718845487 byr:1999
hcl:#866857

cid:294
hgt:186cm eyr:2026 byr:1984
ecl:grn
hcl:#ceb3a1 pid:325370778 iyr:2010

pid:156980004 hcl:#c0946f iyr:2013 ecl:brn
hgt:181cm byr:1933 eyr:2023

hcl:#efcc98 byr:2002 hgt:158cm ecl:gmt iyr:1964 pid:195262032
eyr:2021

hcl:#602927 eyr:2027 hgt:192cm byr:1945 iyr:2018 pid:366509171 ecl:oth

pid:163cm iyr:2016 ecl:lzr hcl:#341e13 hgt:79
cid:130
eyr:2038 byr:2030

hcl:#efcc98
byr:1979
ecl:oth eyr:2020 pid:095314628
hgt:162cm iyr:2015

byr:1998 cid:157
pid:346442779 hcl:#b6652a hgt:162cm
ecl:amb
eyr:2023 iyr:2018

hcl:#d6a701 byr:1971 hgt:160cm ecl:#98c896 pid:627704105 eyr:2024 iyr:2010

byr:2021
iyr:2023
eyr:1981 hgt:68cm ecl:dne
hcl:z pid:20981493

pid:159037919 hgt:162cm
ecl:amb cid:244
byr:1971 eyr:2027
iyr:2017 hcl:#18171d

iyr:2011 pid:086826874
cid:162
hgt:189cm ecl:gry
byr:1926 hcl:#888785

eyr:2022 hgt:152cm pid:919970712 byr:1955 hcl:#733820 iyr:2018 ecl:brn

cid:111 ecl:#a1843f
byr:2015 hcl:z iyr:1956
pid:186cm eyr:2030

byr:1991
eyr:2024 pid:050818633
hcl:#888785 cid:124 hgt:176cm ecl:gry iyr:2018

byr:1963 hgt:188cm
eyr:2021 cid:255
ecl:oth
hcl:#a97842
iyr:2010 pid:030540064

byr:1921 hgt:164cm pid:748078322 hcl:#c0946f ecl:blu
eyr:2027
iyr:2020

eyr:2020 cid:214 hcl:7a942e hgt:191cm byr:1998 iyr:2012 ecl:grn pid:054135231

eyr:1927 pid:242147946 iyr:2010
hcl:ea3cb1 byr:2028
hgt:186cm ecl:dne

ecl:brn hcl:#efcc98 eyr:2021
hgt:160cm pid:333644730 byr:1999
iyr:2019

iyr:2013 byr:1921
hcl:#a97842 eyr:2027
ecl:gry hgt:157cm pid:682013109

ecl:gry hcl:#733820 byr:1945 hgt:174cm
eyr:2020 pid:505827627 iyr:2019

eyr:2021 iyr:2015 ecl:oth hgt:162cm pid:137342936 byr:1922 hcl:#888785

hcl:#efcc98
ecl:oth
hgt:151cm cid:312 byr:1983
eyr:2030 pid:289512908 iyr:2020

byr:1989 iyr:2015 pid:057335770 ecl:grn eyr:2022 hgt:167cm hcl:#602927

hgt:184cm iyr:2013 hcl:#c0946f byr:1969 eyr:2028
pid:802041641
ecl:brn

pid:155cm hcl:#b6652a cid:288 byr:2028 iyr:2028 hgt:150cm
ecl:#996e72 eyr:1960

eyr:2020
iyr:2011
pid:934576102 byr:1994
ecl:amb
hcl:#18171d

eyr:1993 byr:1995
hgt:64cm iyr:2020 pid:15714997 hcl:#b6652a ecl:blu

iyr:2014
eyr:2030 pid:866047540 cid:59 hcl:#733820 byr:1951
hgt:64in ecl:amb

iyr:2015
byr:1962
hgt:69in ecl:brn
hcl:#623a2f eyr:2023
pid:671492881

iyr:2020 ecl:oth hgt:154cm byr:1950 pid:924256973
eyr:2028
hcl:#b6652a

byr:2021
hgt:116 cid:348 iyr:1930 pid:76948864 hcl:z
eyr:2036

hgt:156cm iyr:2014
byr:1960
pid:720786216
cid:99
ecl:gry
hcl:#a97842
eyr:2028
'
]

{ #category : #data }
AdventOfCode2020Tests >> dataForDay05 [
	^ 'BFBBFFBRRL
BFBFFFFRLL
FBFBFFBRRR
FFBBBFBRLL
BBBFBFBRLR
BFBBFBFLRR
FBBBFFFRRL
BBFFBFFLLL
BBBFBBBRLR
BFFBFFBRRL
FFBFFFFLRR
BFBBBFFRRR
BFFBBFFRRR
BBFFFFBLLL
BFBBBFFLLL
FBFFBBFRLR
BFBBFBFRLR
FBFBBBFRRL
BBFFBBFLRL
FBBFBFBLLR
FBFFFFFLLR
BFBFFFFLRL
FBFFFFFLRR
FBBBFFBRLL
BFFFBFBRRR
FFBBFFBRLR
FBBBBBBLRL
FFBFFBFLLL
BBFBFFFRLL
FBFFFFFLRL
BBFFBBBRRR
FFBBFFBRRR
FFFBFBBRRL
FBBBFBFRRL
BFBFFBBLRL
BBBBFFFLRR
FBBFFBFLRL
FBFFFBFLRL
BFFBBFBRRR
FBFFBBBRLR
FBBBBBBLLR
BFBFFBBLLL
BBFBFBFLRR
BFBFBBBLLL
BFBBFBFRLL
FBBBBBBRRL
BFFFBFFLLR
BBFFBFFRLL
BFFBFFBLRL
BBFBBBFLLR
FBFBFBBLRR
FBFBBFBLLR
BFFFFBBRRR
BFBFFFBLRL
FBBBFFBLLR
FFFBBFBLLR
FFBBBFFRLR
BFBBFFBLRR
BFBFBBFRLL
FBFBBBBRRL
FBBBFFBRLR
FFBBBFBRRL
BBFFBFFLRL
BFBBFBBRRR
BBBFBBFLLR
BBFFFBBLRL
BBFFBFBLLR
FBBFBFBRLR
BFFBBBFLRR
BFFBFFBLRR
BBFBBFBLLR
FFBFFFFRRL
FBBFFFFLRL
FBBBFBFRLL
BFFBBFBLRL
BBBFFFFRLL
FFFBBBFRRR
FFBFFBFRRR
FBBBFFFRLR
BFFBFFFRLR
BFBFBFBRRL
BFFFBBBLLL
BFBBFBFLLR
FFFBFBFLRL
BFBBBFBLRL
FBBBFFBLRL
FBFFBBFRRL
BBBFFBBLRR
FFFBBFFRLR
FFFBFFFRLL
FFBBBFFLLL
BBBFBBFRLL
BFFFBBBRRR
FBBBFFFLLL
BFFBFFFLRL
BBFBFFBLRR
BFBFFFBRLR
BFFBBFFRRL
BFBBFBBLRL
FFFBBBBRRR
BBFBBFFLLL
FFBBFBBRLL
FFFBBBFLLL
FFBBBBFRRL
BFBFFBFRRL
FBFBFFBLRR
FFFBBBFRRL
BBFFBFFLRR
FBFFBBFLRL
BBBFFBFLRL
FFBFBFBLRL
FFBBFBBRLR
FBBFFFBRLL
FBBFFBFRLR
BFFBFBFLRL
BBFFBBBLLR
FBFBFBBLRL
BBFBBBFRRL
BFBBBFFLRL
BFFBFBBLLR
BBBFBFFRRR
BFFFBBBRLL
BFFBFBFLRR
BFBFBFFRLL
BFFBBBFLRL
BBFFFBFRLR
BBFFFFFRLR
BBFBBFBLLL
BFBBBBBLRR
BFFFBBBRLR
FFBFBBBLRR
FBFFBFFLRR
BFBFFBBLRR
FFBFFBBRLL
BBFBBBBLRL
FFBBBFFLLR
FBFBBFBRLL
BFBFBFFLLL
FFBFFFFRLL
BFFFFFFRLL
FBBBFBBRRL
FBBBFBFLRL
FBFBBFFLLR
BFBFFFFRLR
BBFFBBBLLL
FBFFBBFLLR
FBFBBFFRRR
BBBFFBBLRL
FBBFBFFLRL
FBFFFFFRRR
BBFBFFBRLL
FFFBFFBLLR
FBFFFFFRRL
FFBBFBBLLL
FFBFFBFRRL
FBBFFBBRRR
FBFFFBBRLR
FBBFBFFLLL
BFFFFBFLRR
FBFFFBBRLL
FFFBBBBRRL
FBBFBBFLLR
FFFBBFFRLL
FBBFBFBLLL
BFBFFFBLLR
BFFFFFBLRL
BFFFBBBLRL
BFBBFBBLRR
FFBFBFFRRR
BBBFBBBLRL
BBBFBBFRRL
FFBBBFFLRL
BBFBFBFRRR
BFFFFFFLLR
BFFFFFBLLL
FBFBFFFRRL
BBBFFBFRRR
BFBBFBBRLL
BFFFFBFLRL
BBBFFBFRLL
BBBFFBFLRR
BFFFFFFLRR
BBFFBFBRRR
BBBFBBBRLL
BFBFBFFRLR
FBBFFFFRRL
FBFBBFFRLL
BBFBFFFLRR
BBFBBFBRRR
FBFFBFBLRL
FFBFBFFLLR
BFBFFFBLLL
BFFFFBFRLL
BBFFFBBRRR
FBBBFBFLLL
FBBFBFFLLR
FFFBBFFRRR
BFFFBFFRRL
BFBBFBBRRL
BFFFBFBLLR
BFFFBBFRRR
BFFFFBBLLR
FFBBFFBLRL
FFFBBBFLLR
BBBFFBBRLL
FFBFFBFLRL
BFFFFBFRLR
BBBFBFBLRR
BFFFBBFRRL
FBBFFFFLRR
FBFBFBFRLL
BBBFFFBRRL
FBFBFFFLLR
BFBBFFFLRR
BBBFFFFRRL
BFBFFBFRLR
BBFFFFFLLL
FBBFBBFLRR
FFBBBFBLRL
FFBFFFBRLR
FBFFFFFRLR
BBBFBFBRRR
BBBFFFFRLR
BFBBFFFRLL
BFBFBBFLLR
FFBBBBBLRL
BFFFBFBLRR
FFBFFFBRRL
FBFBFFFRRR
BFBBFFFRLR
FBBFBFBLRR
FFBFFFFLRL
BBFFFBBLRR
FFBFBBBRRL
FBBFFBBLLR
FBFBBBFLRL
BBFFBFBLRL
BBFFBBBRLR
FBBBFBBRLL
BBFFBBBRRL
BFFFBFFRRR
BFBFFFFRRR
BFBBFFBRLR
FFFBBBFRLR
BFBBFFFLRL
BBFFFBBRRL
BFFBFFBRLL
FFBFFBBLLL
FFFBBFFLRL
FBFFBFBLRR
FBFBFBBRLL
BBBFBBBRRR
FFBBFBBRRL
BFBBBFBRRL
FFBFFFBRRR
BFFBBFFRLR
FFBFFBBLRR
BFFFFFBLLR
FFBBFFFRRR
FBBBFBBLLL
FFBFBFBLLL
FFBBFFBRLL
BFBBBBBRRL
BFBFFBBRLR
BBBFBBFLRL
BBBFBFFLRR
FBBFFFBRRR
BBFBFBBRLL
BBFBFFBRLR
BFFBBBBLRR
BBFFBFBLLL
FBBFBBFLRL
BFFBFBFRRR
BFFFBFFRLL
FFFBBFFLRR
FBBFFBBRLR
FBBFFFFRLR
BBFBBFBLRR
FBFFFFBLRL
BBFBBFFRLR
BFBFBBBRLL
FFBBFFBLRR
FBFBBFFLRL
FBBFFBFRRR
FBFBFFFRLL
FBFFFBFLRR
FFBBFBBRRR
FFBBFFFRLR
FBBFFFBLLR
FBFFFBBLLR
BFBFBFBLLL
BBBFBFFLLL
BFBFFFBRRR
FFFBBFFLLL
FBFFBFBLLL
FFBFBFBRRL
FBFFBBBLRR
BBFBFBBLLR
BFFBFBFLLL
FFFBBBBLLL
FBFBBFFLLL
BBBFFBFLLR
BFFBBFBRLR
FBBBBFFRLR
FBFBFBBLLR
FFBFFFFRRR
FBBFBFBRRL
FBFBFFBRRL
BBFBFFFLLL
FFFBFBBRLR
BBBFFFBLLL
FBBBFFBLLL
FFBFFBFRLL
BFFFBFFLLL
FBFBFFBRLL
FFBFFBFRLR
FBBFFFBLLL
BFFBBBFLLR
FFBBBBFRRR
BBBFFBBRRL
BFFFBBBRRL
FFBBBBBLLR
FFBBFFFLRL
BFFFBFBLLL
BFBFFBBRRR
FBFBBFBRLR
BFFBFBBRRR
BFBBBFFRLR
BFBBBBBRRR
BFBFFFBRLL
FFBFBBFLLL
BBFFBBFLLR
FBFFFBBRRR
BBBBFFFLLL
BFFBBFFLLR
BBBFFBFRRL
BBFFBBFRLL
FFBFBBBLLR
FBFFBBFRRR
BFFFFFFRLR
BBFFFFFLRL
FBBBBFFLRL
BFBFFFBLRR
FBBBFBFLLR
BFFFBFBRRL
BBFFFFBLRR
FFFBFBFLLL
BFBFBBFRRR
BBFBFFBLLL
BBFFBFBLRR
BFBBFFBLRL
BBFBBFFRRL
BFFBBBBLRL
FBBBBBFLLL
BFBBFFFRRR
FBFFFFBRLL
BBFFBBBRLL
FBFBBFFRLR
FBFBBFBLRR
FFBBFFBRRL
FBBBBBFLLR
BBFBFBFRLL
BBFBBBFLRL
BFBBBFFLRR
FBFBBBBLRR
FFBFBBBRRR
FBBBBFFRLL
BFFFBBFRLR
FBBFFBBRRL
BBFFBFFRRR
FBBFFBBRLL
BFFBFBFRLR
FFBFBFFRLL
FBBBBFBRRL
FFFBFFFRRR
FBFFFBBLRR
FBBBBBBRLR
FBBBFBBRLR
BFBBBBFRRL
BFFFBBFLRL
FBBFBBFRLR
FFBBFBFRRL
BFFBFFBRLR
BFBBBBFRRR
BFFFBFBLRL
FBBFFFBLRR
BBFFFBFLLR
FBFBFFBLLL
BBFBBBBLRR
BBFFFBFLRR
FBFFBBBLRL
FBFFBBFLRR
BFBFFBBRRL
FBFFBFFRLL
BFBFFBFLRL
FFBBBFFRLL
BFFFBBFLLL
BFFFBFFLRR
BBFFFBFRRR
BFFFBBBLRR
FBFBBFBLLL
FBFBFBBRLR
BFBFFBBRLL
BFBBFFFRRL
BFFFFBFRRL
BBFFBFFLLR
BFFBFFFRRR
BFFBFFFRRL
BFFFBBFLLR
BBFBFBBRRR
BFBBFFBLLR
BFFFFBFRRR
FFFBBFBLRL
FFBBFBBLRR
FFBFBFBRLR
FFBFBFFLRL
FBFBBBFLLL
BFFFBBFRLL
FBBFBFFLRR
FBFFFFBLRR
BBBFFFFLLR
BFBBBFFRLL
BFBBFFFLLR
FFBFFBFLLR
FBFFFBFLLR
FFBFBBFLRL
FBFBFFFRLR
FFFBFBBLRR
BBBFFBBLLR
FBFFBFFRRL
FFFBBBFRLL
FFFBFFFRLR
FBBBFBFRRR
BBBFBFBRRL
BBFFFBBRLR
BFFBFBFLLR
BFBBBFBRLL
BBFBFBBLRR
BBFFFFBRLL
BFFFBBFLRR
FBBFBFFRRL
BFBFFBFRLL
BFBFFBFRRR
BFFBBBFRRR
FBBFBBBRRR
FBBFBBBLRL
BBFFBBFLRR
BBFFBBBLRR
BFFFFFBLRR
BBBFFBFLLL
BFBFBBBLRR
FBBBFBBLRL
BBBBFFFRLR
FBFBBFBRRL
FBFBBBFLRR
BFBBBBFRLR
BFFFFBBLRR
FBFFBBBRLL
BFBFFFBRRL
BBBFBBFRLR
FFFBFBBRRR
FBFFBFFRRR
FBFFFFFRLL
BBFFBFBRLR
BFFBBBBRRL
BBFBFFFLRL
FFBBBBFRLL
FBBFBFFRRR
FFBFFBBLRL
FFFBFBFRLR
FBFFFFBRRL
BBFBBBBRLR
FFBBBBBRLL
BFBBBFBRLR
FBFFFBBLRL
BFFFFBBRRL
FFBFFFBLRL
BBBFFFBRLR
FBFFFBFRLR
FBBBBFFRRR
BFBBFFBRLL
FBBFBBFRRL
FBBBBFBRRR
BBFFFFFLLR
BBBFFFBLRR
BBFBFBFRLR
BFFBBBBRLR
FBFBFFFLRR
BFBBBBBRLL
FBFBFBBRRR
BFFFBFFRLR
FFBBBBFLRR
FBFFFFBLLR
FFBBFBFLRR
FBBFFFBRRL
FFBFFBBRRL
BBBFFFFLRR
BFBFBFBLRR
BFFBFBBLRR
BBBFFBBRRR
FFBBBFBLRR
FBFFBBBLLL
FFBBBBFRLR
FBBBBFBLLL
BFFBBBBRRR
FFFBFBFLRR
BFFBBBFRLL
FFFBBBFLRL
FBBBBFFLLL
FFFBBBBRLR
BFFBFBFRRL
BFFFFBBRLL
FBBFFBBLRR
FFBBFBFRLL
FBBFBBBLRR
BFBFBFFRRR
FFBBFBFLRL
BFFBBFFLRR
BFBFFBFLLR
BFBBBBFLLR
FBFBFBFRRR
BBFBFBBLLL
BBFBFFFRRR
BFBFBBBRLR
BBFBFFBLLR
BFFBFFBLLL
FFBFFFFRLR
BFFFFBBLLL
BFFBBBBRLL
BFBFBFFLRR
FBBFFBFLLL
BFFFBFBRLR
FBFFBFFLLL
BFFFFBFLLR
FFFBFBBLLL
FBBBBBFRRL
BFFBBFBLLR
BBBFFFBRLL
FFFBFBBLRL
BBFFBBFLLL
FFFBFFBRLL
BFBBFBFRRL
BFBBBFFRRL
BBBFBFBLLR
BFFBFFFLRR
FFFBBFBLRR
BFFBBFFLLL
BBFBFBFLRL
BBFFFFBLRL
BFBFBFBRLL
FBBBFFFLRR
BBBFFFBLRL
BBFBFFBLRL
BBFFBFBRRL
BBFBFFFRLR
BFFBBBFLLL
FBFFBFBLLR
BBFBBBBLLR
FFBFFFBLRR
FFBBFBFRLR
BFBFFFFRRL
FBFFBFBRLL
FFBFFBBRRR
FFBBFFFRLL
FBFBFBFRRL
FFBBBFBLLR
FFBFBFBLRR
BFBBBBFLRL
BFFBFBBRLR
FFFBBBBLLR
FFBFFFFLLR
FBBBFBBLLR
FBFBBFBRRR
BFBFBFBLLR
FFBBBBBRRL
FBBFBBBLLL
FFFBBFBRRR
FBBFBFBRLL
FBBBBBFLRL
BBFFFFFRRR
BFBBBBBLLR
BFFBBBBLLR
BFBBFBBRLR
BFBBBBFLRR
FBBBBFBLRR
FBBBBBFLRR
BFFBBFBRLL
BBFBBFBRLR
BBFFBFFRLR
FBBFFBBLLL
FFBFBFFLLL
BFFFFFFRRL
BBBFBBBLLR
FBFFBBBLLR
BBFFFBFLLL
FBFBBBFRRR
BBBBFFFRLL
FBFBBBBRLL
BFBFFFFLRR
BFBFBBFRLR
FBBBFFBRRL
FFBFFFBRLL
BFBFFBFLRR
BFBBFBFRRR
FFBBBFBRLR
BBFFFBFRRL
BBBFFFFLLL
FFBBFFFLLR
FFBBFFFLRR
FBBFFFFRRR
FBFBBBFRLR
FFFBFFBRRL
FFBFBBFRRR
FFBBBFBLLL
FFBBFFBLLL
FFFBBFBLLL
FFBBFBBLRL
FBBBFFFRLL
BBFFBBBLRL
BFBBBFBRRR
BFBFFBBLLR
BFFBFBBLLL
BFBBFFFLLL
FFBFBBFLRR
FBFBBBBLRL
BFBFBBFLRR
BFBBBBFRLL
BBFFFBBLLR
FBBFFBBLRL
FBBFBFFRLL
FBBFBBBLLR
FBBFBBBRLR
BBFFFFBLLR
FBBFBFBRRR
BBBFBFBRLL
FFFBBFFLLR
BBBFBFFRRL
BFFFFFFLLL
FBFBBFBLRL
FBFFBFFRLR
FBFBFFBLLR
FBBFFBFLLR
BFBFBBBLLR
FBBBBFBRLR
FFBBFBBLLR
BFBBBBFLLL
FFFBBFFRRL
BFBFFBFLLL
BBBFFFBLLR
BBFFBFFRRL
BFFFFBBRLR
BBFFBBFRLR
BBBFFFBRRR
BBFBBBBLLL
BFBFBFBRLR
FBBFFFFRLL
BBFBBFFLRR
BFBFBBBLRL
BBFFBFBRLL
BBBFFBFRLR
FFBFBFFRRL
BBFFFFBRRL
FBBFFBFLRR
FBFFBFFLRL
BFFFFFBRRR
BFFBFBBRRL
BFFBFFFLLR
BFFBFBFRLL
FFBBBBFLLL
BBFBFBBRRL
BFFFBFFLRL
BBBFBBFRRR
FFBFBBFRRL
BFFBFFFRLL
BFBBBFBLRR
BFFBFFFLLL
FBFBFBFLLR
FBBBBBBLRR
FBFFBFFLLR
FBBBFFFLRL
BBFBBBFLRR
FFBFBBBLLL
BFBBFFBRRR
FFFBFBBLLR
BFBFBBBRRL
BBBFBBFLLL
FBFBFFBRLR
FFFBFFBRLR
FFFBFFBRRR
BFFBBFFLRL
BBBFBBFLRR
FBFBBBFLLR
BBFBFFFRRL
BFBFFFFLLR
FBBFBBBRLL
FFBBFFBLLR
FBFBBBBRRR
BFBFBBFLRL
FFBFBFFRLR
FBBBBBFRLL
FBBFBBFRLL
FBBBBBBRLL
BFBFBFBRRR
FBBBBBFRLR
FFBBFBFLLL
BBBFBFBLLL
FFBBFBFRRR
BFFBFFBLLR
BBFBBFBRLL
FBBBBFBRLL
FFFBBBBRLL
BBFBFBFLLL
FBBBBBBLLL
FFFBFBBRLL
BBFFFFFRLL
BBFBFFFLLR
FBBBFFBRRR
BBFFFFFLRR
FFBFBBFRLL
FBFBBBBLLL
BBBFFFFRRR
BFFBFFBRRR
BBBBFFFLLR
BFBBBFFLLR
FBBFFFFLLR
FBFBFBFRLR
BFFBFBBLRL
FBFFFBFRRL
BBBFBFBLRL
FFBBFBFLLR
FBFFBFBRLR
FFFBBBBLRR
BFFBBBFRLR
FBFFFFBLLL
BBFBBBBRRL
FFBFBFBRLL
BBFBBBFLLL
BFBBFBBLLL
FFBBBBFLRL
FFBFBBFLLR
FBFBFBBRRL
BFFBBFBLRR
BFFBBFBRRL
BFBBFBBLLR
FFFBFBFRRL
BBFBBFBLRL
FBBFBBFRRR
BBFFFBFLRL
BFFFFFFLRL
BFFBFBBRLL
FBFFFFFLLL
BBBBFFFLRL
BBBFBFFLRL
BFBBBBBLRL
FBFBFFFLLL
FFFBFBFRRR
BBFBBFBRRL
FBFFBBFRLL
FFBFBBBLRL
BBFBFBBLRL
FFBFBFFLRR
FBFBBFFRRL
BBFBFBBRLR
BBFFFFBRLR
BBFFFBBRLL
FBBBBBFRRR
FBBFFFBRLR
FFBFFBBLLR
FBBBFFBLRR
BBFBBBFRLR
FBFBFFFLRL
BFFFBBBLLR
BBBFBFFLLR
BFFFFFBRRL
FBFBFFBLRL
FBBBBFFRRL
FFBBBFFRRL
FBFBBBBRLR
FBBBBFBLRL
BFFBBBFRRL
BFBFBBFLLL
BFBFFFFLLL
BFFFFBFLLL
FFBBBFFRRR
BBFFFBBLLL
BBBFBBBLRR
BFBBBFBLLR
FFFBFBFLLR
FBBBFBFRLR
BFBFBFFRRL
FBFBFBFLLL
BFFFFFBRLR
BBBFFFFLRL
BBFBBBFRLL
FFFBBFBRLR
BBFBFFBRRR
BBFBBBBRRR
FFBBBFFLRR
BFBBFBFLLL
FBBBFBBRRR
FFBFBBBRLR
FFBFBBBRLL
FBBFFBFRRL
BBFBBBFRRR
FBBBFBBLRR
FFFBBBFLRR
BBFBFBFLLR
BFFFFFFRRR
FFBBBBBRLR
FBBFBBFLLL
FBBFFFFLLL
BBFFFFFRRL
FBFFFBFRLL
FBFFBBBRRL
BBFFFBFRLL
FBFBFBBLLL
BBFBFFBRRL
FBFFFBFRRR
FFBBBBBLLL
BBFBBFFLRL
BBBFBBBLLL
BBFFBBFRRL
BBBFFBBRLR
FBBFBFBLRL
FBFFFBBRRL
BFFFFBBLRL
FFBFBFBLLR
FFBBBBBRRR
FBBFBFFRLR
BBFBBBBRLL
BFBFBBBRRR
FBFFBFBRRL
FBFBFBFLRL
BFBBFBFLRL
FFFBBFBRLL
BBBFFBBLLL
FBBFBBBRRL
FFBBBBFLLR
FFBBFFFRRL
FFBFBBFRLR
BBFFFFBRRR
FBBBBFFLLR
FFBBFFFLLL
BFBBFFBLLL
FBFFFFBRRR
BFFFBFBRLL
FBFFFBFLLL
BFBFBFFLRL
FFBFFBBRLR
FFFBBFBRRL
FBFFBBFLLL
FBFFFBBLLL
FFBFFFFLLL
FBFFBBBRRR
BFBBBBBRLR
BFBFBFFLLR
BBBFBBBRRL
FBBFFFBLRL
FFBFBFBRRR
FFFBFFFRRL
FBBBFFFRRR
BFBBBFBLLL
FBBFFBFRLL
FFBFFBFLRR
FBFBFBFLRR
BFFBBFBLLL
FBFBBFFLRR
BFBBBBBLLL
FFBFFFBLLR
FBBBBFFLRR
FBBBBFBLLR
FFFBFBFRLL
FBFBBBBLLR
FFFBFFBLLL
BFFBBFFRLL
BBFBBFFRRR
FFFBFFBLRR
BBBFBFFRLR
BBFBBFFLLR
BBFBBFFRLL
FFBBBBBLRR
FFFBFFBLRL
FFBBBFBRRR
BBBFBFFRLL
FFFBBBBLRL
FBFBBBFRLL
FFBFFFBLLL
FBBBFBFLRR
BBFFBBFRRR
BFBFBFBLRL
BFBFBBFRRL
FBBBFFFLLR
FBBBBBBRRR
BBFBFBFRRL
BFFBBBBLLL
FBFFBFBRRR
FBFFFFBRLR
'
]

{ #category : #data }
AdventOfCode2020Tests >> dataForDay06 [
	^ 'su
egu

h
h
h
h

cpuqz
cfqu
cqekuv
xunqc

hsaygprt
hsfatgyr
srtagyfbph
rgqywhsealtx

aefomnlihcsdpyvxurbkq
ipudhrafbcszoxmeqknv
hpricubknmdoqsjvfx
uiwohncxmrpsgqbfvktd

tvruzqbyspjdfalicehwkm
haswlezrvxjbtckfyipmq
alzkjcqpbsfmetihuvyr
rkjibhvylpfqscaemzt
zjctmrhpseqgfklnibyva

ix
akdhy
felrouzwt
ygs

pifgwbtvs
gkwbcpixmt
pbrgitw

vex
iyhmwl
cks
fj
dzsfn

xsvmdzrpq
ipzmvdgsxqa
tcouzvhdqxwlspe
psjydqizxgv

sdcgvhx
ieupwazvdxq
vgfxd
xgjdbslv

cla
aj
a

unvhtezsdrxjyka
sruxtezyjhdbkav

f
s

l
l
l
l
l

dqlpmwrfuaeioc
kzpyiembgthnj

ks
qoh
cftlim
ukv

ekfwgpbaurcqijdvhtxznl
tafuqxhgjkizprsvylcedb
eukbxaligpfhdvrqtczjm

muikcbg
ithfkq

ojdwcsigaflpykv
uzjmbhrdlxnt

v
v
bv
v
vf

il
li

sfqoutzki
erfsuxcjqhtk

op
gbepq

vtzpwj
ijmxtzv

zvoxpf
bwiexz
birzwxq

h
f

pjiae
pjkyza
akzptjb
ajipz
sjhap

xerdismyblco
yaiowgpsedtnzrhx
dilmokqxybrescu

bxeclkt
bighzytlw

itokcrbm
isa
iwuq

rqcue
pisb

gpdmiyet
mwtgl
gmtdz

hrselofawdu
roadesjfukh
sopadrhefuj
drusaofeh
hsdoekafur

matixrjqfw
traxmfqwisj
ajtqkrwmfi
ipmwjaftvrq

eyvmb
bht
nkpbw
ehtba
zdrsjxblf

efpgnzjdabsukr
kjpagiumfsbedzrn
djngsrapubzefk
kfbzpeadgrujsn

pwnqbhjv
vwqhbp
qwbhvp

sdlizutpwkfbhjm
sdqvrpuflmwjz

uxahnymvs
xnrlpebt
gnzlxjfoq
kfzxn

amedtwkgxcypbrqnujvifhs
saxvbymtfrhgdiwqjnkcpe
erjkmaigvdfxcnbtyqhwps

ivb
vbi
vbi

gme
gem
gme

h
p
e
e
e

b
b
b
b
bl

t
l
l

zda
efmil

ulx
solxwu

gclsqwx
cgxswl

qawroeb
owfeqlzxbn
igratbowseq
otvcqjbegw

mcahbeizsjovynpx
nsbdiclahpmxyove
qgepcisukanhmwyv

cogbsyu
cusogb
uxoscbgf
bpugchsort
bgocmsuv

jxigcazhlfsruwetkpynmvqo
drkvthunlgcsyeaxzqpjfwimo
syaeqcvmuxpnkgtwjfhbozilr
mgczoqvyhjuxreawtnkfpsil
acouwfqpjtgkrxyzivehsnml

xpyldvrbug
falxpgdzuhsvrt
ldewxuvpgrtm

jzbpury
hlgzxrkpouavq
emirbuzcp
wnfumipczrb

liydasvrkgqe
ayidqgrsvel
vdjygiulearpws
gvedasikylr

ikatocyfxps
spaoikxctyf
ckpsxfioyuta
waxiforkpystc
xcmykipsftoa

zxleoadsyv
yovaleu
veaoyl

qnmkplahgtubszedcij
pscidealhtqjbguynz
jqseucdgzbpilanth
liahqmuznjscdbpgyte
avqrielhntdjzpgxubsc

uflmyhndsqboxv
mnlofduxbsqyvh
kvoptzfmrgysanuhxblqdjec
dfsnbvxolqmyuh

ihrjpxygmfudqwcaoezt
jdlbmonxwraiqyctzhvupfe
utfhadqciozemwjpryxg

mcy
my
ym
aym

euktqozh
qvjfhalk

ziblapqkvhcmdte
lfqkvdeaicmztph
mliqbcvpkathz
ylwiochpqmtakvjz

oahnmutxc
hncxomtuva

kfnsgxhiyzcbjmwvloe
ezciqlkbmspnfgx

fatwrkenzmlij
rftamzejnskiwl
nlifwzaerjmtk

ygpdfunhz
ycfquwndg
ygfnud
nfrygudbt

wargt
vzumj

pevirabdgyntjmfzxu
fbajcpgwtmveixnyzu
fqkgtevmuiybnjxapz
gufjytsplnvamozeixb

n
w
wsp
y
dheck

dyltqraen
tpsgabzmoexn
rvkailytneq
tfnayeihu

ewsxrgjbqyno
qmswbxnjogrye
gobjqesnywxr
bsyexgrnwjoq
rbjewonsqgxy

stwikjqlp
lrsiupwhofjtk
pljtwiks
pwkijqstl
cslkjtwpiq

tpdekxavhynbmwq
cplmqztabw

tagofzql
leaoktp
ltnuaoxv
kylztoa

cyhkmbsxfwjndv
xykhbcfvmenwdsj
ycfmjwvnbhxskdz
ecvmhdkjbwsxfyn
xbksdmhwfjvycn

dwhonqeszgyucxip
ilbhvtupfksgzm

oazfpt
ozfpbt

yxor
xrbe
brxe
rx
erx

d
d
d
d
d

ihnyoscrtazjfwme
jibycpvemkqzas
jbaivmzxsgecudy

kmsp
smapk
jmpek

wbeoh
zon
fzoq

cmbwrupzjkq
qzbprmkowuj
rajuzkbwmpq
ljrpxbuztwiqkme

ijnglzsbcqfawohpdxmtve
aqpzxbndsfgtomwlvehjci
ambcxwlvdzqftenorgjsihp

rbjtkm
krm
mkr
mrk

qjkdftrpnumcizayl
wqplnjcudgxzmkriatyf

qlhrxgeftoy
bzorhtyxlpqegf
egbolyfxrthq
etflxyhoiqrg
fyruhtqgoxel

ydogmjnixtkw
yminkvjwfpdqgo
nigxjwoykmd
igwjnydkxom
nikydjgmow

s
s
s

mctyqjebhrx
jmteybcxhq
vmbtseyoxhacdl
miyeqcxhtb
cmuybexth

j
jrn
j
j
j

gjwhqzotyivsa
dncumikebpr

rjgvkwqib
dumtbxzowfylh

oge
eivjdbkmcywg
eg
gfoe
ge

qebcdswmkoygivfhzt
hxyztepdnocigquwvbfa
dgtwcyhfivboeqz
cdhbgtveizowfylqk
yfzbqhlvitmcgwedso

evhlbqwtrfx
mlfbwh
hbflwp
bfwlkhim
whnfbl

pcrf
crhf
fcr
cfr

okxihbndges
cfheijbgqotnsk
yngobhskevi
rgknsoielhb
dknoeisbhg

nztcvyikjfx
fkityvjxnc
kjvnfycxilgtp

tjlbadpizowyev
qehgkdrzbcvotlay
falbynztqeodhv

x
x
x
x
x

ausbpe
sbeauop

ftgly
bf

erhokg
gekohr
hrgkeo
ghreko
hregko

ag
ga
ga
ag

vempgsokyfctax
ckonsxfptmyvge
yxefdorjmuzhvpsgwbltck
esxmcvgykfnpot

thob
obe

xg
qyalvxc
xg
x

sqyowmanjczfebkulxtvgid
fahgqzenwypcbrmtvjslok

zohlmctqxnueg
jhpbgfkds

fyj
cwojdbf
jtf
rfjt

hycpvrmfqlngu
vmqcypgunlrh
pqmhuvylgncr

rxgswj
dwsybphk

pcozvsdx
kvznm

xneik
xkin
xinqk
nxsjik

btfdr
jbqcasvpd
tkubd
ubdxwr
towilbd

bfjidznx
nxbijdzf
jzfxidbn
nifdbxjz
nzfbidjx

kjnydrclqeiumxg
foidejlnxgckm
coinexmgdlkj
lpckgdvnhmjxei

upnhgfa
uhfpn
uhpfn
phufn

hvyqepkfdsulzb
kfdepzvyhqlb
yezgbkqpvfdh
yzpfkegqdvhb
ykveqbfjzhwrpd

lvndux
uxdnlv

skymq
yqmi
yqzm
zymutq
qym

lgnxbpzsce
eczlspaibgt

raimheuwjdlsvncoypgzbqkxt
gcwavnjedbxsyfkqlprthuimoz
gjszrpmaxbydoktivewhlqncu
tojqzuenragvmxckiydphslwb
xeacszmjuliyvqdgkwprbnoht

eahlnzupx
ulhmektsxdyjz

zulrwsdaq
rqilsadz
tarlisqmdz
arslzdq

pwzjtoafs
pzjwoafts
joafwztps
fzstwojap

qbsykroiwcmzugealpxfjtdn
rcketgxqjupwzbymofaidns
kbngvtqdysrpumcejwaifozx

vxpyulwietrmfqbo
tyeqbwxprmvfl
jlqismvbdprexwtkyf
betvyxlrnmwaqfpc
pqywsxoerfitvmbl

osgilzptxmyhdwnbkjucvfq
iovflbqpkshyxdcjtg
iphsqdgyjfcevlotxk

pdmxwbrzyk
orxtiplgmeua

rkeaoq
muncxwzvjtfp
eyhkiqso

acjpbvh
knmspwuebjyvgft
vbjpd
pqbvrj

spld
qlaogwv
fhzjnmixyrut

khmw
sjqdtwk
pckw
okwjz
ybvnuakxwgr

js
j
qj
j
je

sdqftlargy
jrmtgfaydoizsl
rtdlwafsyg
rtfylgwsad
adgltwryefs

ujxfzvaptw
txuwfjzp
vjuzfatwxp
gnzfxptwju

ltnfhrdwxv
dnwxtprhfv
hxfdntvawir

sd
tl
dvytb
cv
pofkherqumi

bnhwe
iwesc
swe

xgukzobv
xkzugbafjrov
ebxukzgvo

yor
ior
ryo
royk

wj
jzw
wj
wj
jw

pigbdcozntylm
toxilbam
bixopln
bvwkrloiefuh

eduk
uekd
eudk
ckdue

vulk
klvu

jeyafmuqxd
aoxfed
edxaf

sjbkveaymcdtgx
gtskxcyqmhvjarfn
jrngyohawxkqmpcvst

fmubgnqisdyax
axnydgimfuts

nzkrjofhqiubspv
fksopnbuihrjqvz
vhrbipqfjsozknu
urfvnibojqpkszh
jvnpuzkifhobqsr

ctikjyqxempoh
comiqtxhjpkny

whbdemfkursty
ryfuqxvkwmbesht
tkrumwhfsbeya
ryefhwstbmukn

xnd
flrakdi
rlps
ehqtbzvjgcouy

qvwihfpbd
imsfuvbrwhd
fvhdipbw
vhifdbw

uezrmltpvhd
fykjilqzsac

davlkgpqbwuc
bgvdnwlcuakpq
abuwhqckgzvtdplr

nd
fdrjxc
a
bmzeuwq

luopqihwtygjda
hodyuwapglqjbrti
agwqcijhduoyplt
qypgdtjlahiow
ljpskhxvqwyafiotdg

nhkdmtw
thyknm

jnfxrctwgqahudmoiyvs
axdtfwsonugzimcjrhlyqv
atcnfovyhjguxqimrdws

ue
cm
xrnozk
a

n
n
n
n
n

fojreag
e
enq
etdzqm
eb

wfsakpx
isfaxk
axwskvf
xeldakfsu

kzpwfxhab
gfkqxdhtpbwz
pfhazwxkb
wbpzfkxh

tbcn
mg
vbkmg
au
sfz

vangwftohxdbrzy
vohwdnbraftxzgy
xvozdtfargyhnwb
yardwbvhtofxzgn

irfa
irawf
iraf
ifra

jbtsqvywarn
bajcviqwyrt
kutgqjmlxaryzbvwo
rwsqjevdbyat

iyhg
hyg
hgy
gyh
ghy

qwidmahzfcueoskvlp
fkysbnihvumpaegtd
kaemjsurfdvhxip

oujsvbwceghnlpzxraf
ecaogrvjxluswpnfhbz
azexcujlfosbwnvgrhp
busrxgazjvpcfonwhel

ughqky
ntdwhmblxearjogzck
hfkyg
qighsk
khgp

cuzonhjegy
zujhocvnyeg
eoculrnjbgzywh
hjzcuyoegn
ugzvhcemynjo

lrigswxvmcqofua
owxmivacesurglkjq
wcmaqsirovxnglu
lisvmugqxrcofaw

t
mj
m
j
zdl

nmsexwigtjulcy
favyolnmgqtbrjkw

w
w
w

gxu
utx

mcgfu
g
gr
rg
gp

rhjaizdkxup
erblofajmvspxt

zt
tzf
lxmcowgyk

q
rux
q
g
q

uantxs
snwukxvjo

rixtwvc
vwciatx

ycipkftmez
yimcftepkz
empozcyfikt

aijwrvfmgyxlbztod
znytdgfbekxlpi

svqgfxh
nvkqgseaxh

mgqxhbl
zkvgqlbxm
lqgmxb

wq
fm

ktydgbsziqehmjfl
ksihgtdfjylze

ne
ne
ne
tenx

vzcwnxfimj
icvxzjmnwf
vzcmjrdxiwbnf
wjxnmfzcvi

dwy
h
ovk

nbowqrxlpyzifjvka
zyvxrolwfbpikqa
vkqdwrbyiapzxofl
kzebrvfiqypaomxlw

zjksb
zkjbs
zkbsj
bzksj

oeimldgvybkrznxhc
ejfxokaqhzd

esvbydlxc
nbvcxlyes
eoclzgsvxkmywb
eltvbcsyx
vnyelctsbx

hbjpermvdoc
hmjpercovdb
pjchombvred
vdrobejphcm

ipbeqnsmujhvtdkowc
bhmtonvedjkiuwcqsp

a
eg
t

vcmogkuapqrlsednzh
lvhzknodrcapxuetqs
nurkabhsywlceozdpfqv
ingvptqocaszlkurehd
skchauznlpvreodqg

oaqcwxnjr
btdki
cahmjsof
vuegzpyl

cvy
vyc
yvc

pqrtafjgizcldshx
ldsrhuqpjafgctinx

p
p
p

bwjtu
ft
fbp
qosmg

oixgna
wangjr
xomcdugal
agkftv

tvzoq
oatqsvc

xvnkdyz
kzdyafl

cxaquiretkwplvyszm
cmlqxwuertsozyaphi
fjzpsbytwnrxmqadgiceul

fnb
p
b

xvjswmpu
fuwspvxm

ofwkhlpbdarcze
eopfkwbazrhdl

m
c
a
m

cnty
ybonsp
nykrh
hnyc

tunpiybzjvskxwrgh
zhfcxlatqbmdygwrosev
yzdvgmxhesrbwtq

bflvmeipqojdngtyxuawh
ktdjovceibnugpsfymqxhl
vbueothjgpxfmilndqy
qjinbdmfoerpvhglyutx

d
d
d

vcmh
mch

ti
bt
rwhfdxtsy
ti
tmbi

ftiokrw
tofkriw
witkofr
tkowrif

akfsdozrbuleytnjivq
vaefyztrjboiqskhln
ladtnokzvirjbsyefpq

kyzuqsnpmclrhi
ulqznyrsckhpmi
zilfphqmucyrsnk

yrtjqxbfmalw
zsfmbqajcrgxyltwkv
yqmjaxwolfbrt
pnxlqmyrbwtfaj

qukbzapi
uzakbq
zkfbayv
tkaznb
qlbazk

pzfdbhyav
swlmrnt
rmw
jn
luqm

fmkgtbahndrqycowsplxiv
micuraxlznwhgbfkystqpo
ghrnsfwkcaoyimlbqtexp

kougsrdnt
xtrd
rtlwd
hrpdaty
xrdptm

nivmqo
ivqnmo
vmonqgi

tluszyrbkhg
rhyucgzetibl
wyuetgnlrzmh
rhdzvluqajotgxyfp

vhqmbdneyafzgw
lhwkvpaidgmyjzerq
hauvndomegwzqty

jcwlh
lwch
ltcw
weyckla

vcfrjqsgdtilbm
edltfjsrcmvbgih
bcylqfrmvstdgiej
fjbzklvdnwasmptcgori

acyvqjfgopdzksmw
dzofksgmycawpjvq
fogswakdzxpcyvmjq
mwqzsoydfcagpvjk
agsmowfzpykdvcjq

imxe
exim
iexmd

zkxaqfudyi
yacupxzkdqebfr
xwfuakhnmqvdzly
bqfydxakzru

ohaj
ajho
djoah
ohaj

xmra
mpa
mwaqn
am
anm

sgqjafrnbm
qfmrbjnas
rsfnjabmq
nsyjrbqfawm
mjfarkqsbn

fba
vfo

fncekxpr
epkbzds

qrpejclbhaf
lzcirpeqahjbf
lsphcjfbqaewir
rpnehulvcqayfj

ejkpzwght
tzkjegwxph

mxtojefrbdlnkwaz
mnwzjrbkaxoietfd
daktrfexnojpbzmw

zyeq
yzq
cwnax

pvqzxgs
xfqvszg
xsqpzvg

banycodivlqzt
mjbkheui
rbwixjf

ltq
tlq
olxtq
iltq

kerwtgcizshypfnxajdvolu
gueyjtxonfrsliw
lwruobigyesfnxtj
leqrmsoyfbigntjuwx

qsfokthwrlx
dlxosjagmr
xljorvsg

dgohszbxkmvw
gwzsboxvchkm
xkzohpsgwbvjm

mquspzhxlgktcid
xqktughicmdlzsp
cusqlzghkptxmid
zlscphgxdutimkq

vbrlu
rbdvel
lubvr

mkwzhyinogvxfl
gwzovxnkfhm
bksxgwzmvohn
mnwvgxlzkho
hgevxtklmwozn

m
m
jb

fjidp
pjsid
dfpji
pdij

nvsmdfhlzowxiqjp
npzqlhxifsvomdwj
dmfhsqxvnjwpzoli
vxoflmpdqzwjinsh
qsjwxoifldmnpzhv

xthm
mtxh
txmh
btxmwhd

b
c
kz
c

ohvnbcapejswtmrk
awskorhblqjepvtm

tvygs
ysvtg
gvsty
ytsgv
tvsyg

oyzucnqkxrimf
quxnfyzmckir
mrfkcqxyzniu
yferzmqixkucn
kfinqcrymxuz

gbuti
bniufgtw
giubt
igutb

jgtmbxs
mcbsxjt

huilkbsfytevzxwa
ibuhkapfyszedxrv
yufsaojhzkveibxg

mnswgtfdojhazrbq
athqodnrgwmzsfjbp
wtgdoaiuqnfxshbmrzj

wymeobr
mrycewo
oghswaxmzyufer
pemowyr

vxcfqtzadwkmipnr
iuarmqnpvdwkztx
dktmqbnvwarzixp

w
l

nprsxahzgfjltmwcbie
zmrlbnegfxscwaiphj
xzlwhejamsbipcgfrn
pwrealhncjbzgxmifs
mzwbepsjarflxnhcig

rqnie
qxnimer
ineqr

ergmlia
jgtxbszvfhy

tpbklr
plbtrk
tlbkpr
pkrlbt

e
e
e

ozqnktgywfjsm
ywfzxqcnomg
nqgfeczamywlo
dyfznqiomgbw

sxzgtkpvyedf
txgeyfmsd
difagyxtse

qoehywxtjgpdkavfs
bqjdigkxtwyfphev

dmni
dimn

tfrvu
tvaqruf
ruvztfwy
vuftqr

ydlrkcnoqahzjs
fhlnkersbcy
ervyucshkln

axkgudrfbvelt
pjuegtolfxdvika
evlkdfuzatgx
bxtvaefudklg
etxdlkafhguvr

hdcnjpfkbevusm
mblvpcfjseuhdn
bskjevpcufdnmh

wqnjbpoduamhytfkievszlgxc
xjlygvwsmhnauzkipotb
ixjknowtgzhbvumpylas
wtgnmbxriuhjplvakzyso

tl
tjl
ayufcpid
zxlm
zm

cnmwbldgaisjyzpfq
fjmrwsdibzqylcgpa
lozcsdmqfyaijpbgtw

dtf
fd

uqmtlwkfvo
yhpgrcdi
jhsnbezaxp

cefj
tfjce
tec
wsec

onazewv
wavykhnzd
lxsgvrzabmtcpq

nbcrxusghzimepqa
psqieacnuxohzgmbr
xhgrbqcnfvuspieamz
rixebsnmcpazdgjquh
sngeamhprxfcbquzwi

grydbjpzscfunwx
qcakmej

idhbcqoxzfuvt
dtocbufh
tfubdohc

yrp
ypr
pyr
yrp
rpy

bxlkfmjhqawictrnyvdpgus
unbrdyifkgwcsmptjhxlaveq
tlzjsycbnifvrdwuaphmkgqx

edkclbw
elwabdk

iehpmokrctn
pydojmegufz
mpxoeayujw

ewdarsfjpvlchmqiboxg
sfewicgrvdoxbmalhjqp
tsphvciwfqdgrexalbomj
vsxjleqokrfchybdpmiawg
rlqeiwpvacogmhjfbxds

y
y

vshoznkgwcdimrp
nzdrkoiehltvwsmg
gsjyoarznhwqvkdm
fshedmouvlrnzkwcg
vsokunwzrbdmhg

t
t
t
ta

paejgztcsxq
eszajxg
znjdgasxe
igxezjnas

ufakhtvdmr
adfmjhvkrtu
vmktjrzfdauh
tumkdfvhra
kutmavlhfrd

yxcnqsb
hpufomvwaz
lgai
agfdw

bytx
xrt
rhdtx

qcuypb
ycwlknup
cpuy
ucpy

l
l
l
yl
zlx

kradgyufzbxwole
xydwzbgfauole
alwugfoxbdyze

rob
oer
or

smul
lhms

hxrpgin
oxpcm
xpmc

ekcjs
nbkqpfjsc
puckyszjo
jsckb

mtakdsrxwecgozyi
lijgwkmsratdxoyzu
hkrtxgwyiamodsz

ucnfl
nuflc

uoh
shog
osh
oh
hovazw

aywsjgbkn
wgbqynskij
ybsgknjpa
ykqsbgnj
bzsgdxcnyjke

zwlxdg
wxgnlm
gdjwlx

vfkurtlgnqpszwod
nvtksfduzwqprglo
fkolzvndqwgurtps
oklfvqwtzgpunsdr

rbwfldicv
fopvzijb
hukbvgfqexyi
rnzvisfb
dbizvpaf

ruhvznkbqsxpmla
zhbxpvaqrmknuse
zbsrukpvnmaxwqh
azqrbmnsxkhvpud

onsfuwzlx
olsxufnvzw
ozfluxswn
oxwufzsln

xgzhikqe

pmwhykbvjduq
mxpfyjuvswah

eylbn
vebjwf
prhomzs
b

xqsvyfjgr
wqxrsl

whapjuqyd
uqgpwajd
aqwpuj
sfljpqnmaiuw
kabjpqgewvuc

cyrpbuoslqkz
zybkcxqfsrnue
yszrkqtucob

rtweslzqynuoxhmpbc
wuhbjyiackqfvpx

ahisomynwvbgklpjuzrxdtc
lxavshmbwykztcuniorpgdj
irdcxlzskwempjvghyatunbo

nlswcqkhvmxyfodrjizegu
mlxaqjovndhyrcgiufzse
fjdugnmlyeqzciovhxrws

suhwdifyrk
giwtnkpsfauydmc

weshq
qajovwhi

ph
ph
ph
ph

mrouzhwixysv
zarmsieovtyc
yrivmozs

vsxbz
svyxbzl
szqvxb
xzsbvq

b
w
w
w

cwetnkaxfvgirdphsolyzj
kapdhrvxezgwyfolijncts
vdlwgrocshaexyktzifjnp
ikezpjoraldxvfshwcgnty
frdysohpmjtlkxgzewcanvi

wcoqzgbitjlyad
duoznymtjbiwca
wpahfobjcuiydtz

aclkhypervifzjbwqgxdstu
sxlarjdgifwbztkchpuyvqe
tfdbrjxepvkslwqzciguhya
dyltqaruiwgckjvsbfxzhpe

qylp
qpy
yqpl
qype
pqy

xrkebt
tbrkemx
kebrtx
xketbr
etxrbk

yucsht
sycwu
vkuzcysl

qlfbrenuhm
qzfrnelmu
lrixmuefqn
qjmdspkfornela

vmtc
d

ait
ita
ait
ati
xavti

bxoygq
mtgbyoq

nkes
swkeg
kes
ksen
kres

saouewqmlfd
cygzlhbndtukixj

mxuboivyfpctzkael
qjbtgukilvmy
mktqbvhilnyu
gtjykviblusm
klbimtvyuq

fbdnvswoxpakthuz
adwhspktonufxzv
oamtszpdhkwyfnxuv
tudnvpzawockfxhs

ugxpjzytdbm
cerilwoby

onpmy
mylpo
pmoy
lmypo

jaf
afr
af

casenkqdir
sicuanvekrxh
yizacrkosntpe
agicxnrkesw

jqt
ql
qg
jq

wc
w
w
b

hzr
g
h
iabscl

hqwpsagbnldrukzjifytx
zpfrqidyshjkgwaxbtnul
fjiprlyakugwdqzhtbnsx
fiarukdwntlyhgzpbqsjx

czukvtah
comukqhjbra

wmhncxkspailt
uxfkbmrgt

teolabiy
hpktibyaxoc

bqyarip
wiyp
piny

mtrgebyouwfk
emwjyfrut
eruvtfywm
amwyfunelrptz

niduf
nfdiu
ifunjd

pelahycbn
hpovfylkcbn
iblwzqmxchgdstn
bnrjhkcul

sfjzl
sa

b
d
j
ji
j

zshvimlaw
alwsvmhi
vhlwsami
vhsawlmi

awvgejcbhlsintoupdf
gajfxdoebcphnsuwtl

tuickvpglhw
lvthdgiuwp
shuivyptl

nlxwpzuigcq
lcwpufgxzniq
wlxzuniqpgc
pjgxclzuwiqn

tsozgkq
lmvyuqracphne
qfitdwgkzjx

k
zk
skh
drkup
ablk

qcr
lq

m
i
jy
m

hrsgfwaeytpl
rifdnaq

detrifahwgjs
piagxwmfsrhe

g
l
l
t
u

xlphfs
tqnc
knrgiu

auscpvhwfnkjgxdbtlzo
wldqsafnxycpjzibrvu
fzpdcuvngbxwslaj
flsdbuwexnvajomzgpc
wazdljnbuxcfpvs

ejpwgam
pmgwja
jgawmp
wpamgj

jlupvzoyitmkeagfqnxswch
csahitmwogflvunqxkjpzey
vquxiozpmjatncwsykhlfeg
ihoejuxnwtsckzylqmfvagp
ovgfeciumakxsnpqyltzwhj

rlcy
lyrg
yr
hyqr

pnv
np

dxirheclfvkugyq
lmqcngrihtbzkoa

xmdr
cxdm
jmxlsdgq
dmx
xmdo

tomwqa
oqawmt
kwtbmaoq

jm
w

dem
dme
dejm

u
u
u
u

dhqxlsbnp
udbspl
ldbspc
kpsldbu
subkldp

wconqgth
vuhrlnzgt
kghntm
zhgnrt

tubwopjkrsglmfdqn
kpixtmabowfsjlezdnqrcg
ymjnolpqstbvfrgwkd

fykdachlrtxupbgq
aprdlbchfkguytejx
amvksrbwzlcfhyxgtupd

yac
cay
ydaeoc

yva
avxy
jyv
vyo

ryozihbkmxegfvw
ljexptfsyiwqcv

rszwmnhjp
mslwygz
zgwsm

lshvanz
vnlha
vnlha

glrmyfequjpboiczkhw
uozqrgjhwfceyidblmaxpk
wckorliguhqzmyfbepj

bc
dcj
bhc

ed
ed
de
led
de

geyxwujopkzd
pkwuzxjdoegy

fplwjykaod
rgz

qgpz
fpgaq

yfwzkgqej
vuzed
znhsecid

vlgxshtipzfj
vghilfsztxj
hxpisvfgtlzj
izshytgluxfvj

wyhoqaieuzf
lcjpm
btdxknglc
rclts

qucrslhpoywjidgkmvab
bvlidmwphqsoaykgurczj
ramesuijngcxpqlkdovbwh
ubapcqvshrgklwimojd

wfhcyjidtlqokx
nhgvuwobcklisdqm
drcnwvqslkaizohb

fidrkaw
fr
rueof

izypgsvlhfounrwemtdkqx
yfthniwaxlskqopvurg
xnqpustrywighalvbfko

gkihqofrasyz
xptgbqkim
iemgxqkup

rstvcynoaxpejid
xajeyproin
jixpmoreany
mriewajpxgony
rjaepyngiox

hysqpw
quwtyiph
hyqupw
jvfrnywqhlp
hwypqu

vojesgyt
vgeuyoj

kq
kgq

qash
qhsdvl

ogecvxt
gvtcxqeo
xtvcogeu

aiuzktwjnshlevr
ixuwcdgptmfzejl

mlsu
luy
wl
tl
golfv

ujxfyqdpchbk
mckfrhiqudxp
gkhbuxpcdfq

kamydczqfrsvg
szgkfuvyicmrqa
smcfgykqrvaz

hdyistonwvkuxm
uqospkewltar

iloqsexhubfy
deuiqbhfylxosw
jqheudxwsiblyofa
slahouqefyxib
gfntrbcyqxoeisulh

rtkqzxi
txzi
vygxiwzt
exztaci

pscgbunrdmlxz
vmolpgzcxndr
jrompngxdczl
cxdlznrmgp

myopnajkcxd
aoxdymgknjc
fayoxjbdclvsnm
cmjaxnoyd
adenpocymjx

gwurxpealzqfn
uqanelrwzpfxg

p
p
qgmpt
p
p

osjvfthlruqecwdgab
omqzlxkfuybce
oypfucqleibnm

jkylogfscpehwnzudbi
yvqcuehfbzwsjplniogk
cpgeosihzlbkwynjfu
ekcwtnyjsgpohfuilbz

bqoxplvhnmgs
jnmozhsdgqclb
tuhbnyoqsmgwl

pyanchrwtoqe
oenqatcphw
wpqcnetoah
nwqcapteho

wndqsh
jfgnq
pclbvk

gwav
gawv
gawv
awvg

t
zd
jfcl
t

ryhqtewijk
fnqwhjkyrie
qhjwrynki
kogrhwuixqypj

vhytdaqf
vyathqdf

vyeizmaopnglsqcxbdr
acoixrsbglqvyzujdp
bzqagplxovdcrsiy
scxizbrdvpqgolya
cylxpabuiodgsrvqz

hp
hs
rzuh
he

glxeqjf
tmufqbxiekdcj
fxslvpeqj
nzgpxjeqf
xnzjlqefh

fcwd
pxnowvtfrc
lfcw
wqgkcfd

teblqdskjwymgipvfocanzr
glbojevqktirspuydncamwfz

zftjgnpuc
zrcuqjtfn
irdutbecnz
nkcovuxzswmtlyah
ztqncdu

kdirczys
skrdzciy
dcszyirk

weytvzmidgnbxl
qdxfpkblsrouajvw

gmdupkbl
klhtgdmsbp
nbvpmdlkg
pzibclmyeodqgk
mpbxldkg

ikchnfbqgymdwpet
gkmfnhtwxiqbdcyve
mgdecfiotqknhbaw
dsmrqfnkyctighzewb
mqehgkwnscdbift

rzdnimcaxe
dceaxbmzrt
dmrecazx
zeuqxmchlrydak
rxeaczmd

nlbecfu
nuelcf
eufncl
fluenc

skoltxqicvwfbhzdupem
ilqsfyouaxvkwdcpth

gvecuatmospxl
mhbxcyskojpeluv
upfslomxcnve
pqvmluiecsox
mnpcfxzueloavts

mxquegw
esgcbif
gevrn
cykzdhge
bgzkieadl

hna
nxha

qmorc
rmcoq
mcrqo
cqorm
qrcom

tewncgarvqjdoumkb
jgwqdbcmorevutkn
eomtvngdjrbcqkuw

aeckhjmvzn
mvenkcuhazj
hzkvdejamcn
jevzhnmcak
mhejzkcavn

yvpjqszo
dtg
atg

ghczoyrkviaudbtjwne
dnbecrftkowghyuzvai
wbygucnavdktezhior

vyoq
voy
oyv
voy

um
m
m

eijf
jief
jgief
jfie
fijxde

xy
xyc
xy
yx
xy

ubcnvioqxlhm
iqzbngoclhmxu
iofwxbcmslndq

njqvmbatkxlfswizur
dqxkwlzbnmvau
vbuwmznakqlhx
unvzlxmwaqkbg

izwlbfqdh
wubacgyzrhfm

xvdzmaireyoqgfpub
rndxuczebfyipvtogma
vodgmwbxfzpeiyurja

hpdwqz
rqdhpzwn
whpdzq
qphzwd
cwqphvzd

rndgovb
gdrvobn
govndbr
vgbnord
nbvgord

ufxdk
pehaqtz
rwpiea

v
v
v

zrclgthjybdxwsnmvqi
tnwyvidqrzxlgjscmbh
isjynzrmbgwlxtpchdvq
ynqwlihbxrmztsjdcgv

q
q
q

c
c
jb
u
c

vkejfcmgwixbnolutaqphrzsdy
fqdwjngcuxviloyzkshmpteabr

rfv
r
rz
qjmrg

wzhdyp
r
gbm
aw

rsdywfzikhnlqc
kifcrndqlswzhy
hdfkiylsnqcrzw

lfhtzrxcj
fbtzlhrcj
lzdaftrjphco
'
]

{ #category : #data }
AdventOfCode2020Tests >> dataForDay07 [
	^ 'light plum bags contain 1 faded blue bag.
muted salmon bags contain 4 faded lavender bags, 4 posh magenta bags.
wavy gray bags contain 2 dotted teal bags.
wavy tan bags contain 2 plaid aqua bags.
wavy purple bags contain 1 drab white bag, 4 muted yellow bags, 2 wavy aqua bags.
dull fuchsia bags contain 2 bright indigo bags, 3 plaid cyan bags, 1 light gold bag.
striped plum bags contain 1 dull coral bag, 2 drab salmon bags.
mirrored gold bags contain 2 faded tan bags, 1 dull aqua bag.
dim blue bags contain 3 dotted gray bags, 2 mirrored turquoise bags.
dark olive bags contain 2 bright cyan bags.
dotted orange bags contain 2 pale lime bags.
vibrant aqua bags contain 5 posh plum bags, 5 faded tomato bags, 5 shiny tomato bags, 1 mirrored orange bag.
striped gray bags contain 5 drab tomato bags.
light beige bags contain 1 drab aqua bag, 5 striped yellow bags, 5 bright indigo bags.
dotted brown bags contain 5 dim tan bags, 1 dim violet bag, 2 dull turquoise bags, 3 dark olive bags.
dark turquoise bags contain 1 light bronze bag.
vibrant beige bags contain 3 wavy indigo bags, 5 striped gray bags.
dotted plum bags contain 2 mirrored green bags, 2 dull crimson bags, 2 drab tan bags, 1 vibrant coral bag.
dull indigo bags contain 2 vibrant gold bags, 1 dim chartreuse bag, 3 bright brown bags, 2 dim turquoise bags.
wavy olive bags contain 2 dotted indigo bags, 4 vibrant beige bags, 1 dotted gray bag.
posh olive bags contain 4 muted magenta bags, 5 dim cyan bags, 3 drab bronze bags, 2 pale lime bags.
dotted silver bags contain 3 light brown bags.
dim purple bags contain 5 clear lavender bags, 4 drab aqua bags, 1 mirrored bronze bag.
wavy green bags contain 4 plaid white bags, 3 clear cyan bags, 1 striped gray bag, 4 clear coral bags.
dark brown bags contain 4 light brown bags, 2 light magenta bags, 3 dotted gold bags.
dark aqua bags contain 1 dull coral bag, 4 shiny coral bags, 3 vibrant crimson bags, 2 muted black bags.
shiny gray bags contain 1 dark gray bag, 4 pale purple bags.
posh brown bags contain 1 posh magenta bag, 5 wavy bronze bags, 5 posh yellow bags.
clear turquoise bags contain 1 shiny tan bag, 1 muted salmon bag.
dotted teal bags contain 5 bright tan bags, 5 vibrant crimson bags.
drab coral bags contain 1 striped brown bag, 1 light lime bag, 1 faded green bag.
dull plum bags contain 5 vibrant silver bags.
bright orange bags contain 2 dark yellow bags, 4 mirrored silver bags, 4 mirrored cyan bags, 2 striped tomato bags.
drab bronze bags contain 2 drab violet bags, 2 striped bronze bags.
dim tan bags contain 1 shiny black bag, 5 posh aqua bags.
clear indigo bags contain 4 clear tan bags, 5 vibrant silver bags, 2 striped orange bags, 2 dotted lavender bags.
muted violet bags contain 4 mirrored white bags, 1 dim blue bag, 4 faded beige bags.
posh aqua bags contain 4 striped fuchsia bags, 4 pale red bags, 5 muted coral bags.
mirrored purple bags contain 5 dim beige bags, 5 shiny brown bags, 5 posh indigo bags, 3 clear turquoise bags.
vibrant orange bags contain 1 dark turquoise bag, 1 dotted olive bag, 3 dull coral bags, 3 dark chartreuse bags.
light tomato bags contain 4 mirrored lime bags, 3 pale beige bags, 4 clear magenta bags.
drab indigo bags contain 5 mirrored blue bags, 1 dull salmon bag.
bright red bags contain 3 pale gold bags, 5 dim fuchsia bags, 5 mirrored aqua bags, 4 shiny gold bags.
clear silver bags contain 3 dotted brown bags, 3 dull olive bags.
vibrant salmon bags contain 3 shiny tan bags, 4 dotted gray bags, 3 wavy violet bags, 5 light gray bags.
vibrant tan bags contain 1 wavy purple bag, 2 bright plum bags, 3 dim turquoise bags.
wavy maroon bags contain 4 striped fuchsia bags.
mirrored red bags contain 3 vibrant coral bags, 2 dotted crimson bags, 3 striped orange bags, 2 clear olive bags.
shiny tan bags contain 5 striped fuchsia bags, 4 drab chartreuse bags, 2 drab tomato bags, 5 muted crimson bags.
dull black bags contain 2 shiny teal bags.
shiny coral bags contain 4 posh blue bags, 1 dotted coral bag.
mirrored blue bags contain 4 posh chartreuse bags.
striped fuchsia bags contain 4 muted lime bags, 2 shiny crimson bags.
shiny lavender bags contain 1 vibrant yellow bag, 1 clear turquoise bag.
dark tomato bags contain 5 clear brown bags.
shiny indigo bags contain 3 pale orange bags.
posh fuchsia bags contain 2 vibrant blue bags, 5 striped black bags, 3 dim turquoise bags, 5 pale black bags.
muted plum bags contain 5 dim turquoise bags, 1 posh fuchsia bag.
posh tomato bags contain 1 faded yellow bag, 1 vibrant blue bag, 1 clear coral bag.
dotted gold bags contain 3 dull tomato bags, 5 striped tomato bags, 5 wavy purple bags.
striped lime bags contain 3 faded salmon bags, 1 plaid gold bag, 4 wavy aqua bags, 3 bright beige bags.
posh violet bags contain 5 dim purple bags.
mirrored chartreuse bags contain 1 dark bronze bag.
posh purple bags contain 4 posh fuchsia bags, 4 posh magenta bags, 2 mirrored cyan bags.
bright indigo bags contain 5 drab white bags, 1 posh tan bag.
dark indigo bags contain 1 clear tan bag, 2 wavy teal bags.
dark beige bags contain 1 bright olive bag, 5 posh purple bags.
clear crimson bags contain 4 muted black bags, 4 posh purple bags, 1 striped black bag, 5 bright black bags.
shiny green bags contain 2 dark orange bags, 2 bright silver bags, 3 dim orange bags.
plaid crimson bags contain 5 muted cyan bags, 3 striped orange bags, 4 dull lavender bags, 5 wavy magenta bags.
clear tomato bags contain 2 posh fuchsia bags, 2 dark orange bags, 3 pale black bags, 2 dull aqua bags.
vibrant gold bags contain 1 faded brown bag.
pale salmon bags contain 4 dull coral bags, 2 posh fuchsia bags, 2 plaid tan bags.
light cyan bags contain 4 plaid magenta bags.
dim teal bags contain 1 posh bronze bag, 4 mirrored green bags, 5 dull black bags, 1 clear gray bag.
plaid lime bags contain 3 wavy orange bags, 5 pale blue bags, 1 plaid gold bag.
light tan bags contain 4 faded crimson bags, 1 plaid fuchsia bag, 1 bright aqua bag, 2 dotted blue bags.
shiny brown bags contain 3 mirrored bronze bags, 3 light coral bags.
bright plum bags contain 3 posh gray bags, 3 faded brown bags, 3 plaid magenta bags.
bright beige bags contain 5 dotted coral bags.
drab tomato bags contain no other bags.
pale beige bags contain 3 drab bronze bags.
dotted aqua bags contain 5 plaid yellow bags.
striped yellow bags contain 2 dull tan bags, 2 posh violet bags, 2 pale violet bags, 2 clear lavender bags.
vibrant maroon bags contain 4 muted green bags, 1 muted cyan bag, 1 mirrored tomato bag.
plaid green bags contain 2 dotted black bags.
dotted indigo bags contain 5 mirrored tan bags, 3 dim yellow bags.
vibrant coral bags contain 3 drab blue bags, 3 striped gray bags, 1 clear plum bag, 2 faded tomato bags.
pale maroon bags contain 5 shiny black bags.
posh black bags contain 2 posh green bags, 1 posh tomato bag, 4 dim gold bags, 5 wavy olive bags.
wavy aqua bags contain 5 faded green bags, 4 pale lavender bags, 5 plaid aqua bags, 3 mirrored brown bags.
clear green bags contain 3 pale lime bags.
dim beige bags contain 4 vibrant beige bags, 3 dull aqua bags, 1 mirrored orange bag, 2 dim yellow bags.
dim chartreuse bags contain 5 dark maroon bags, 1 dark crimson bag, 5 wavy teal bags, 3 clear aqua bags.
bright turquoise bags contain 1 dim turquoise bag, 3 dull turquoise bags.
bright magenta bags contain 2 striped fuchsia bags, 5 dim brown bags.
light fuchsia bags contain 2 drab tomato bags, 5 dim chartreuse bags.
vibrant magenta bags contain 2 pale red bags, 4 dim turquoise bags, 4 drab blue bags, 3 drab aqua bags.
muted gold bags contain 3 pale gray bags, 4 dim salmon bags.
vibrant violet bags contain 4 mirrored gray bags, 2 wavy aqua bags, 3 drab tan bags.
wavy cyan bags contain 3 pale fuchsia bags, 1 mirrored tan bag, 2 dull blue bags, 2 dull cyan bags.
light silver bags contain 2 faded brown bags, 3 mirrored white bags, 5 plaid maroon bags, 3 plaid plum bags.
mirrored lavender bags contain 1 shiny tan bag, 2 dim turquoise bags, 1 shiny coral bag, 1 striped brown bag.
dull teal bags contain 2 striped purple bags, 5 dark plum bags, 5 bright purple bags, 4 light bronze bags.
light indigo bags contain no other bags.
shiny silver bags contain 2 dim maroon bags.
wavy brown bags contain 1 posh lavender bag, 2 dark bronze bags, 4 mirrored chartreuse bags.
dull lavender bags contain 3 dull cyan bags, 1 drab lavender bag.
posh gold bags contain 1 mirrored cyan bag, 5 bright salmon bags, 4 dotted orange bags.
dim yellow bags contain no other bags.
vibrant crimson bags contain 1 drab lavender bag, 4 wavy purple bags, 5 clear red bags, 4 posh gray bags.
plaid gold bags contain 4 striped fuchsia bags, 5 drab tomato bags, 3 light indigo bags, 3 mirrored bronze bags.
vibrant indigo bags contain 4 faded yellow bags, 4 clear salmon bags, 4 plaid lavender bags.
dark crimson bags contain 1 posh fuchsia bag, 2 drab silver bags, 5 shiny coral bags.
vibrant white bags contain 3 dim orange bags, 2 shiny tomato bags, 5 dark teal bags, 5 faded aqua bags.
pale chartreuse bags contain 2 dim cyan bags, 2 faded red bags, 3 light yellow bags, 4 wavy yellow bags.
drab chartreuse bags contain 2 pale black bags.
drab gray bags contain 4 posh indigo bags, 3 muted maroon bags, 5 striped teal bags, 5 striped lime bags.
dim tomato bags contain 4 plaid tan bags, 4 vibrant turquoise bags, 2 mirrored salmon bags, 2 dull magenta bags.
plaid purple bags contain 3 posh blue bags.
dark lavender bags contain 4 muted green bags, 2 dim crimson bags, 5 dull gray bags.
bright maroon bags contain 5 drab tomato bags, 4 vibrant red bags, 5 light lime bags.
striped chartreuse bags contain 5 striped black bags.
dull salmon bags contain 3 drab lime bags, 5 wavy crimson bags.
clear beige bags contain 4 dim orange bags.
light orange bags contain 1 plaid gold bag, 5 shiny coral bags.
faded red bags contain 3 bright tan bags.
wavy violet bags contain 5 plaid chartreuse bags.
dim violet bags contain 1 pale lavender bag.
posh indigo bags contain 4 muted plum bags, 1 plaid cyan bag, 2 mirrored turquoise bags, 2 light teal bags.
muted aqua bags contain 5 striped black bags, 4 wavy purple bags, 4 mirrored silver bags, 4 wavy bronze bags.
faded gold bags contain 5 wavy indigo bags, 2 dark olive bags, 5 mirrored orange bags.
bright teal bags contain 5 dotted coral bags, 4 clear lavender bags, 1 pale black bag, 5 light indigo bags.
dotted green bags contain 3 dotted brown bags, 1 mirrored chartreuse bag, 5 vibrant gray bags, 2 mirrored tan bags.
drab yellow bags contain 1 wavy maroon bag, 4 posh chartreuse bags.
dull maroon bags contain 1 dotted blue bag, 4 pale chartreuse bags, 5 drab teal bags.
clear black bags contain 3 pale magenta bags, 5 vibrant silver bags.
dull orange bags contain 4 vibrant lime bags, 4 shiny gold bags, 4 light coral bags, 4 striped brown bags.
clear violet bags contain 3 muted plum bags, 3 dim teal bags.
muted bronze bags contain 5 mirrored salmon bags, 5 dim tan bags.
plaid lavender bags contain 3 posh violet bags.
muted brown bags contain 5 striped brown bags, 5 mirrored green bags, 2 light orange bags.
clear chartreuse bags contain 2 muted lime bags.
shiny chartreuse bags contain 1 wavy coral bag, 4 light salmon bags, 5 plaid cyan bags.
clear tan bags contain 4 dotted black bags.
dull tan bags contain 1 posh maroon bag, 1 dotted coral bag.
wavy black bags contain 1 dull chartreuse bag, 3 drab plum bags.
faded fuchsia bags contain 4 mirrored violet bags, 2 dim lavender bags.
pale brown bags contain 1 dotted olive bag, 2 bright fuchsia bags.
faded green bags contain 5 dim turquoise bags, 2 mirrored blue bags, 1 mirrored tan bag, 5 mirrored silver bags.
clear brown bags contain 3 vibrant lime bags, 2 muted maroon bags, 3 dull coral bags, 3 faded plum bags.
vibrant silver bags contain 2 clear coral bags, 1 muted yellow bag, 2 drab cyan bags, 4 mirrored orange bags.
bright crimson bags contain 1 posh olive bag, 3 faded beige bags, 1 dim black bag, 1 shiny silver bag.
dim gold bags contain 2 posh beige bags, 1 dull coral bag, 1 plaid aqua bag.
drab white bags contain 1 dim yellow bag, 2 posh gray bags.
dim indigo bags contain 3 shiny brown bags, 1 drab red bag, 2 pale aqua bags, 4 plaid lime bags.
dull blue bags contain 2 pale fuchsia bags, 1 faded tomato bag, 4 plaid aqua bags.
mirrored bronze bags contain 5 bright tan bags, 2 plaid magenta bags.
vibrant turquoise bags contain 5 shiny brown bags, 2 vibrant beige bags, 2 dotted magenta bags, 3 dull lavender bags.
dull turquoise bags contain 4 clear lavender bags, 3 striped gray bags, 3 posh gray bags.
dim lavender bags contain 3 plaid lime bags, 4 mirrored red bags, 3 pale orange bags.
clear lime bags contain 3 drab fuchsia bags, 3 plaid gray bags, 1 light beige bag, 3 muted violet bags.
wavy fuchsia bags contain 3 bright gray bags, 1 faded purple bag, 4 posh purple bags, 4 light tan bags.
plaid beige bags contain 2 drab bronze bags.
faded beige bags contain 1 posh bronze bag, 3 mirrored bronze bags, 3 shiny black bags.
posh blue bags contain 3 shiny gold bags, 2 shiny black bags.
dull silver bags contain 2 wavy crimson bags, 5 faded black bags.
pale fuchsia bags contain 5 dull black bags.
bright green bags contain 3 bright black bags, 4 drab tan bags.
mirrored violet bags contain 4 pale teal bags, 3 dotted crimson bags, 2 posh violet bags, 2 shiny silver bags.
pale violet bags contain 4 posh magenta bags, 5 wavy crimson bags, 3 drab aqua bags.
faded white bags contain 1 drab purple bag, 5 shiny chartreuse bags.
faded tomato bags contain 2 bright teal bags.
faded violet bags contain 2 plaid salmon bags.
drab turquoise bags contain 1 mirrored green bag.
mirrored silver bags contain 5 dull aqua bags, 1 dark orange bag, 3 pale red bags, 4 dim yellow bags.
dotted violet bags contain 5 plaid chartreuse bags, 1 mirrored tan bag, 5 dotted lavender bags.
plaid olive bags contain 1 mirrored cyan bag, 2 muted orange bags, 2 posh maroon bags.
pale silver bags contain 3 dull lavender bags, 4 mirrored olive bags, 4 muted coral bags.
mirrored coral bags contain 1 pale fuchsia bag, 1 dull turquoise bag.
drab crimson bags contain 1 wavy purple bag, 1 wavy violet bag, 2 vibrant gold bags, 3 bright salmon bags.
dull chartreuse bags contain 4 faded salmon bags, 3 light lime bags, 1 mirrored brown bag.
bright purple bags contain 2 light cyan bags.
dull brown bags contain 3 bright white bags.
muted magenta bags contain 3 shiny gold bags, 4 muted plum bags, 5 pale lime bags, 2 light cyan bags.
pale aqua bags contain 4 drab blue bags, 1 bright lavender bag.
drab purple bags contain 2 mirrored bronze bags, 1 drab violet bag.
dotted chartreuse bags contain 2 pale chartreuse bags, 5 clear beige bags.
shiny purple bags contain 5 clear black bags.
muted blue bags contain 4 dotted indigo bags.
striped blue bags contain 4 vibrant beige bags, 3 plaid lime bags.
dull gold bags contain 4 drab violet bags, 3 pale aqua bags, 3 mirrored cyan bags.
plaid tan bags contain 5 shiny gold bags.
mirrored brown bags contain 3 pale lime bags, 2 dull coral bags.
mirrored white bags contain 5 muted black bags, 1 dark yellow bag, 4 drab blue bags, 4 clear bronze bags.
pale yellow bags contain 4 clear tomato bags, 1 drab salmon bag, 1 plaid crimson bag.
faded silver bags contain 5 dotted indigo bags, 3 posh chartreuse bags.
mirrored orange bags contain 4 drab tomato bags.
dotted lime bags contain 3 faded tomato bags, 4 vibrant beige bags, 5 posh chartreuse bags.
muted coral bags contain 1 muted plum bag.
bright tomato bags contain 1 posh red bag, 4 light red bags, 1 dotted fuchsia bag, 4 dull turquoise bags.
plaid orange bags contain 4 shiny salmon bags, 4 muted tomato bags, 4 dull gold bags, 3 clear green bags.
plaid teal bags contain 1 shiny black bag, 4 wavy purple bags, 3 dark plum bags, 4 pale silver bags.
muted tan bags contain 5 faded salmon bags, 4 dotted magenta bags, 3 clear gold bags, 3 dotted tan bags.
faded olive bags contain 1 clear lavender bag.
muted olive bags contain 4 drab coral bags, 5 light yellow bags.
posh salmon bags contain 3 dim turquoise bags, 1 vibrant purple bag, 2 bright maroon bags, 2 drab lime bags.
dim crimson bags contain 5 dull white bags, 1 dim yellow bag, 5 dark green bags.
light brown bags contain 1 drab tan bag.
light bronze bags contain 2 vibrant silver bags, 1 muted plum bag, 3 drab blue bags, 5 dull yellow bags.
faded lime bags contain 3 bright teal bags, 2 light aqua bags.
clear gold bags contain 1 dim cyan bag, 3 striped brown bags.
clear coral bags contain 4 mirrored bronze bags, 5 posh magenta bags, 5 striped purple bags.
striped cyan bags contain 1 wavy violet bag, 4 drab yellow bags.
bright coral bags contain 4 dotted lime bags, 3 striped chartreuse bags.
faded bronze bags contain 1 vibrant beige bag, 4 dotted green bags, 4 dotted gold bags, 1 shiny turquoise bag.
dark red bags contain 3 pale salmon bags, 5 bright green bags.
posh cyan bags contain 3 plaid fuchsia bags.
clear teal bags contain 5 plaid aqua bags, 1 posh tomato bag, 2 shiny olive bags, 4 shiny turquoise bags.
dotted turquoise bags contain 5 dim blue bags, 5 bright teal bags, 2 dull coral bags.
wavy silver bags contain 5 posh aqua bags.
shiny cyan bags contain 5 clear crimson bags, 4 vibrant purple bags, 3 mirrored turquoise bags, 5 plaid aqua bags.
mirrored beige bags contain 2 dim green bags, 1 dull teal bag.
plaid turquoise bags contain 1 dark yellow bag.
dim white bags contain 5 posh indigo bags, 4 bright cyan bags, 5 dim orange bags, 2 dim teal bags.
faded tan bags contain 4 dim salmon bags, 2 plaid blue bags.
faded yellow bags contain 1 posh gray bag, 4 dim beige bags.
dull tomato bags contain 2 pale indigo bags, 2 striped bronze bags, 1 wavy maroon bag, 5 posh tomato bags.
posh lavender bags contain 4 faded blue bags, 4 striped teal bags, 5 plaid chartreuse bags.
mirrored magenta bags contain 2 dim magenta bags.
drab violet bags contain 3 shiny black bags, 1 mirrored silver bag.
pale coral bags contain 5 dim gold bags.
clear red bags contain 4 muted maroon bags.
dark yellow bags contain 5 striped black bags, 2 clear plum bags.
dull coral bags contain 5 bright teal bags, 2 shiny black bags, 3 drab tomato bags, 4 dotted coral bags.
dotted bronze bags contain 3 bright black bags, 3 dull orange bags, 3 mirrored indigo bags.
dull green bags contain 4 clear teal bags, 5 muted silver bags, 2 pale blue bags, 2 light plum bags.
wavy gold bags contain 5 pale red bags, 3 dim salmon bags, 2 striped orange bags, 4 bright beige bags.
plaid aqua bags contain 4 pale black bags, 2 clear tomato bags, 1 faded beige bag.
wavy tomato bags contain 5 posh turquoise bags.
wavy white bags contain 2 dim maroon bags.
dull beige bags contain 3 wavy brown bags.
light olive bags contain 5 dim white bags, 4 dark fuchsia bags, 4 dull magenta bags, 5 light lavender bags.
mirrored lime bags contain 5 vibrant coral bags.
light black bags contain 2 dark salmon bags.
bright gold bags contain 3 dark orange bags, 5 shiny black bags, 2 bright silver bags, 3 pale black bags.
dull lime bags contain 2 posh bronze bags, 2 mirrored blue bags.
posh chartreuse bags contain 3 light lime bags, 3 bright lavender bags, 3 posh fuchsia bags.
clear orange bags contain 1 dull maroon bag, 1 faded yellow bag.
striped red bags contain 2 dotted cyan bags, 3 dull silver bags, 2 light blue bags.
pale turquoise bags contain 4 wavy silver bags, 3 dotted teal bags, 4 light green bags.
wavy crimson bags contain 1 light cyan bag, 2 posh beige bags.
light turquoise bags contain 1 dull orange bag.
dotted coral bags contain 1 drab tomato bag, 5 dim yellow bags, 5 bright lavender bags.
dotted tan bags contain 4 light coral bags, 4 dim cyan bags, 3 vibrant beige bags.
drab blue bags contain 1 dim turquoise bag.
pale white bags contain 3 clear olive bags, 2 clear coral bags, 5 dark olive bags, 2 wavy white bags.
muted orange bags contain 2 dim gold bags.
faded black bags contain 2 wavy aqua bags, 5 vibrant bronze bags, 5 mirrored blue bags.
posh lime bags contain 2 dim salmon bags, 2 pale orange bags, 4 wavy maroon bags, 1 dim coral bag.
wavy indigo bags contain 2 muted lime bags.
faded orange bags contain 1 light green bag, 5 plaid turquoise bags, 4 posh turquoise bags.
light blue bags contain 1 plaid fuchsia bag, 4 mirrored salmon bags, 1 muted chartreuse bag.
light violet bags contain 3 dotted black bags, 3 posh black bags.
posh bronze bags contain 3 striped purple bags, 5 posh purple bags, 2 plaid magenta bags, 3 dull aqua bags.
shiny fuchsia bags contain 5 dim olive bags, 2 plaid silver bags, 1 dark cyan bag, 1 pale red bag.
vibrant gray bags contain 2 drab blue bags.
faded salmon bags contain 1 drab aqua bag, 1 mirrored blue bag.
dark white bags contain 4 dim orange bags, 4 plaid magenta bags, 2 clear tomato bags.
muted indigo bags contain 4 dotted violet bags.
dull white bags contain 2 shiny cyan bags, 3 shiny orange bags.
faded plum bags contain 3 dim cyan bags, 2 dark yellow bags.
muted silver bags contain 2 drab red bags, 3 dark gray bags, 4 striped teal bags.
wavy lavender bags contain 1 drab turquoise bag.
striped beige bags contain 2 dim turquoise bags, 1 muted plum bag, 4 posh violet bags.
dark gray bags contain 3 posh fuchsia bags, 2 striped brown bags.
plaid yellow bags contain 3 vibrant red bags, 5 dark gold bags.
dark violet bags contain 2 mirrored orange bags, 2 muted crimson bags, 1 pale white bag, 1 pale chartreuse bag.
shiny maroon bags contain 4 dim tan bags.
dotted fuchsia bags contain 4 bright lime bags, 3 dotted lime bags, 2 bright maroon bags, 5 drab yellow bags.
light yellow bags contain 1 dotted coral bag, 1 bright lavender bag, 3 pale violet bags.
shiny blue bags contain 1 shiny crimson bag.
dotted black bags contain 4 muted aqua bags, 2 light lime bags, 3 posh turquoise bags, 1 light silver bag.
pale purple bags contain 2 striped violet bags, 5 clear lavender bags.
pale red bags contain 4 bright tan bags, 4 pale black bags, 4 mirrored cyan bags, 3 dotted coral bags.
dim gray bags contain 3 dull cyan bags, 3 dotted purple bags, 2 shiny brown bags, 2 plaid tan bags.
posh tan bags contain 2 light coral bags, 2 bright black bags, 2 dim yellow bags.
vibrant black bags contain 4 pale crimson bags, 2 mirrored brown bags, 4 plaid violet bags, 3 muted yellow bags.
dark salmon bags contain 2 mirrored brown bags, 5 clear salmon bags, 5 drab yellow bags.
dim green bags contain 5 pale indigo bags, 5 pale coral bags, 5 plaid lavender bags.
plaid fuchsia bags contain 2 muted maroon bags, 3 muted crimson bags, 3 dim black bags.
faded maroon bags contain 3 mirrored purple bags, 5 faded tan bags.
dark maroon bags contain 5 dull lavender bags, 4 clear plum bags, 3 shiny silver bags.
pale magenta bags contain 1 light indigo bag.
dim salmon bags contain 2 vibrant red bags, 1 light lime bag.
dotted lavender bags contain 4 drab tan bags, 1 mirrored olive bag, 5 plaid gold bags.
faded aqua bags contain 5 dim purple bags.
plaid brown bags contain 2 shiny green bags, 3 faded tomato bags, 4 wavy orange bags.
striped purple bags contain 4 posh gray bags, 1 light lime bag.
muted yellow bags contain 2 pale indigo bags, 3 vibrant blue bags, 2 muted coral bags.
dark gold bags contain 4 striped teal bags, 4 bright maroon bags.
mirrored indigo bags contain 5 dim white bags, 4 wavy white bags, 4 bright purple bags.
mirrored tomato bags contain 1 drab turquoise bag, 1 drab cyan bag, 1 dotted teal bag.
striped white bags contain 1 shiny silver bag, 1 faded gold bag.
pale plum bags contain 2 shiny brown bags, 1 posh fuchsia bag.
bright gray bags contain 4 posh chartreuse bags, 4 dull turquoise bags.
shiny olive bags contain 3 plaid yellow bags, 4 dotted fuchsia bags, 2 bright beige bags.
faded crimson bags contain 4 faded blue bags, 5 faded gray bags, 1 dotted lime bag, 1 wavy magenta bag.
striped coral bags contain 1 dull fuchsia bag, 4 striped fuchsia bags, 1 dull gold bag, 5 posh lime bags.
posh orange bags contain 4 dim yellow bags, 2 posh tan bags.
striped tan bags contain 5 vibrant coral bags, 5 posh violet bags, 4 plaid aqua bags, 4 dark crimson bags.
shiny yellow bags contain 3 dull silver bags, 3 dim purple bags, 3 vibrant violet bags.
shiny black bags contain 3 mirrored cyan bags, 1 clear gray bag, 2 light cyan bags.
posh silver bags contain 1 posh blue bag.
mirrored cyan bags contain 5 pale lime bags, 1 drab aqua bag, 4 muted lime bags.
dark plum bags contain 3 muted green bags.
clear white bags contain 5 wavy crimson bags, 3 plaid salmon bags, 4 plaid silver bags, 3 faded beige bags.
plaid plum bags contain 2 dim salmon bags, 1 faded black bag, 2 plaid purple bags, 5 dull lavender bags.
dim turquoise bags contain 2 pale indigo bags, 4 striped black bags.
vibrant green bags contain 5 clear purple bags, 4 pale brown bags, 2 drab olive bags, 3 dotted brown bags.
dark lime bags contain 4 dull blue bags, 4 wavy chartreuse bags, 1 bright olive bag.
shiny white bags contain 2 muted magenta bags, 4 clear gray bags, 1 mirrored bronze bag, 3 mirrored green bags.
dark orange bags contain 5 clear gray bags, 1 posh maroon bag, 1 vibrant blue bag.
light crimson bags contain 2 drab tomato bags, 5 bright tan bags, 5 striped gray bags.
clear yellow bags contain 2 muted salmon bags, 1 mirrored magenta bag.
plaid salmon bags contain 3 drab tan bags, 4 dark yellow bags, 5 dim yellow bags.
faded chartreuse bags contain 1 dull black bag, 5 pale lime bags, 2 wavy olive bags, 4 shiny green bags.
plaid bronze bags contain 2 vibrant maroon bags.
striped crimson bags contain 1 shiny beige bag.
clear magenta bags contain 3 muted olive bags, 4 bright olive bags, 5 pale purple bags, 3 dark aqua bags.
muted lime bags contain no other bags.
dull yellow bags contain 3 dark black bags, 1 wavy orange bag, 5 posh fuchsia bags.
shiny teal bags contain 5 posh bronze bags, 1 striped tomato bag, 2 dim gold bags, 2 posh chartreuse bags.
plaid violet bags contain 5 mirrored bronze bags, 5 shiny crimson bags, 5 vibrant blue bags.
posh coral bags contain 5 bright silver bags, 2 bright lime bags.
dim magenta bags contain 5 drab white bags, 1 faded blue bag, 1 drab red bag, 5 light brown bags.
muted turquoise bags contain 4 shiny beige bags.
posh maroon bags contain 2 light lime bags.
posh crimson bags contain 5 wavy lavender bags, 3 pale orange bags, 3 plaid magenta bags.
striped black bags contain no other bags.
drab teal bags contain 5 light olive bags, 3 clear teal bags, 2 posh magenta bags.
plaid white bags contain 1 shiny tan bag, 3 dotted lavender bags, 5 wavy olive bags, 4 clear black bags.
pale olive bags contain 4 vibrant beige bags.
shiny tomato bags contain 5 pale lavender bags, 3 muted fuchsia bags, 5 drab white bags.
dim coral bags contain 3 dotted fuchsia bags.
faded blue bags contain 4 dim maroon bags, 3 vibrant blue bags, 4 clear gray bags.
plaid maroon bags contain 3 dotted indigo bags, 1 mirrored olive bag.
mirrored teal bags contain 3 dim olive bags, 5 posh white bags, 4 faded plum bags.
mirrored olive bags contain 5 light indigo bags, 5 muted lime bags, 4 wavy indigo bags.
drab aqua bags contain 4 drab tan bags, 2 striped gray bags, 1 pale lime bag.
posh plum bags contain 5 dim magenta bags, 5 clear gray bags.
dull olive bags contain 1 clear black bag, 3 dim brown bags.
bright chartreuse bags contain 5 vibrant violet bags, 4 posh green bags, 5 pale coral bags.
dull bronze bags contain 3 dark green bags.
plaid silver bags contain 4 striped lavender bags, 3 mirrored orange bags, 5 muted coral bags.
mirrored fuchsia bags contain 1 vibrant crimson bag.
drab beige bags contain 4 light indigo bags, 1 shiny green bag.
plaid chartreuse bags contain 2 dark bronze bags, 5 drab chartreuse bags.
drab magenta bags contain 3 plaid chartreuse bags.
pale black bags contain no other bags.
dark fuchsia bags contain 1 dim yellow bag, 5 dim salmon bags.
clear gray bags contain 3 bright tan bags.
dark purple bags contain 4 plaid purple bags, 1 dark gold bag.
bright tan bags contain no other bags.
clear plum bags contain 1 posh blue bag, 4 bright teal bags.
striped brown bags contain 5 clear tomato bags, 1 dotted indigo bag, 2 clear coral bags.
drab silver bags contain 3 clear lavender bags, 3 shiny gold bags, 5 dotted coral bags, 5 wavy indigo bags.
dotted purple bags contain 2 mirrored bronze bags, 4 light red bags, 4 dim teal bags, 3 muted indigo bags.
dotted red bags contain 2 shiny brown bags, 2 dull tan bags, 3 wavy coral bags, 2 pale lime bags.
posh magenta bags contain 3 clear gray bags.
dim olive bags contain 4 muted cyan bags, 2 mirrored brown bags, 3 dim orange bags.
dotted tomato bags contain 2 bright fuchsia bags, 5 dull silver bags, 2 dim lime bags.
striped magenta bags contain 3 mirrored red bags, 1 muted magenta bag, 3 wavy white bags.
posh red bags contain 3 bright orange bags, 4 clear olive bags, 5 faded violet bags, 3 plaid coral bags.
muted crimson bags contain 5 light indigo bags.
drab fuchsia bags contain 3 shiny coral bags.
light lime bags contain 4 bright lavender bags, 2 light crimson bags, 5 vibrant blue bags.
dotted yellow bags contain 4 pale fuchsia bags.
bright lavender bags contain no other bags.
dull aqua bags contain 4 posh gray bags, 2 light indigo bags, 5 light crimson bags.
shiny aqua bags contain 2 pale orange bags, 3 drab gray bags.
drab red bags contain 5 striped tomato bags.
bright salmon bags contain 3 light indigo bags.
faded turquoise bags contain 5 clear beige bags.
shiny gold bags contain 1 mirrored bronze bag, 4 dull aqua bags, 2 dotted indigo bags, 1 light indigo bag.
clear fuchsia bags contain 5 dotted indigo bags.
dark bronze bags contain 4 shiny black bags.
dotted olive bags contain 4 bright cyan bags.
vibrant purple bags contain 3 striped gray bags.
dull purple bags contain 5 wavy orange bags, 5 faded black bags, 2 plaid violet bags, 2 vibrant lavender bags.
shiny lime bags contain 1 light purple bag.
pale cyan bags contain 3 vibrant red bags, 5 dark white bags, 4 mirrored red bags, 3 vibrant brown bags.
dark cyan bags contain 5 clear olive bags, 4 plaid purple bags, 5 striped teal bags, 3 bright magenta bags.
dim lime bags contain 3 muted tomato bags.
drab olive bags contain 1 dotted blue bag, 2 dull lavender bags.
faded gray bags contain 5 mirrored tan bags, 1 muted orange bag, 3 posh purple bags.
muted gray bags contain 5 pale white bags.
mirrored yellow bags contain 5 bright black bags, 1 plaid turquoise bag.
wavy lime bags contain 5 plaid bronze bags, 4 mirrored green bags, 5 pale lavender bags, 3 wavy tan bags.
wavy orange bags contain 3 dotted lime bags, 1 dull crimson bag, 2 mirrored turquoise bags.
dotted cyan bags contain 4 dotted lime bags, 2 striped teal bags.
light green bags contain 3 muted indigo bags, 3 pale fuchsia bags.
drab cyan bags contain 3 posh bronze bags, 5 drab white bags, 3 drab tomato bags, 1 light indigo bag.
faded brown bags contain 3 bright tan bags, 4 striped gray bags, 5 drab cyan bags, 3 mirrored tan bags.
light purple bags contain 3 pale aqua bags, 1 dim olive bag, 2 dim tan bags.
vibrant lavender bags contain 2 faded lavender bags.
vibrant brown bags contain 4 striped black bags, 1 faded yellow bag.
dull crimson bags contain 2 mirrored white bags, 2 clear tomato bags.
drab green bags contain 2 drab beige bags, 1 vibrant crimson bag, 2 vibrant purple bags, 1 faded black bag.
shiny bronze bags contain 3 dark fuchsia bags, 3 dark bronze bags, 2 striped brown bags, 4 shiny brown bags.
plaid blue bags contain 5 faded green bags.
light white bags contain 3 wavy brown bags, 3 dark violet bags, 2 muted coral bags, 5 plaid chartreuse bags.
bright violet bags contain 1 faded violet bag, 2 muted maroon bags, 3 posh gray bags, 2 dark salmon bags.
striped turquoise bags contain 5 bright salmon bags, 1 bright lavender bag, 1 wavy maroon bag, 4 light turquoise bags.
clear cyan bags contain 5 posh magenta bags, 4 striped plum bags, 5 light turquoise bags.
bright silver bags contain 4 dotted indigo bags, 1 drab tomato bag, 1 muted salmon bag.
mirrored plum bags contain 5 bright white bags, 1 vibrant brown bag.
mirrored aqua bags contain 5 drab bronze bags, 3 mirrored salmon bags, 3 posh lavender bags, 3 bright crimson bags.
muted lavender bags contain 4 posh bronze bags, 3 striped lime bags, 5 striped chartreuse bags, 5 plaid plum bags.
dim orange bags contain 3 muted magenta bags, 2 pale magenta bags.
faded teal bags contain 5 wavy coral bags, 3 posh blue bags.
dotted magenta bags contain 5 faded purple bags, 5 posh fuchsia bags, 1 drab white bag.
drab brown bags contain 4 light red bags, 4 muted chartreuse bags.
striped indigo bags contain 3 light maroon bags, 2 pale gray bags, 2 faded magenta bags, 1 vibrant teal bag.
dull gray bags contain 3 clear olive bags.
clear blue bags contain 2 clear tomato bags, 4 faded purple bags, 1 wavy lavender bag.
posh green bags contain 5 clear aqua bags, 4 bright orange bags, 2 bright cyan bags, 4 dim fuchsia bags.
muted fuchsia bags contain 5 dull lavender bags, 2 drab violet bags, 4 dotted magenta bags, 2 wavy yellow bags.
posh turquoise bags contain 2 dotted lavender bags.
bright blue bags contain 1 pale lavender bag, 5 dark yellow bags, 5 bright beige bags.
bright bronze bags contain 2 bright gold bags, 4 shiny turquoise bags.
muted chartreuse bags contain 1 vibrant tomato bag, 1 bright lavender bag, 1 vibrant blue bag, 1 dim black bag.
dim bronze bags contain 2 light lavender bags, 2 striped plum bags, 3 dotted gold bags.
pale crimson bags contain 5 dotted lavender bags, 2 clear crimson bags, 4 bright lime bags.
clear bronze bags contain 2 drab tomato bags, 3 vibrant red bags.
pale lime bags contain 4 pale indigo bags, 3 striped black bags.
light red bags contain 4 bright salmon bags, 1 bright gold bag.
pale orange bags contain 5 drab blue bags.
shiny crimson bags contain 3 light crimson bags.
dotted beige bags contain 5 bright turquoise bags, 3 dotted turquoise bags, 4 muted green bags, 4 light black bags.
light gray bags contain 4 faded green bags, 5 wavy gold bags, 4 dim olive bags.
light coral bags contain 2 muted plum bags.
light magenta bags contain 1 dim maroon bag, 5 clear chartreuse bags, 1 vibrant lavender bag, 2 plaid beige bags.
striped violet bags contain 1 vibrant beige bag.
bright aqua bags contain 1 dark crimson bag, 4 dark bronze bags.
dotted maroon bags contain 5 light silver bags, 5 dark maroon bags.
drab plum bags contain 1 dotted yellow bag, 1 bright green bag, 4 vibrant brown bags.
posh gray bags contain 2 light crimson bags.
dotted blue bags contain 2 posh tan bags.
vibrant olive bags contain 3 faded yellow bags.
posh white bags contain 1 faded tomato bag, 2 dim violet bags.
drab lavender bags contain 3 light brown bags.
dark blue bags contain 5 vibrant lavender bags, 4 posh plum bags, 5 pale violet bags, 1 pale beige bag.
muted beige bags contain 1 striped lime bag, 2 clear purple bags, 1 vibrant brown bag, 2 mirrored bronze bags.
dim maroon bags contain 5 dim beige bags, 1 dull coral bag.
wavy teal bags contain 1 drab yellow bag, 2 muted magenta bags, 4 wavy gold bags, 2 vibrant cyan bags.
shiny salmon bags contain 2 light red bags, 3 bright fuchsia bags.
light salmon bags contain 3 vibrant purple bags, 3 drab blue bags, 3 faded black bags, 2 bright white bags.
shiny magenta bags contain 5 light fuchsia bags, 3 drab indigo bags, 3 mirrored yellow bags, 4 dim purple bags.
plaid black bags contain 3 light bronze bags, 4 mirrored tan bags, 4 muted lime bags, 5 mirrored white bags.
wavy red bags contain 4 clear lavender bags, 4 dull chartreuse bags.
posh beige bags contain 4 wavy maroon bags, 4 clear plum bags.
wavy bronze bags contain 1 wavy purple bag.
dotted gray bags contain 3 striped black bags, 1 wavy maroon bag, 5 pale indigo bags.
bright white bags contain 3 pale indigo bags, 2 drab white bags.
mirrored black bags contain 2 striped plum bags, 5 wavy brown bags, 1 wavy crimson bag.
light gold bags contain 3 posh plum bags, 1 vibrant crimson bag.
bright fuchsia bags contain 3 light cyan bags, 1 drab turquoise bag, 3 dim orange bags, 1 dull chartreuse bag.
striped gold bags contain 3 muted violet bags, 2 clear teal bags, 2 posh brown bags, 3 dim tan bags.
striped orange bags contain 1 pale fuchsia bag.
drab gold bags contain 4 shiny teal bags, 5 muted aqua bags, 3 wavy lavender bags.
light chartreuse bags contain 2 bright gold bags, 5 striped turquoise bags, 5 light gray bags, 3 wavy aqua bags.
vibrant chartreuse bags contain 2 dotted yellow bags, 5 bright fuchsia bags, 1 striped chartreuse bag, 1 dim salmon bag.
pale indigo bags contain no other bags.
drab lime bags contain 2 mirrored turquoise bags.
vibrant plum bags contain 3 dotted turquoise bags.
pale teal bags contain 5 striped lime bags, 3 faded salmon bags, 4 bright indigo bags.
dark tan bags contain 2 drab lavender bags.
faded lavender bags contain 1 vibrant blue bag.
drab orange bags contain 1 muted turquoise bag, 3 pale indigo bags.
dim fuchsia bags contain 1 drab silver bag.
vibrant lime bags contain 1 posh purple bag, 3 light coral bags, 3 light lime bags, 4 light indigo bags.
clear salmon bags contain 2 light indigo bags, 2 striped plum bags.
dark black bags contain 2 striped fuchsia bags, 4 wavy white bags, 2 wavy maroon bags.
muted white bags contain 2 pale indigo bags, 5 light plum bags.
pale gray bags contain 4 light yellow bags, 2 striped olive bags, 4 clear black bags.
dull cyan bags contain 2 vibrant red bags, 3 drab tan bags.
striped silver bags contain 3 mirrored green bags, 2 wavy purple bags, 3 posh aqua bags.
wavy magenta bags contain 4 dim purple bags, 2 dark aqua bags.
drab black bags contain 2 light plum bags.
drab maroon bags contain 2 vibrant lime bags, 4 dull purple bags, 2 mirrored salmon bags, 3 vibrant aqua bags.
shiny orange bags contain 5 wavy coral bags, 1 pale violet bag.
plaid coral bags contain 2 mirrored cyan bags.
plaid cyan bags contain 4 pale indigo bags.
dotted crimson bags contain 2 dim teal bags.
mirrored tan bags contain 1 pale red bag, 1 light cyan bag, 1 clear gray bag, 3 striped gray bags.
light maroon bags contain 2 vibrant bronze bags.
bright brown bags contain 2 wavy yellow bags.
muted tomato bags contain 5 clear gold bags, 5 plaid coral bags.
dotted white bags contain 4 dotted purple bags, 1 posh chartreuse bag, 5 dark gold bags, 1 vibrant gold bag.
muted red bags contain 4 clear crimson bags, 4 posh magenta bags, 3 plaid cyan bags, 5 pale crimson bags.
wavy yellow bags contain 3 muted magenta bags.
muted purple bags contain 1 dull chartreuse bag.
striped olive bags contain 5 faded tomato bags.
light aqua bags contain 1 vibrant tomato bag, 4 posh lavender bags.
vibrant blue bags contain 2 muted lime bags.
pale lavender bags contain 4 shiny coral bags, 5 muted crimson bags.
mirrored turquoise bags contain 5 posh blue bags.
pale gold bags contain 3 plaid chartreuse bags, 2 pale red bags, 5 clear aqua bags.
wavy salmon bags contain 4 dotted yellow bags.
shiny beige bags contain 1 bright magenta bag, 1 muted fuchsia bag.
striped bronze bags contain 5 bright turquoise bags, 5 dull black bags.
dark magenta bags contain 5 drab lime bags.
dark coral bags contain 3 plaid bronze bags, 3 posh green bags, 4 muted violet bags, 3 plaid purple bags.
mirrored green bags contain 4 posh purple bags, 2 dotted blue bags, 1 dull turquoise bag, 2 plaid purple bags.
striped tomato bags contain 5 drab white bags.
muted teal bags contain 5 shiny lime bags.
vibrant bronze bags contain 3 shiny gold bags, 5 striped fuchsia bags, 5 mirrored orange bags, 2 bright green bags.
clear olive bags contain 3 posh violet bags, 1 bright beige bag.
clear maroon bags contain 1 vibrant lime bag, 2 muted coral bags.
faded coral bags contain 4 dim beige bags, 4 bright magenta bags, 3 vibrant magenta bags, 1 bright silver bag.
pale bronze bags contain 1 dark teal bag, 4 dotted aqua bags.
striped aqua bags contain 3 faded aqua bags.
vibrant cyan bags contain 2 mirrored blue bags, 4 striped black bags, 4 clear black bags.
wavy coral bags contain 4 drab salmon bags, 3 light orange bags, 3 posh aqua bags.
mirrored salmon bags contain 4 pale lime bags.
plaid magenta bags contain 1 dim yellow bag, 1 light indigo bag.
dim brown bags contain 3 vibrant purple bags, 2 striped gray bags, 4 mirrored salmon bags, 2 muted maroon bags.
dull magenta bags contain 1 mirrored green bag, 4 dull coral bags.
dark silver bags contain 5 dotted gray bags.
pale tomato bags contain 1 vibrant blue bag, 4 shiny green bags.
plaid tomato bags contain 4 mirrored chartreuse bags, 1 plaid white bag, 4 wavy magenta bags.
faded magenta bags contain 4 dull yellow bags, 3 wavy silver bags.
mirrored crimson bags contain 3 muted tan bags, 5 posh beige bags.
muted green bags contain 4 dim black bags.
wavy chartreuse bags contain 1 plaid tan bag, 5 bright tan bags, 2 posh beige bags.
wavy plum bags contain 2 clear purple bags, 5 dotted violet bags.
plaid indigo bags contain 1 dull brown bag, 3 clear chartreuse bags, 5 posh gold bags, 1 pale teal bag.
posh teal bags contain 3 light magenta bags, 3 muted white bags, 3 dim blue bags.
striped salmon bags contain 4 shiny coral bags.
pale green bags contain 4 dark gold bags, 4 striped teal bags.
vibrant yellow bags contain 4 faded salmon bags, 1 drab beige bag, 1 muted black bag, 5 clear lavender bags.
dim cyan bags contain 2 mirrored turquoise bags.
wavy turquoise bags contain 4 dark turquoise bags, 3 bright tan bags, 4 muted tomato bags.
bright cyan bags contain 5 wavy indigo bags.
plaid red bags contain 1 mirrored coral bag, 2 dull plum bags, 4 vibrant coral bags, 4 vibrant lavender bags.
dark chartreuse bags contain 5 mirrored salmon bags, 5 posh salmon bags, 2 faded turquoise bags.
plaid gray bags contain 1 dim gold bag, 4 faded olive bags.
vibrant tomato bags contain 5 wavy maroon bags, 1 pale red bag.
faded purple bags contain 1 faded tomato bag, 1 striped black bag, 5 vibrant purple bags.
dotted salmon bags contain 3 bright gold bags, 5 dull gray bags, 3 dim blue bags.
drab salmon bags contain 3 mirrored green bags, 1 mirrored tan bag.
pale blue bags contain 4 dotted fuchsia bags.
faded cyan bags contain 2 striped orange bags, 1 vibrant gold bag, 2 bright orange bags, 1 muted gray bag.
dull red bags contain 2 drab teal bags, 2 light bronze bags.
wavy beige bags contain 1 plaid tan bag, 5 dotted indigo bags, 2 dotted gold bags.
dim red bags contain 5 pale magenta bags.
dark green bags contain 5 muted cyan bags, 3 faded brown bags.
muted cyan bags contain 3 drab tomato bags, 4 drab white bags.
mirrored maroon bags contain 5 wavy tomato bags, 2 vibrant white bags.
faded indigo bags contain 5 dim olive bags, 5 drab tan bags, 3 light orange bags.
light lavender bags contain 1 faded salmon bag, 5 pale lime bags, 4 dark maroon bags.
dim aqua bags contain 4 faded gold bags, 1 striped fuchsia bag.
shiny violet bags contain 1 pale yellow bag, 4 mirrored aqua bags.
wavy blue bags contain 1 dim fuchsia bag, 3 clear gold bags, 1 faded aqua bag, 1 light red bag.
striped teal bags contain 3 mirrored silver bags.
striped green bags contain 1 muted teal bag.
vibrant teal bags contain 3 muted indigo bags.
shiny turquoise bags contain 3 dull chartreuse bags.
bright lime bags contain 5 bright magenta bags, 1 dull orange bag.
shiny red bags contain 4 drab tan bags, 4 posh turquoise bags.
dull violet bags contain 4 shiny silver bags, 3 striped crimson bags, 1 mirrored plum bag.
dim black bags contain 1 posh magenta bag, 3 mirrored turquoise bags, 2 faded tomato bags, 4 dim turquoise bags.
muted maroon bags contain 2 mirrored tan bags, 3 clear coral bags.
posh yellow bags contain 1 bright tan bag, 5 mirrored bronze bags.
clear purple bags contain 5 shiny black bags.
dim silver bags contain 4 clear brown bags.
bright black bags contain 4 posh fuchsia bags.
shiny plum bags contain 1 mirrored cyan bag.
striped lavender bags contain 3 pale lavender bags, 4 muted cyan bags.
drab tan bags contain no other bags.
bright olive bags contain 3 muted coral bags.
dim plum bags contain 3 drab tan bags, 5 pale indigo bags.
light teal bags contain 2 dotted blue bags, 5 muted salmon bags, 2 bright purple bags.
clear lavender bags contain 2 muted lime bags, 5 plaid magenta bags, 3 pale lime bags, 1 drab aqua bag.
muted black bags contain 3 light crimson bags, 4 mirrored blue bags.
clear aqua bags contain 5 plaid gold bags.
dark teal bags contain 1 bright purple bag, 1 dotted coral bag, 5 plaid aqua bags, 5 posh maroon bags.
mirrored gray bags contain 3 dim turquoise bags, 4 bright black bags, 1 drab lavender bag.
vibrant fuchsia bags contain 1 vibrant magenta bag.
bright yellow bags contain 1 mirrored cyan bag, 1 clear olive bag.
vibrant red bags contain 1 dotted indigo bag, 2 faded beige bags, 1 drab tomato bag.
striped maroon bags contain 3 plaid aqua bags, 2 dim maroon bags, 4 plaid chartreuse bags.
pale tan bags contain 5 posh gray bags, 3 wavy violet bags.
'
]

{ #category : #data }
AdventOfCode2020Tests >> dataForDay08 [
	^ 'jmp +1
acc -15
acc +14
acc +18
jmp +443
jmp +286
acc +27
jmp +522
jmp +1
acc -19
acc +22
acc +37
jmp +111
acc +28
acc +43
acc +18
nop +597
jmp +479
jmp +604
jmp +499
acc +0
acc +22
acc +13
jmp +566
acc -12
acc +0
nop +153
jmp +173
jmp +192
jmp +292
acc +36
acc +7
jmp +440
acc -17
acc +40
acc +24
acc -7
jmp +519
nop +16
acc +15
acc +42
jmp +445
jmp +350
acc +42
acc +12
acc +2
jmp +133
acc +12
acc +3
acc +27
jmp +186
acc +25
acc +46
jmp +285
acc +32
acc -11
acc -6
jmp +565
nop +215
acc +1
acc +35
jmp +1
jmp +502
acc +27
acc +19
acc -8
acc -8
jmp +531
jmp -21
nop +292
acc +8
acc -13
jmp +26
acc +1
acc +45
nop -42
jmp +323
jmp +39
jmp +336
acc +19
jmp -51
acc +45
acc +26
jmp +278
jmp +6
acc +40
nop +271
acc -10
nop -4
jmp +272
nop -61
acc +4
acc -14
acc +27
jmp -70
acc -9
acc +29
jmp +416
acc +25
acc +45
jmp +19
jmp +39
acc -19
acc +7
jmp +248
acc +11
acc +36
jmp +515
acc +45
acc +49
jmp +329
acc +30
acc +31
acc +28
acc +26
jmp +8
jmp +283
acc +32
jmp +127
acc +4
acc +20
jmp +92
jmp +50
jmp +133
acc +5
acc +8
jmp +313
acc +38
acc +34
jmp +395
acc +14
acc +29
jmp +392
nop +246
jmp +374
nop +429
nop +388
acc +3
acc +0
jmp +432
acc -1
acc +35
acc +35
jmp +148
acc +8
acc +11
acc +12
acc -10
jmp +434
acc -19
jmp +330
nop +329
acc +30
jmp +239
acc -6
jmp -136
jmp +418
nop +385
jmp +1
acc +34
acc +9
jmp +410
nop -13
acc +31
acc +15
acc +37
jmp -142
jmp +109
acc -16
nop +405
nop +343
jmp +8
acc +44
acc -15
acc +7
acc +9
jmp +185
acc +6
jmp +35
nop -25
jmp +93
acc +22
acc -17
acc +15
acc +39
jmp +41
nop -123
acc +15
acc +6
jmp -35
acc +48
jmp +422
acc -7
nop +67
nop +66
acc +48
jmp -29
acc -11
acc +16
jmp +92
acc +45
jmp +92
jmp +212
acc -3
acc -18
nop -186
nop +7
jmp -28
nop +292
acc +7
nop -120
acc +46
jmp +48
acc -3
acc -16
acc +50
jmp -44
acc -2
acc -11
jmp +236
jmp +344
acc +33
acc +44
acc +39
nop -45
jmp -53
acc -11
nop +380
acc +35
jmp +113
nop +203
acc +40
jmp +167
acc +44
jmp +394
jmp +229
jmp -167
jmp -204
acc +21
acc +49
jmp +25
acc -19
acc -17
acc +44
jmp -11
acc +40
acc +12
jmp +253
acc +21
jmp +349
jmp +285
acc +0
nop +261
acc +15
acc +38
jmp +10
acc +27
jmp +1
jmp +373
jmp -151
acc +6
jmp -48
acc +14
acc -8
jmp -61
acc +8
acc +20
jmp +1
jmp +1
jmp +208
acc -18
acc +32
jmp +94
jmp +262
acc +0
jmp -156
nop +188
nop +312
acc +21
acc +6
jmp -123
acc +47
jmp +316
acc +25
nop +290
jmp +62
acc -7
acc +36
nop +212
acc +14
jmp +332
jmp +291
jmp +226
acc +30
jmp -161
acc +39
acc +38
jmp +203
nop +63
nop -6
acc -15
nop -56
jmp +72
acc +1
acc +34
acc +22
acc +19
jmp -135
acc +27
jmp -303
acc +1
acc +48
acc -19
jmp +142
acc +50
jmp +298
acc +43
acc +0
acc +50
acc +12
jmp +137
acc +41
nop +252
jmp -310
acc +13
acc +34
acc -15
acc +43
jmp +236
acc +5
acc -8
acc +25
acc +45
jmp +153
acc -12
acc +31
acc -1
jmp +120
jmp +236
acc +38
nop -238
jmp -328
jmp +81
acc +48
acc +15
acc -9
jmp -73
nop -49
jmp -271
acc -17
acc -17
jmp +106
nop +212
jmp -290
acc +36
nop +109
jmp +186
jmp -310
acc +4
acc +16
jmp +117
jmp +1
acc +10
jmp +20
acc +12
jmp -311
acc +12
acc +30
nop +182
jmp -315
acc +25
acc +12
acc +30
jmp +50
acc -19
jmp -333
acc +30
nop +87
jmp -199
acc +8
jmp +112
acc -8
jmp -313
acc +7
acc +32
jmp +1
jmp +230
acc +25
acc +45
acc +20
acc +0
jmp -307
acc +30
nop -253
acc +7
acc +39
jmp -113
acc -12
jmp +209
acc +42
acc +17
acc -19
acc +24
jmp -170
acc +30
acc +9
acc -1
jmp -328
acc +19
acc +45
jmp +132
nop -244
nop +35
jmp +34
acc -10
acc +26
acc +35
nop -238
jmp +54
acc +15
nop -378
acc +42
jmp -43
acc -9
acc -5
acc -11
nop -307
jmp -129
nop -202
acc -9
nop -376
acc +11
jmp -75
jmp +14
acc -1
acc +32
acc -14
acc +16
jmp +39
acc +42
acc +32
jmp -133
acc +1
acc +17
nop +85
acc +35
jmp +83
acc +27
acc +0
acc -12
jmp -93
acc +48
acc +35
nop +154
jmp -287
jmp -347
jmp -348
acc +18
jmp -374
acc -15
jmp +36
jmp -123
acc -11
jmp +55
acc +19
acc +23
jmp -339
nop +5
acc +44
acc +2
jmp +1
jmp -417
acc +23
jmp -253
acc -9
acc -3
jmp -138
jmp -227
acc +12
jmp -437
acc +47
acc +19
acc -6
jmp -245
acc +2
jmp -328
acc -14
acc +25
acc +4
acc -2
jmp -411
jmp -351
jmp -459
acc +3
acc +48
jmp -134
nop +54
acc -14
jmp -298
jmp -401
acc -14
acc +25
nop -55
acc -10
jmp -312
acc -7
acc +45
jmp -74
acc +30
jmp -462
acc +5
acc -8
jmp -355
acc +9
acc +44
acc +44
jmp -150
jmp -484
acc +14
acc +19
acc -6
jmp -474
acc -18
jmp -166
jmp -264
acc -15
acc +17
acc +29
jmp -149
nop -273
acc +31
acc +0
acc -2
jmp -410
jmp -411
acc +47
acc -6
nop -287
jmp -436
acc +4
nop +88
jmp -158
acc +32
jmp +1
acc -15
jmp -319
acc -6
acc -18
acc +49
jmp -256
acc -18
acc +31
acc +27
acc +27
jmp -351
jmp +58
acc +12
jmp +1
acc +32
nop -151
jmp -411
acc +19
acc +7
jmp -287
acc +30
jmp -496
acc -11
acc +5
acc +42
acc +25
jmp -249
acc -1
jmp -243
jmp -190
acc +32
acc +32
acc +14
jmp +12
acc +5
acc +30
acc +34
jmp -46
acc -13
acc +5
acc +45
jmp -271
acc +29
acc +37
jmp -323
nop -18
acc -2
acc +21
acc -12
jmp -453
acc -14
acc +19
nop -173
jmp -411
acc +24
acc -7
nop -136
acc +6
jmp -357
acc -1
acc -1
acc +32
jmp -264
acc +26
jmp -175
acc +10
acc +35
nop -361
jmp -493
acc +14
jmp -206
jmp -138
acc -1
jmp -156
acc +3
acc +11
acc -2
jmp -213
acc +35
acc -13
acc +47
acc +45
jmp -376
jmp -543
jmp -479
acc +29
jmp -532
acc +28
acc +47
acc -11
acc -14
jmp +1
'
]

{ #category : #data }
AdventOfCode2020Tests >> dataForDay09 [
	^ '23
3
36
14
50
8
2
44
30
37
20
5
34
41
31
39
28
24
49
42
22
4
45
46
32
6
35
7
26
15
21
8
9
12
25
10
11
13
14
16
17
57
18
64
19
20
22
33
27
23
24
28
29
30
38
31
37
35
21
26
44
25
32
34
36
69
40
51
39
43
41
45
46
63
49
54
47
66
64
55
52
65
53
57
59
83
61
92
70
97
79
80
82
84
86
87
91
93
96
101
99
148
105
107
109
110
112
114
116
166
204
191
196
149
159
161
198
240
170
173
178
190
219
314
200
206
222
217
216
223
224
428
412
265
319
404
349
357
308
446
331
670
343
348
384
368
407
514
406
737
628
433
439
440
584
667
596
741
749
639
918
651
656
674
727
679
691
1040
781
1342
775
813
839
1023
1406
873
1455
1131
1114
1420
1235
1247
1440
1347
1290
1307
2366
1330
1353
1370
1454
1466
2071
1556
2467
1588
1652
2701
1896
2723
2895
2245
2444
3814
2577
2617
2537
2637
2597
2620
2807
2700
5140
3208
4289
5214
3054
5168
3144
6198
5498
4353
4141
4513
4689
4782
4822
9511
5174
9604
5134
5681
6761
7096
5320
7561
5844
7833
6262
7343
14386
7195
7285
8318
10951
8866
8494
8654
10978
11878
15627
11895
14538
15513
10454
12876
13129
12106
14480
11164
13039
13547
15837
15689
27356
15779
15603
24992
19269
21742
17148
19472
36417
31628
21618
28503
22349
24293
24203
22560
42959
23270
32927
24711
38539
60710
35161
31292
31382
32751
34872
35075
41351
45619
36620
43765
41090
54188
47473
43967
44909
99097
67162
85318
57432
47981
54562
56003
67912
62674
85999
79363
64043
92890
67623
100663
71695
80385
77710
98155
91440
127698
92382
88876
131955
99471
167825
102543
110565
120046
103984
117236
118677
126717
151550
194946
167094
131666
148008
139318
149405
202947
158095
169150
226188
257995
202014
188347
199441
263621
321663
206527
229242
227801
224030
221220
270984
245394
274725
279674
281071
287326
288723
297413
379315
307500
357536
327245
390370
387788
423471
390361
572138
405968
427747
619076
495014
445250
449021
502291
466614
516378
520119
562051
560745
568397
576049
586136
604913
634745
776266
717615
717606
778149
793756
856975
851218
876768
833715
872997
894271
911864
1184229
1165658
1338894
982992
1146881
1130448
1279657
1383062
1144446
1568824
1191049
1352360
1412894
2003856
1435221
2038655
1571905
2574111
1690690
2113440
3682264
1706712
1767268
1806135
2058745
2127438
2129873
2277329
2174041
3318487
3140729
2692551
2496806
3043050
2543409
2603943
3158495
5009177
3007126
3125911
4240878
3473980
3397402
4336074
3512847
3573403
3880753
3826013
3864880
5332536
4257311
5790176
4451370
4670847
5040215
5100749
5147352
5586459
7677973
5550535
5611069
6133037
7299993
8437617
6699314
9589847
10711818
7223415
7086250
7706766
7399416
7690893
8083324
8122191
8928158
8708681
9122217
9491585
9711062
10140964
10248101
10697887
14708676
11161604
14539227
15306739
15828957
14406080
13785564
13922729
14930181
14309665
17205541
24654181
15090309
15482740
16813110
17011482
24212526
17636839
19202647
24547044
19632549
19959163
20389065
31550709
21859491
24947168
25084333
28095229
29229468
28191644
31941663
27708293
32727148
29239846
40136921
41418067
47424403
37596002
35115289
33824592
34648321
39591712
36839486
38835196
40021614
40348228
41818654
45336233
46806659
56948139
60918792
52792626
55803522
55899937
57431490
41682220
67842437
84927945
78426908
68472913
109740765
68939881
72244323
76861100
70664078
71487807
82175719
75674682
180404843
80369842
82030448
87018453
160602627
113926543
136315350
94474846
97485742
124372850
97582157
112346298
109524657
144147595
139603959
226272841
154274771
140427688
141184204
142151885
157850401
242633075
238766361
156044524
162400290
167388295
169048901
207010399
196543110
191960588
241729752
206821144
251760513
195067899
303584494
406035284
266621069
354360878
280788163
280031647
281611892
282579573
308572499
283336089
449000187
436797651
318444814
323432819
325093425
489400717
375870045
361009489
387028487
664593983
398781732
524309325
401889043
475856062
605125072
546652716
547409232
562400055
564191465
891289760
945434448
606768908
659206134
1096169625
930201727
641877633
1532967276
794300876
648526244
686102914
748037976
1123908021
907662205
785810219
1445016353
1008657951
877745105
949298275
1022508778
1094061948
1109052771
1109809287
1756695927
1265975042
1248646541
1255295152
1290403877
1578727971
1334629158
1480403790
1327980547
1396564220
1434140890
1772434265
2486390176
1957956226
1663555324
1894862990
1735108494
1827043380
1886403056
1900253883
1971807053
2116570726
2203114719
2218862058
2358455828
2503941693
2514621583
2539050418
2618384424
3465131027
3012868861
4347498019
2808384337
2724544767
2830705110
4747977355
3398663818
3490598704
3549958380
3706915547
3562151874
4030158099
6562827241
3786656939
4802512163
4510857471
4319685445
4421976777
5122326117
5449089534
5042992111
5053672001
5157434842
5342929191
5532929104
5555249877
8349843544
7810284149
6123208585
6321303814
7197514251
6889262522
7112110254
7256873927
8864350389
14419600266
7816815038
8106342384
9668292313
16166658582
13228668501
8741662222
10677575994
10096664112
14987558974
10200426953
21970330723
10500364033
10875858295
11656137689
11678458462
12444512399
15853772476
13012471107
13578177741
19419238216
15073688965
14368984181
23512835140
15923157422
16558477260
16848004606
24595434698
18409954535
18838326334
18942089175
20972522407
20297091065
21076285248
21376222328
21878885415
22156501722
22178822495
39366607616
27518201364
27381455288
28935628529
31988132276
39716329281
43129024129
29442673146
30292141603
30927461441
59863089970
35686330940
45494105789
37248280869
37352043710
37780415509
49869550616
39239180240
47678546353
41373376313
84926827222
43532724050
44035387137
44335324217
49560277783
74327528740
54899656652
59369587564
58378301675
61430805422
80612556553
138990858228
67540422472
61219603044
66613792381
73466746449
73038374650
74600324579
75028696378
75132459219
77019595749
82771904290
155810278940
92013870570
84906100363
87568111187
87868048267
93595664920
93895602000
133969912143
135819927623
113277958327
117747889239
119597904719
249097885950
127833395425
142569118850
134257977694
139652167031
140080538830
146505121099
148067071028
149629020957
275900466453
152152054968
159791500039
167678004653
211343554159
172474211550
178801702363
207173560327
181463713187
347254099157
211643491239
231025847566
247535936021
257400056270
237345793958
301781075925
262091373119
267485562456
282325048722
273910144725
279732705861
413990683555
417114583413
356802581284
309420520996
319830059621
327469504692
366965060366
780955743921
390445193602
539126869883
866596374575
591745569718
418809507145
1097622222141
442669338805
468371641524
484881729979
494745850228
499437167077
541395707181
529576935575
549810611178
553642850586
1280587058130
804166371224
856660022360
629250580617
809634399171
1018182252702
647299564313
694434565058
1286180134776
809254700747
833114532407
2383802356917
887181148669
861478845950
1014458665554
927551068784
1391055781525
953253371503
979627580207
994183017305
1040832874258
1070972642756
1433416951841
1103453461764
1200942414899
1691347519893
1276550144930
3584744771816
1438505281364
1456933963484
1534480712982
2119294667183
1503689265805
1642369233154
1880804440287
1694593378357
1964932307714
1990634610433
2318606850309
2431888655783
1907178648991
3389579493065
1932880951710
2020460454465
2451116980789
2111805517014
2304395876663
2380003606694
2477492559829
2639447696263
4684399483357
2715055426294
3364112612475
3345683930355
4339067304774
3038169978787
5515662538616
4736284532446
3336962611511
3992609957301
3601772027348
3840059600701
6965884639823
3953341406175
3927639103456
4018984166005
5116940256092
5622232481813
4562922497803
4416201393677
6682646541866
4781888436492
8553832517403
5192547986123
5354503122557
6383853909142
5753225405081
8164694525151
6375132590298
8755268698451
6639942006135
6938734638859
7355946777516
7264601714967
10893523743279
7441831628049
8709527539948
9044579359548
7880980509631
7946623269461
9608749379800
12435871946947
8979123891480
15139122607593
9198089830169
9974436422615
11738357031699
13109172182597
10547051108680
20047906821456
12128357995379
12393167411216
17799848057999
13731079367814
15648262178807
13578676644994
14203336353826
20382495216408
17489729889431
19172526252784
15322812137680
16860104401111
20274147920847
24301936029160
19684980301160
22675409104059
22940218519896
18177213721649
36908011222567
19745140938849
23866715027078
23656223291277
24125727753674
43551695328238
25707034640373
24521525406595
25971844056210
27309756012808
35393403117656
27782012998820
28901488782674
32812542027111
37872225105839
32182916538791
33500025859329
35007792438840
35037318122760
37862194022809
42043928748727
41833437012926
37922354660498
52303538405415
42302941475323
43401364230126
43870868692523
47522938318355
47781951044951
48647253160269
86173810167846
59492672551599
60979636495050
53281600069018
'
]

{ #category : #data }
AdventOfCode2020Tests >> dataForDay10 [
	^ '128
6
152
16
118
94
114
3
146
44
113
83
46
40
37
72
149
155
132
9
75
1
82
80
111
124
66
122
129
32
30
136
112
65
90
117
11
45
161
55
135
17
159
38
51
131
12
123
81
64
50
43
19
63
13
153
110
27
23
104
145
18
125
86
10
76
26
142
59
47
160
79
139
54
121
97
162
36
107
56
25
99
24
31
69
137
33
138
130
158
91
2
74
101
73
20
98
154
89
62
100
39
'
]

{ #category : #running }
AdventOfCode2020Tests >> setUp [
	super setUp.
	
	aoc := AdventOfCode2020 new.

]

{ #category : #tests }
AdventOfCode2020Tests >> testDay01a [
	self assert: #(1721 979 366 299 675 1456) day01a equals: 514579.
	self assert: self dataForDay01 day01a equals: 956091.

]

{ #category : #tests }
AdventOfCode2020Tests >> testDay01b [
	self assert: #(1721 979 366 299 675 1456) day01b equals: 241861950.
	self assert: self dataForDay01 day01b equals: 79734368.

]

{ #category : #tests }
AdventOfCode2020Tests >> testDay02a [
	self assert: '1-3 a: abcde
1-3 b: cdefg
2-9 c: ccccccccc
' day02a equals: 2.
	self assert: self dataForDay02 day02a equals: 410.

]

{ #category : #tests }
AdventOfCode2020Tests >> testDay02b [
	self assert: '1-3 a: abcde
1-3 b: cdefg
2-9 c: ccccccccc
' day02b equals: 1.
	self assert: self dataForDay02 day02b equals: 694.

]

{ #category : #tests }
AdventOfCode2020Tests >> testDay03a [
	self assert: '..##.......
#...#...#..
.#....#..#.
..#.#...#.#
.#...##..#.
..#.##.....
.#.#.#....#
.#........#
#.##...#...
#...##....#
.#..#...#.#
' day03a equals: 7.
	self assert: self dataForDay03 day03a equals: 268.

]

{ #category : #tests }
AdventOfCode2020Tests >> testDay03b [
	self assert: '..##.......
#...#...#..
.#....#..#.
..#.#...#.#
.#...##..#.
..#.##.....
.#.#.#....#
.#........#
#.##...#...
#...##....#
.#..#...#.#
' day03b equals: 336.
	self assert: self dataForDay03 day03b equals: 3093068400.

]

{ #category : #tests }
AdventOfCode2020Tests >> testDay04a [

	self assert: ('' day04WithPassport: #simple) equals: 0.
	self
		assert:
			('ecl:gry pid:860033327 eyr:2020 hcl:#fffffd
byr:1937 iyr:2017 cid:147 hgt:183cm

iyr:2013 ecl:amb cid:350 eyr:2023 pid:028048884
hcl:#cfa07d byr:1929

hcl:#ae17e1 iyr:2013
eyr:2024
ecl:brn pid:760753108 byr:1931
hgt:179cm

hcl:#cfa07d eyr:2025 pid:166559648
iyr:2011 ecl:brn hgt:59in' 
				 day04WithPassport: #simple)
		equals: 2.
	self
		assert: (self dataForDay04 day04WithPassport: #simple)
		equals: 213
]

{ #category : #tests }
AdventOfCode2020Tests >> testDay04b [
	self
		assert:
			('ecl:gry pid:860033327 eyr:2020 hcl:#fffffd
byr:1937 iyr:2017 cid:147 hgt:183cm

iyr:2013 ecl:amb cid:350 eyr:2023 pid:028048884
hcl:#cfa07d byr:1929

hcl:#ae17e1 iyr:2013
eyr:2024
ecl:brn pid:760753108 byr:1931
hgt:179cm

hcl:#cfa07d eyr:2025 pid:166559648
iyr:2011 ecl:brn hgt:59in' 
				 day04WithPassport: #full)
		equals: 2.
	self
		assert: (self dataForDay04 day04WithPassport: #full)
		equals: 147
]

{ #category : #tests }
AdventOfCode2020Tests >> testDay05a [
	self assert: (aoc day05a: 'FBFBBFFRLR
    BFFFBBFRRR
    FFFBBBFRRR
    BBFFBBFRLL
') equals: 820.
	self assert: (aoc day05a: self dataForDay05) equals: 965.
]

{ #category : #tests }
AdventOfCode2020Tests >> testDay05b [
	self assert: (aoc day05b: self dataForDay05) equals: 524.
]

{ #category : #tests }
AdventOfCode2020Tests >> testDay06a [
	self assert: (aoc day06a: 'abc

a
b
c

ab
ac

a
a
a
a

b') equals: 11.
	self assert: (aoc day06a: self dataForDay06) equals: 6590.

]

{ #category : #tests }
AdventOfCode2020Tests >> testDay06b [
	self assert: (aoc day06b: 'abc

a
b
c

ab
ac

a
a
a
a

b') equals: 6.
	self assert: (aoc day06b: self dataForDay06) equals: 3288.

]

{ #category : #tests }
AdventOfCode2020Tests >> testDay07a [
	self assert: (aoc day07a: 'light red bags contain 1 bright white bag, 2 muted yellow bags.
dark orange bags contain 3 bright white bags, 4 muted yellow bags.
bright white bags contain 1 shiny gold bag.
muted yellow bags contain 2 shiny gold bags, 9 faded blue bags.
shiny gold bags contain 1 dark olive bag, 2 vibrant plum bags.
dark olive bags contain 3 faded blue bags, 4 dotted black bags.
vibrant plum bags contain 5 faded blue bags, 6 dotted black bags.
faded blue bags contain no other bags.
dotted black bags contain no other bags.' with: 'shiny gold') equals: 4.
	self assert: (aoc day07a: self dataForDay07 with: 'shiny gold') equals: 326.

]

{ #category : #tests }
AdventOfCode2020Tests >> testDay07b [
	self assert: (aoc day07b: 'shiny gold bags contain 1 dotted black bag, 2 faded blue bags.
faded blue bags contain no other bags.
dotted black bags contain no other bags.' with: 'shiny gold') equals: 3.
	self assert: (aoc day07b: 'shiny gold bags contain 1 dark olive bag, 2 faded blue bags.
dark olive bags contain 3 faded blue bags, 4 dotted black bags.
faded blue bags contain no other bags.
dotted black bags contain no other bags.' with: 'shiny gold') equals: 10.
	self assert: (aoc day07b: 'light red bags contain 1 bright white bag, 2 muted yellow bags.
dark orange bags contain 3 bright white bags, 4 muted yellow bags.
bright white bags contain 1 shiny gold bag.
muted yellow bags contain 2 shiny gold bags, 9 faded blue bags.
shiny gold bags contain 1 dark olive bag, 2 vibrant plum bags.
dark olive bags contain 3 faded blue bags, 4 dotted black bags.
vibrant plum bags contain 5 faded blue bags, 6 dotted black bags.
faded blue bags contain no other bags.
dotted black bags contain no other bags.' with: 'shiny gold') equals: 32.
	self assert: (aoc day07b: 'shiny gold bags contain 2 dark red bags.
dark red bags contain 2 dark orange bags.
dark orange bags contain 2 dark yellow bags.
dark yellow bags contain 2 dark green bags.
dark green bags contain 2 dark blue bags.
dark blue bags contain 2 dark violet bags.
dark violet bags contain no other bags.' with: 'shiny gold') equals: 126.
	self assert: (aoc day07b: self dataForDay07 with: 'shiny gold') equals: 5635.

]

{ #category : #tests }
AdventOfCode2020Tests >> testDay08a [
	self assert: (aoc day08a: 'nop +0
acc +1
jmp +4
acc +3
jmp -3
acc -99
acc +1
jmp -4
acc +6') equals: 5.
	self assert: (aoc day08a: self dataForDay08) equals: 1501.

]

{ #category : #tests }
AdventOfCode2020Tests >> testDay08b [
	self assert: (aoc day08b: 'nop +0
acc +1
jmp +4
acc +3
jmp -3
acc -99
acc +1
jmp -4
acc +6') equals: 8.
	self assert: (aoc day08b: self dataForDay08) equals: 509.

]

{ #category : #tests }
AdventOfCode2020Tests >> testDay09a [
	self assert: (('35
20
15
25
47
40
62
55
65
95
102
117
150
182
127
219
299
277
309
576' lines collect: #asNumber) day09a: 5) equals: 127.
	self assert: ((self dataForDay09 lines collect: #asNumber) day09a: 25) equals: 41682220
]

{ #category : #tests }
AdventOfCode2020Tests >> testDay09b [
	self assert: (('35
20
15
25
47
40
62
55
65
95
102
117
150
182
127
219
299
277
309
576' lines collect: #asNumber) day09b: 5) equals: 62.
	self assert: ((self dataForDay09 lines collect: #asNumber) day09b: 25) equals: 5388976
]

{ #category : #tests }
AdventOfCode2020Tests >> testDay10a [
	self assert: '16
10
15
5
1
11
7
19
6
12
4
' asLinesThenNumbers day10a equals: 35.
	self assert: '28
33
18
42
31
14
46
20
48
47
24
23
49
45
19
38
39
11
1
32
25
35
8
17
7
9
4
2
34
10
3' asLinesThenNumbers day10a equals: 220.
	self assert: self dataForDay10 asLinesThenNumbers day10a equals: 2232.

]

{ #category : #tests }
AdventOfCode2020Tests >> testDay10b [
	self assert: '16
10
15
5
1
11
7
19
6
12
4
' asLinesThenNumbers day10b equals: 8.
	self assert: '28
33
18
42
31
14
46
20
48
47
24
23
49
45
19
38
39
11
1
32
25
35
8
17
7
9
4
2
34
10
3' asLinesThenNumbers day10b equals: 19208.
	self assert: self dataForDay10 asLinesThenNumbers day10b equals: 173625106649344.

]
